### ISSUE TITLE
bug: AWS Pricing Plugin Runs out of memory and quits

### ISSUE THREAD

**Issue by bbernays** [cloudquery/cloudquery#10206]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

running sync with default configurations seems on CentOS VM causes a crash

### Expected Behavior

No crash

### CloudQuery (redacted) config

```
kind: source
spec:
  name: "awspricing"
  path: "cloudquery/awspricing"
  version: "v1.1.4"
  tables: ["*"]
  destinations:
    - "postgresql"
---
kind: destination
spec:
  name: "postgresql"
  path: "cloudquery/postgresql"
  version: "v2.1.4"
  write_mode: "overwrite-delete-stale" # overwrite-delete-stale, overwrite, append
  spec:
    connection_string: ""
```

### Steps To Reproduce

run sync

### CloudQuery (redacted) logs

https://gist.github.com/Smithx10/eb5ddcff468db62a5c23b86e13525be6

### CloudQuery version

unknown

### Pull request (optional)

- [ ] I can submit a pull request
