### ISSUE TITLE
bug: Column name incorrect in aws_cloudformation_stacks table

### ISSUE THREAD

**Issue by pchaganti** [cloudquery/cloudquery#10778]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The cloud formation_stacks table has a column that is named **notification_ar_ns**. 

### Expected Behavior

It should be named **_notification_arns_** to match the API call response.

### CloudQuery (redacted) config

```yaml
kind: source
spec:
  name: aws
  path: cloudquery/aws
  version: "v17.2.0"
```

### CloudQuery (redacted) logs

```
```

### CloudQuery version

3.2.1

### Additional Context

https://www.cloudquery.io/docs/plugins/sources/aws/tables/aws_cloudformation_stacks

### Pull request (optional)

- [ ] I can submit a pull request
