### ISSUE TITLE
feat: [azure] add skip-subscriptions option in azure spec

### ISSUE THREAD

**Issue by chinmayb** [cloudquery/cloudquery#10829]
### Which problem is this feature request solving?

I would like a feature in the azure source plugin, where I can skip some subscriptions from discovering the resources.

just like the skip organization/accountIDs provided in aws source plugins.

### Describe the solution you'd like

add the following field in spec

`skip_subscriptions: [<subID1>, <subID2>]`

It will look like

```
kind: source
spec:
  # Source spec section
  name: "azure"
  path: "cloudquery/azure"
  version: "v7.5.0"
  destinations: ["postgresql"]
  tables: ["azure_compute_virtual_machines"]
  spec:
    # Azure Spec section
    subscriptions:[""]
    skip-subscriptions: ["sub-id-1", "sub-id-2"]
```   

This goes inline with https://www.cloudquery.io/docs/plugins/sources/aws/configuration#aws-spec 

### Pull request (optional)

- [X] I can submit a pull request
