### ISSUE TITLE
feat: S3 Bucket storage information in cloudquery

### ISSUE THREAD

**Issue by rajeshwarakella1994** [cloudquery/cloudquery#11236]
### Which problem is this feature request solving?

Hello Team,

the aws_s3_bucket table in AWS source plugin today doesn't have anything related to bucket size. 
This information will be very useful to identity buckets which are large and such buckets can be looked into for optimisations to save opearational costs.

### Describe the solution you'd like

Eventhough the S3 API provided by AWS doesn't provide storage statistics, we can retrieve this information from cloudwatch metrics. Here is an example of aws cli which illustrates the same - 

aws cloudwatch get-metric-statistics --namespace AWS/S3 --start-time 2023-06-05T00:00:00 --end-time 2023-06-06T00:00:00 --period 86400 --statistics Average --metric-name BucketSizeBytes --unit Bytes --dimensions Name=BucketName,Value={Bucket-Name} Name=StorageType,Value=StandardStorage

### Pull request (optional)

- [ ] I can submit a pull request

**Comment by bbernays** [comment]
CloudWatch metrics are not a free API. I suggest we use the new `table_options` parameter and `use_paid_apis` to enable users to define exactly what they want to sync.


This would follow the same pattern as #11185

**Comment by disq** [comment]
@rajeshwarakella1994 This feature is now released AWS [18.4.0](https://github.com/cloudquery/cloudquery/compare/plugins-source-aws-v18.3.0...plugins-source-aws-v18.4.0), you can try it with a `table_options` entry in the Spec, like so:

```yaml
    table_options:
      aws_alpha_cloudwatch_metrics:
        - list_metrics:
            namespace: AWS/S3
            metric_name: BucketSizeBytes
          get_metric_statistics:
            - statistics:
                - Average
              start_time: "2023-06-06T00:00:00Z"
              end_time: "2023-06-11T00:00:00Z"
              period: 86400
```

This will list all `BucketSizeBytes` in the `AWS/S3` namespace (so every bucket will get its own metric entry) and get Average statistics with the given time period/options for each. Please let us know if you encounter anything unexpected. (To manage different or changing time periods, [environment variable substitution](https://www.cloudquery.io/docs/advanced-topics/environment-variable-substitution) feature can be used)

**Comment by rajeshwarakella1994** [comment]
Hello @disq .. Thank you very much for the feature and sincere apologies for not being able to respond here.

I am trying to use the configuration that you have mentioned and I get table_options as an unknown attribute from the CLI. Please let me know if any change is required in the configuration. I have mentioned the spec and the error below for your reference - 

AWS source spec - 

kind: source
spec:
  name: "aws_223473372591"
  path: "cloudquery/aws"
  version: "v18.4.0"
  tables: ["*"]
  use_paid_apis: true
  table_options:
    aws_s3_buckets:
      aws_alpha_cloudwatch_metrics:
        - list_metrics:
            namespace: AWS/S3
            metric_name: BucketSizeBytes
          get_metric_statistics:
            - statistics:
                - Average
              start_time: 2023-06-28T00:00:00Z
              end_time:   2023-06-28T11:59:99Z
              period: 86400
    aws_ec2_instances:
      aws_cloudtrail_events:
        lookup_events:
          - start_time: 2023-06-28T00:00:00Z
            end_time:   2023-06-28T11:59:99Z
            lookup_attributes:
              - attribute_key: EventName
                attribute_value: RunInstances
          - start_time: 2023-06-28T00:00:00Z
            end_time:   2023-06-28T11:59:99Z
            lookup_attributes:
              - attribute_key: EventName
                attribute_value: StartInstances
          - start_time: 2023-06-28T00:00:00Z
            end_time:   2023-06-28T11:59:99Z
            lookup_attributes:
              - attribute_key: EventName
                attribute_value: StopInstances

Error message - 
Error: failed to load spec(s) from .\aws.yml, .\postgres.yml. Error: failed to unmarshal file .\aws.yml: failed to decode spec: json: unknown field "table_options"

**Comment by hermanschaaf** [comment]
Hi @rajeshwarakella1994, it looks like your configuration is not quite right, please note that the AWS plugin has it's own inner `spec` section, and both `use_paid_apis ` and `table_options` should go under that. For example, for `aws_cloudtrail_events`, it might look like this:

```
kind: source
spec:
  name: "aws"
  version: "v18.4.0"
  registry: "github"
  path: "cloudquery/aws"
  concurrency: 10000
  skip_dependent_tables: true
  tables:
    - "aws_cloudtrail_events"
  destinations: 
    - "postgresql"
  spec:
    use_paid_apis: true
    table_options:
      aws_cloudtrail_events:
        lookup_events:
          - lookup_attributes:
              - attribute_key: EventName
                attribute_value: StopInstances
          - lookup_attributes:
              - attribute_key: EventName
                attribute_value: DescribeInstances
```
