### ISSUE TITLE
bug: oracledb source plugin incorrectly tries and fails to cast float column to integer

### ISSUE THREAD

**Issue by niclasgrahm** [cloudquery/cloudquery#11538]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When trying to sync a table using the `v1.2.2` plugin I get the following error: 

```
Starting sync for: oracledb (v1.2.2) -> [file_destination]
| Syncing resources... (33/-, 585 resources/s) [0s] Error: failed to sync v1 source oracledb: rpc error: code = Unknown desc = failed to sync resources: failed to sync unmanaged client: failed to read from table REDACTED: sql: Scan error on column index 6, name "REDACTED": converting driver.Value type string ("2367.362") to a int: invalid syntax
```

The column that fails has the data type NUMERIC(20, 4).

### Expected Behavior

The table to sync to my destination

### CloudQuery (redacted) config

```yaml
kind: source
spec:
  name: "oracledb"
  path: "cloudquery/oracledb"
  version: "v1.2.2"
  tables: ["REDACTED"]
  destinations: ["file_destination"]
  spec:
   
    connection_string: "oracle://xx:xx@xx.xx.xx:1521/xx.xx.xx"
```

### Steps To Reproduce

* Windows machine
* cloudquery v3.5.1
* oracledb plugin 1.2.2
* cloudquery sync ./my_config

### CloudQuery (redacted) logs

see above

### CloudQuery version

3.5.1

### Pull request (optional)

- [ ] I can submit a pull request
