### ISSUE TITLE
bug: api error InvalidSnapshot.NotFound aws_ec2_ebs_snapshot_attributes

### ISSUE THREAD

**Issue by kumaresh0** [cloudquery/cloudquery#11707]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

affected table: aws_ec2_ebs_snapshot_attributes, 400 reponse with error

`{"level":"error","module":"cli","client":"32423423:us-**-1","error":"operation error EC2: DescribeSnapshotAttribute, https response error StatusCode: 400, RequestID: e2262c0767ac3, api error InvalidSnapshot.NotFound: The snapshot 'snap-0cc076097084c360a' does not exist.","message":"table resolver finished with error","module":"aws-src","table":"aws_ec2_ebs_snapshot_attributes",`

### Expected Behavior

 i think for non-found responses it should not be 400 responses and errors.

maybe it can be fixed with 404 or just a warning on log instead of error.

Please let me know if any further information needed 

### CloudQuery (redacted) config

```
  kind: source
  spec:
    name: "aws-tables"
    path: "cloudquery/aws"
    version: "v18.4.0"
    concurrency: 300000
    destinations: ["postgresql"]
    tables:
      - "*"
    skip_tables:
      - aws_organization_resource_policies
      - aws_organizations
      - aws_organizations_*
      - aws_iam_*
      - aws_cloudtrail_*
      - aws_cloudwatchlogs_*
      - aws_athena_*
      - aws_cloudtrail_events 
      - aws_shield_*
      - aws_waf_*
      - aws_wafregional_*
      - aws_wafv2_*
      - aws_securityhub_*
      - aws_networkfirewall_*
      - aws_inspector2_findings
      - aws_inspector_findings
      - aws_guardduty_*
      - aws_frauddetector_*
      - aws_config_*
      - aws_accessanalyzer_*
      - aws_stepfunctions_*
    spec:
      org:
        member_role_name: cq-memeber-role
      max_retries: 2
      max_backoff: 30
      regions: 
        - us-west-1
  ---
  kind: destination
  spec:
    name: postgresql
    path: cloudquery/postgresql
    version: "v4.2.2"
    write_mode: "overwrite-delete-stale"
    spec:
      connection_string: ${CQ_DSN}
```

### CloudQuery (redacted) logs

`{"level":"error","module":"cli","client":"32423423:us-**-1","error":"operation error EC2: DescribeSnapshotAttribute, https response error StatusCode: 400, RequestID: e2262c0767ac3, api error InvalidSnapshot.NotFound: The snapshot 'snap-0cc076097084c360a' does not exist.","message":"table resolver finished with error","module":"aws-src","table":"aws_ec2_ebs_snapshot_attributes",`

### CloudQuery version

cloudquery version 3.5.4

### Pull request (optional)

- [ ] I can submit a pull request
