### ISSUE TITLE
bug: InvalidPaginationTokenException: You specified an invalid value for nextToken.

### ISSUE THREAD

**Issue by kumaresh0** [cloudquery/cloudquery#11706]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

affected table: aws_servicequotas_quotas, encountering 400 with below error

`,"error":"operation error Service Quotas: ListServiceQuotas, https response error StatusCode: 400, RequestID: 47f57252-d9cc-42cf-94-4cf65789d, InvalidPaginationTokenException: You specified an invalid value for nextToken. You must get the value from the response to the previous API call.","message":"table resolver finished with error","module":"aws-src","table":"aws_servicequotas_quotas","time":`

### Expected Behavior

non 400 response

### CloudQuery (redacted) config

```
  kind: source
  spec:
    name: "aws-tables"
    path: "cloudquery/aws"
    version: "v18.4.0"
    concurrency: 300000
    destinations: ["postgresql"]
    tables:
      - "*"
    skip_tables:
      - aws_organization_resource_policies
      - aws_organizations
      - aws_organizations_*
      - aws_iam_*
      - aws_cloudtrail_*
      - aws_cloudwatchlogs_*
      - aws_athena_*
      - aws_cloudtrail_events 
      - aws_shield_*
      - aws_waf_*
      - aws_wafregional_*
      - aws_wafv2_*
      - aws_securityhub_*
      - aws_networkfirewall_*
      - aws_inspector2_findings
      - aws_inspector_findings
      - aws_guardduty_*
      - aws_frauddetector_*
      - aws_config_*
      - aws_accessanalyzer_*
      - aws_stepfunctions_*
    spec:
      org:
        member_role_name: cq-memeber-role
      max_retries: 2
      max_backoff: 30
      regions: 
        - '*'
  ---
  kind: destination
  spec:
    name: postgresql
    path: cloudquery/postgresql
    version: "v4.2.2"
    write_mode: "overwrite-delete-stale"
    spec:
      connection_string: ${CQ_DSN}
```

### CloudQuery (redacted) logs

`"error":"operation error Service Quotas: ListServiceQuotas, https response error StatusCode: 400, RequestID: 47f57252-d9cc-42cf-94-4cf65789d, InvalidPaginationTokenException: You specified an invalid value for nextToken. You must get the value from the response to the previous API call.","message":"table resolver finished with error","module":"aws-src","table":"aws_servicequotas_quotas","time":`

### CloudQuery version

cloudquery version 3.5.4

### Pull request (optional)

- [ ] I can submit a pull request
