### ISSUE TITLE
fix(docs): Update Environment and file variable substitution guideline 

### ISSUE THREAD

**Issue by erezrokah** [cloudquery/cloudquery#12153]
It seems the guidelines in https://www.cloudquery.io/docs/advanced-topics/environment-variable-substitution#json-files-in-older-versions are incorrect and one cannot import JSON as is in the new CLI.

JSON files should be imported as shown here

```yaml
kind: destination
spec:
  name: bigquery
  path: cloudquery/bigquery
  version: "v3.1.0"
  write_mode: "append"
  spec:
    project_id: project_id
    dataset_id: dataset_id
    service_account_key_json: |
      ${file:./.config/gcloud/application_default_credentials.json}
```

See https://github.com/cloudquery/cloudquery/issues/12148#issuecomment-1633970110

We should align the docs with this behavior
