### ISSUE TITLE
bug: `tables`command does not work with new sources

### ISSUE THREAD

**Issue by erezrokah** [cloudquery/cloudquery#12270]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Using the spec below:

```yaml
kind: source
spec:
  name: aws
  version: v20.1.0
  destinations: [postgresql]
  path: cloudquery/aws
  tables: ["*"]
---
kind: destination
spec:
  name: "postgresql"
  path: "cloudquery/postgresql"
  version: v5.0.0
  spec:
    connection_string: postgresql://postgres:pass@localhost:5432/postgres
```

And running `cloudquery tables <path-to-spec>` fails with an error:
```
Error: failed to generate docs for aws. Error: rpc error: code = Unimplemented desc = unknown service cloudquery.source.v2.Source
```

### Expected Behavior

The command should not fail and the tables JSON file generated

### CloudQuery (redacted) config

```yaml
kind: source
spec:
  name: aws
  version: v20.1.0
  destinations: [postgresql]
  path: cloudquery/aws
  tables: ["*"]
---
kind: destination
spec:
  name: "postgresql"
  path: "cloudquery/postgresql"
  version: v5.0.0
  spec:
    connection_string: postgresql://postgres:pass@localhost:5432/postgres

```

### Steps To Reproduce

Run `cloudquery tables` with the above spec

### CloudQuery (redacted) logs

```
Error: failed to generate docs for aws. Error: rpc error: code = Unimplemented desc = unknown service cloudquery.source.v2.Source
```

### CloudQuery version

`3.9.2`

### Pull request (optional)

- [X] I can submit a pull request
