### ISSUE TITLE
aws_elbv2_load_balancer_web_acls table does not have the expected primary key on arn

### ISSUE THREAD

**Issue by shoan** [cloudquery/cloudquery#12442]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Running cloudquery (partially) fails to record web acls

2023-07-22T04:08:10Z ERR resource resolver finished with validation error error="missing primary key on columns: [arn]" client=xxx:ap-south-1 module=aws-src table=aws_elbv2_load_balancer_web_acls

### Expected Behavior

Unsure. 

The table does contain a few rows, but it is not clear whether there should have been more. 

### CloudQuery (redacted) config

```yaml
kind: source
spec:
  name: aws
  path: cloudquery/aws
  version: "v22.0.0"
  tables: ["aws_elb*"]
  skip_tables: ["aws_ecs_cluster_task_sets"]
  destinations: ["postgresql"]
  spec: 
    # AWS Spec section described below
    regions: 
      - ap-south-1
    accounts:
      - id: "main"
        local_profile: "xxxx"
    # aws_debug: false
---
kind: destination
spec:
  name: postgresql
  path: cloudquery/postgresql
  version: "v5.0.1"
  spec:
    connection_string: "postgres://postgres:postgres@localhost:5432/cloudquery?sslmode=disable"
```

### CloudQuery (redacted) logs

```
2023-07-22T04:08:10Z ERR resource resolver finished with validation error error="missing primary key on columns: [arn]" client=xxx:ap-south-1 module=aws-src table=aws_elbv2_load_balancer_web_acls


### CloudQuery version

cloudquery version 3.10.1

### Additional Context

I also tried dropping the table in postgres using `drop table aws_elbv2_load_balancer_web_acls;`. The problem continues to persist. 

### Pull request (optional)

- [ ] I can submit a pull request
