### ISSUE TITLE
feat: feature to add accounts with sync command one by one

### ISSUE THREAD

**Issue by ozbillwang** [cloudquery/cloudquery#12527]
### Which problem is this feature request solving?

[has discussed this issue in discord channel](https://discord.com/channels/872925471417962546/873606591335759872/1131927561983766588), but I think we need an improvement or design review for the issue I got. 

With default source and destination configuration for AWS from official document, I can successfully sync the resources for one account, after I provide the proper AWS API and Secret key. 

Currently I can't sync resources via AWS Organizations,  ( ref: [Multi Account Configuration Tutorial](https://www.cloudquery.io/docs/plugins/sources/aws/multi-account) ) because of the permission I haven't.

So I have to run the sync command for each aws account, after applied the proper AWS Access and secret key. 
```
for profile in account_1 accont_2 account_3
do
  export AWS_PROFILE=$profile
  cloudquery sync ./cloudquery-config
done
```
**these commands run fine, take about 5 mins for each account.** 

**But when go through the data via Grafana, I only see the last account's data**

discord user **jsonk-cq** provided below solution. 

```
kind: source
spec:
  name: "aws"
  path: "cloudquery/aws"
  version: "v21.1.0" 
  destinations: ["postgresql"]
  concurrency: 10000
  tables: 
    - aws_ec2_instances
  spec:
    regions: 
      - us-east-1
    accounts:
      - id: '123412341234'
        local_profile: '1prof'
      - id: '234523452345'
        local_profile: '2prof'
      - id: '345634563456'
        local_profile: '3prof'
```
and suggest another solution with `write_mode` to `append` or `overwrite`.

But my question is, 

1. I prefer `write_mode` to default `overwrite-delete-stale`, it will keep the data clean and reduce the DB sizes. But seems it doesn't work with my way to run for loop on account by account.
2. when sync the accounts, why the `account_id` is ignored with `write_mode` to `overwrite-delete-stale`? Can I still keep different `account_id` with `overwrite-delete-stale`?

### Describe the solution you'd like

But my question is, 

1. I prefer `write_mode` to default `overwrite-delete-stale`, it will keep the data clean and reduce the DB sizes. But seems it doesn't work with my way to run for loop on account by account.
2. when sync the accounts, why the `account_id` is ignored with `write_mode` to `overwrite-delete-stale`? Can I still keep different `account_id` with `overwrite-delete-stale`?

### Pull request (optional)

- [ ] I can submit a pull request
