### ISSUE TITLE
bug: various issues with Postgres source

### ISSUE THREAD

**Issue by nicosuave** [cloudquery/cloudquery#12656]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

A few days back, I was seeing initial connection succeed and rows moved for a number of tables; larger tables in 1 of 2 environments with similar table structure produced the following after ~10 minutes: `Error: failed to sync v3 source ...: unexpected error from sync client receive: rpc error: code = Unknown desc = failed to sync records: failed to sync unmanaged client: ERROR: current transaction is aborted, commands ignored until end of transaction block (SQLSTATE 25P02)`. 

I inspected the logs further and did not find any other error upstream— `statement_timeout` is not set.

Trying again today, both the previously failing environment is failing, as well as the other pre-production environment with a separate seemingly connection-related issue, but I can confirm the source is still connectable `Error: failed to sync v3 source ...: rpc error: code = Internal desc = failed to init plugin: failed to initialize client: could not open database: RPC 'ATTACH_DATABASE' failed: upstream connect error or disconnect/reset before headers. reset reason: protocol error (UNAVAILABLE)`. 

Can confirm is still connectable elsewhere though— not sure what changed as we've applied 0 infra changes since the other day, and versions have not changed.

### Expected Behavior

For the connection / row transfer to succeed

### CloudQuery (redacted) config

```yaml
kind: source
spec:
  name: ...
  registry: "github"
  path: "cloudquery/postgresql"
  version: "v2.0.4"
  destinations: ["motherduck"]
  tables: ["*"]
  spec:
    connection_string: ...
---
kind: destination
spec:
  name: motherduck
  path: cloudquery/duckdb
  version: "v4.2.0"
  write_mode: overwrite
  spec:
    connection_string: ...
```

### CloudQuery (redacted) logs

Relevant bits above

### CloudQuery version

cloudquery version 3.9.0

### Pull request (optional)

- [ ] I can submit a pull request
