### ISSUE TITLE
How can i find the cursor file?

### ISSUE THREAD

**Issue by LyqRikako** [cloudquery/cloudquery#12665]
The local backend stores cursor state as JSON files on the local filesystem. The default location is the .cq/state directory, but this can be configured by using the path option inside the backend_spec section of the [source plugin configuration](https://www.cloudquery.io/docs/reference/source-spec#backend_spec).
But i can't find the state directory and json files.
Then i set the backend_spec path in my resource yaml file,but i still not find json files.
This is my source yaml file:

```
kind: source
spec:
  name: "mysql"
  registry: "local"
  path: "/root/cloudquery_config/plugins/source/mysql"
  version: "v2.0.2"
  concurrency: 10000
  tables: ["stu_001"]
  destinations: ["mysql"]
  backend_spec:
    path: "/root/cloudquery_config/.cq"
  spec:
    connection_string: "root:123456@tcp(192.168.202.242:3307)/database1?parseTime=True"
```
How could i find the cursor file?
