### ISSUE TITLE
feat: use index alias in elasticsearch destination

### ISSUE THREAD

**Issue by avoidik** [cloudquery/cloudquery#12735]
### Which problem is this feature request solving?

it would be great if `cloudquery` would have been using the index alias to write to the elasticsearch index.

### Describe the solution you'd like

a destination spec property to be able to define index alias for use

### Pull request (optional)

- [ ] I can submit a pull request

**Comment by hermanschaaf** [comment]
Hi @avoidik ! This is a great suggestion, and I agree use of index aliases is something missing in the current Elasticsearch destination. 

I was curious, could you describe in more detail how you would want it to work? What would your workflow for creating/managing the indexes involve, and what might the corresponding CloudQuery config look like?

**Comment by avoidik** [comment]
Hi @hermanschaaf ! I assume this feature will be useful in long-term analysis when the `elasticsearch` destination is configured in `append` mode and `source` has many accounts which could generate vast amount of data, so that with every `sync` information will be incrementally committing into the `elasticsearch` index. In this case at some point in time there will be a need to periodically run the roll-over procedure to meet the hot-warm-cold architectural pattern. The roll-over procedure is moving data through phases and is controlled by an ILM life-cycle policy assigned to the index template with an alias. Whenever the roll-over procedure is getting executed the alias will stay as is, but the underlying index will be substituted with another one, typically with the incremental suffix in its name. So, the alias is an abstraction on top of moving parts and that's a reason why it's recommended to write into alias instead of index directly.

There is another thing - mappings. Advanced users would definitely want to control this part themselves. CloudQuery is doing its job by gathering data, and it's been doing this job very well, but sometimes data structures, especially deeply nested arrays of dictionaries, being classified as plain text. This makes data in elasticsearch unindexed, eliminating strong searching capabilities of elasticsearch. From another point of view CloudQuery won't be able to address all possible data structure combinations to properly process and classify them. It would be much easier If you would have delegated this mundane data-classification task to users if they know about their data structure.

If I understand correctly there is a 1:1 mapping between `source.spec.tables` and indices in elasticsearch. Having the following configuration in mind CloudQuery should create an index pattern `aws_ec2_vpcs` and an index `aws_ec2_vpcs` in elasticsearch (without aliases between each other). If the index pattern is already there, no matter if `--no-migrate` is set or not, it will be overwritten, meaning that all the customisations will be lost. I could slightly override this behaviour by defining an index alias under the same `aws_ec2_vpcs` name manually, so that CloudQuery will use an active index instead of the one it created, but it will leave an empty `aws_ec2_vpcs` index.

```
---
kind: source
spec:
  name: "aws"
  path: "cloudquery/aws"
  version: "v22.2.0"
  tables: ["aws_ec2_vpcs"]
  destinations: ["elasticsearch"]
  spec:
    regions:
      - eu-central-1
    default_region: eu-central-1
---
kind: destination
spec:
  name: elasticsearch
  path: cloudquery/elasticsearch
  version: "v3.0.0"
  write_mode: "overwrite-delete-stale"
  spec:
    addresses: ["http://elasticsearch:9200"]
    username: elastic
    password: ${ELASTIC_PASSWORD}
    autopilot: false # true (default) - current behaviour, false - try to use whatever is already in place
```

From the configuration point of view it could have a property such as `autopilot` to determine whether it should create indices and index patterns or not.
