### ISSUE TITLE
bug: elasticsearch destination plugin converts JSONArray into a string

### ISSUE THREAD

**Issue by avoidik** [cloudquery/cloudquery#12761]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

a row is unmarshalled into a literal string first:
https://github.com/cloudquery/cloudquery/blob/f708159c67a0be41d880e15976d84018294a901d/plugins/destination/elasticsearch/client/write.go#L116

then an entire document is marshalled back to json, now MarshalJSON treats our JSONArray as literal string because original type was lost:
https://github.com/cloudquery/cloudquery/blob/f708159c67a0be41d880e15976d84018294a901d/plugins/destination/elasticsearch/client/write.go#L58

as a result elasticsearch documents have some fields stored as text fields with json strings inside

### Expected Behavior

preserve JSONArray data type, allow MarshalJSON to properly unmarshall

### CloudQuery (redacted) config

```yaml
---
kind: source
spec:
  name: "aws"
  path: "cloudquery/aws"
  version: "v22.2.0"
  tables: ["aws_securityhub_findings"]
  destinations: ["elasticsearch"]
  spec:
    regions:
      - eu-central-1
    default_region: eu-central-1
---
kind: destination
spec:
  name: elasticsearch
  path: cloudquery/elasticsearch
  version: "v3.0.0"
  write_mode: "append"
  spec:
    addresses: ["http://elasticsearch:9200"]
    username: elastic
    password: ${ELASTIC_PASSWORD}
```

### Steps To Reproduce

1. run with config
2. check results in kibana

### CloudQuery (redacted) logs

elasticsearch destination plugin has no log output calls in getValueForElasticsearch method

### CloudQuery version

3.11.0

### Pull request (optional)

- [ ] I can submit a pull request
