### ISSUE TITLE
bug: StreamingBatchWriter Hangs on DeleteStale

### ISSUE THREAD

**Issue by bbernays** [cloudquery/cloudquery#12793]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When a destination uses the `StreamingBatchWriter` the the process will just hang when the CLI sends a `DeleteStale` message.

The issue is that the `UnimplementedDeleteStale` doesn't read the messages from the unbuffered channel passed to the plugin.

### Expected Behavior

The destination should return an error saying that the plugin doesn't support `DeleteStale` and then continue on

### CloudQuery (redacted) config

```
kind: source
spec:
  name: xkcd
  path: hermanschaaf/xkcd
  version: v2.0.0
  destinations: ["s3"]
  tables: ["*"]
  spec:
# ---
# kind: destination
# spec:
#   name: "file"
#   path: "cloudquery/file"
#   version: "v3.4.0"
#   spec:
#     path: "path/to/files/{{TABLE}}/{{UUID}}.{{FORMAT}}"
#     format: "csv" # options: parquet, json, csv
---
kind: destination
spec:
  name: "s3"
  # path: "cloudquery/s3"
  # version: "v4.6.0"
  registry: "grpc"
  path: localhost:7777
  spec:
    bucket: "test-bucket"
    region: "region-name" # Example: us-east-1
    path: "path/to/files/{{TABLE}}/{{UUID}}.parquet"
    format: "parquet" # options: parquet, json, csv
    endpoint: http://172.16.5.4:9000
```

### Steps To Reproduce

Run with config

### CloudQuery (redacted) logs

NA

### CloudQuery version

All

### Pull request (optional)

- [ ] I can submit a pull request
