### ISSUE TITLE
bug: snowflake overwrite-delete-stale truncating tables

### ISSUE THREAD

**Issue by icio** [cloudquery/cloudquery#12967]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Destination tables are empty after a sync when using `write_mode: overwrite-delete-stale`.

### Expected Behavior

The tables still have data in them.

### CloudQuery (redacted) config

Here's the one I'm testing with locally (admittedly using a local build with some changes, but this should reproduce even with the latest version of snowflake).

```yaml
kind: source
spec:
  name: digitalocean
  registry: local
  path: /home/icio/go/src/github.com/cloudquery/cloudquery/plugins/source/digitalocean/digitalocean
  version: "v5.2.0"
  tables: ["digitalocean_accounts"]
  destinations: ["snowflake"]
  spec:

---

kind: destination
spec:
  name: "snowflake"
  registry: "local"
  path: /home/icio/go/src/github.com/cloudquery/cloudquery/plugins/destination/snowflake/snowflake
  version: "v5.0.3"
  # write_mode: append

  spec:
    account: acc
    user: paul
    role: accountadmin
    private_key: "${file:./snowflake.key}"

    warehouse: test
    database: paultest
    schema: public
```

### Steps To Reproduce

Run the above sync then check if there's any rows in `digitalocean_accounts`. I found none, despite confirmation from cloudquery that it wrote something.

### CloudQuery (redacted) logs

```
2023-08-09T16:22:31Z INF batch written successfully duration=922.555289 len=1 module=snowflake-src table=digitalocean_accounts
```

### CloudQuery version

f8dfac3404c3e3c92e0fbbe021acfdfec7f85757

### Additional Context

It looks like the `_cq_sync_time` is persisted at a lower resolution than the timestamp we run the stale-cleanup with:

```
$ snowsql -a acc -u paul --private-key-path ./snowflake.key -w test -d paultest
* SnowSQL * v1.2.28
Type SQL statements or !help
paul#TEST@PAULTEST.(no schema)>alter session set TIMESTAMP_OUTPUT_FORMAT='YYYY-MM-DD HH24:MI:SS.FF9 TZHTZM';
+----------------------------------+                                            
| status                           |
|----------------------------------|
| Statement executed successfully. |
+----------------------------------+
1 Row(s) produced. Time Elapsed: 0.053s
paul#TEST@PAULTEST.(no schema)>SELECT _cq_sync_time FROM DIGITALOCEAN_ACCOUNTS;
+-------------------------+                                                     
| _CQ_SYNC_TIME           |
|-------------------------|
| 2023-08-09 16:24:40.229 |
+-------------------------+
```

The deletion looks like this:

```sql
delete from digitalocean_accounts where "_CQ_SOURCE_NAME" = ? and "_CQ_SYNC_TIME"::timestamp_tz < ?::timestamp_tz
-- ? == 2023-08-09T16:24:40.229491915Z
```

* The `?` is provided with nanosecond precision whereas the `_cq_sync_time` column appears to have been persisted with millisecond.
* The `_cq_sync_time` column is timestamp_ntz but we're comparing to a timestamp_tz, which might hint at some timestamp translation error, but the `?` parameter is already in UTC. Probably not an issue.

### Pull request (optional)

- [ ] I can submit a pull request
