### ISSUE TITLE
bug: Snowflake destination migration fails if multiple schema contain the table

### ISSUE THREAD

**Issue by remisalmon** [cloudquery/cloudquery#13266]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When a Snowflake destination database contains multiple schemas with the same table synced with cloudquery, the migration fails with `rpc error: code = Canceled desc = plugin returned error: table <table> has multiple columns for id. migrate manually or consider using 'migrate_mode: forced'`.

### Expected Behavior

Migration should work regardless of other tables in other schemas in the Snowflake destination.

### CloudQuery (redacted) config

```yaml
kind: destination
spec:
  name: "snowflake"
  registry: "github"
  path: "cloudquery/snowflake"
  version: "v3.2.0"
  write_mode: "overwrite-delete-stale"
  spec:
    connection_string: "<connection string>"
```

### Steps To Reproduce

1. Setup a Snowflake database with two schemas A and B
2. Sync a table to Snowflake in schema A
3. Clone that table in Snowflake in schema B
4. Run a cloudquery sync or migration (fails)

### CloudQuery (redacted) logs

```
Loading spec(s) from postgresql.yml, snowflake.yml
Starting sync for: postgresql (v3.0.0) -> [snowflake (v3.2.0)]
/ Syncing resources... (9/-, 3 resources/s) [3s] Error: failed to sync v3 source postgresql: rpc error: code = Canceled desc = plugin returned error: table <table> has multiple columns for id. migrate manually or consider using 'migrate_mode: forced'
- Syncing resources... (9/-, 3 resources/s) [3s] ⏎ 
```

### CloudQuery version

cloudquery version 3.14.1

### Pull request (optional)

- [X] I can submit a pull request
