### ISSUE TITLE
bug: AWS plugin syncing only last account (v22.7.0+)

### ISSUE THREAD

**Issue by hermanschaaf** [cloudquery/cloudquery#13389]
Reported by `G4m3` on Discord:

> hi team, I have an issue with the latest version of the aws source plugin. The aws_account_contacts table gets the full_name (and potentially other fields) not reflecting the value of each account_id (ie. I have 10 accounts_id and the full_name is always the one from the first account). Is this  a regression ? Thank you!

Config:

```yaml
kind: source
spec:
  name: aws_dev
  path: cloudquery/aws
  version: "v22.7.0"
  tables: ["*"]
  skip_tables:
    - aws_ec2_vpc_endpoint_services
    - aws_cloudtrail_events
    - aws_docdb_cluster_parameter_groups
    - aws_docdb_engine_versions
    - aws_ec2_instance_types
    - aws_elasticache_engine_versions
    - aws_elasticache_parameter_groups
    - aws_elasticache_reserved_cache_nodes_offerings
    - aws_elasticache_service_updates
    - aws_iam_group_last_accessed_details
    - aws_iam_policy_last_accessed_details
    - aws_iam_role_last_accessed_details
    - aws_iam_user_last_accessed_details
    - aws_neptune_cluster_parameter_groups
    - aws_neptune_db_parameter_groups
    - aws_rds_cluster_parameter_groups
    - aws_rds_db_parameter_groups
    - aws_rds_engine_versions
    - aws_servicequotas_services
    - aws_ecr_repository_image_scan_findings
    - aws_athena_work_group_query_executions
  destinations: ["postgresql"]

  spec:
    accounts:
      - id: "dev"
        role_arn: "arn:aws:iam::xxxxxxxxxxx:role/xxxxxxxxxxxxx"
      - id: "dev2"
        role_arn: "arn:aws:iam::xxxxxxxxxxx:role/xxxxxxxxxxxxx"

kind: destination
spec:
  name: postgresql
  path: cloudquery/postgresql
  version: "v6.0.1"
  migrate_mode: forced

  write_mode: "overwrite-delete-stale"

  spec:
    connection_string: "postgresql://cloudquery:xxxxxxxxxx@localhost:5432/cloudquery?sslmode=disable"

```

CLI v3.14.5

User confirmed that this behavior is not happening in AWS v22.6.0, so this seems like a regression.
