### ISSUE TITLE
bug: Lack of clear error when no tables selected in config

### ISSUE THREAD

**Issue by hermanschaaf** [cloudquery/cloudquery#13400]
I inadvertently created a config where a single table was both selected and skipped. I would have expected a clear error indicating that no tables were selected, but instead got only this error in the logs:

```
2023-08-29T14:34:31Z ERR started call grpc.code=Unknown grpc.component=server grpc.error=EOF grpc.method=Write grpc.method_type=client_stream grpc.service=cloudquery.plugin.v3.Plugin grpc.start_time=2023-08-29T15:34:31+01:00 grpc.time_ms=3.565 module=cli peer.address= protocol=grpc
```

and no other errors or warnings.

Config:

```
kind: source
spec:
  name: aws
  path: cloudquery/aws
  version: "v22.8.1"
  tables:
   - aws_cloudtrail_events
  backend_options:
    table_name: "aws_backend_options"
    connection: "@@plugins.postgresql.connection"
  skip_tables:
    - aws_cloudtrail_events
  destinations: ["postgresql"]
  spec:
---
kind: destination
spec:
  name: postgresql
  path: cloudquery/postgresql
  version: "v6.0.1"
  migrate_mode: forced

  write_mode: "overwrite-delete-stale"

  spec:
    connection_string: "postgresql://<connection string>"
```
