### ISSUE TITLE
bug: Sync doesn't work as expected when you have multiple accounts

### ISSUE THREAD

**Issue by Ramesh7** [cloudquery/cloudquery#13434]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hi Team,

Have observed wired behaviour with CloudQuery where the sync doesn't work as expected, once sync completed I see that portion of resources only gets sync. Basically I have around 5+ accounts configured.

When I run sync which takes around 12+ minutes and it completes with no errors : 
```
% cloudquery sync configs/cloudquery
Loading spec(s) from configs/cloudquery
Starting sync for: aws (v22.7.0) -> [postgresql (v5.0.5)]
Sync completed successfully. Resources: 55496, Errors: 0, Warnings: 348, Time: 12m48s
% echo $?
0
```
When I check the PostgreSQL I see only portion of resource data. : 
```
cloudquery=# select account_id, count(*) from aws_ec2_ebs_volumes group by account_id;
  account_id  | count
--------------+-------
 961701xxxxxxx |   264
 217932xxxxxxx |   264
 62425xxxxxxxx |   264
 60324xxxxxxxx |   264
(4 rows)

cloudquery=# select account_id, count(*) from aws_ec2_instances group by account_id;
  account_id  | count
--------------+-------
 961701xxxxxxx |   203
 217932xxxxxxx |   203
 62425xxxxxxxx |   203
 60324xxxxxxxx |   203
(4 rows)
```
I can see only 4 accounts out of 6 are showing result but interestingly all showing same result count where as I have couple of accounts EBS & EC2 resource count >2K.
Not sure what I am missing here, Looking for inputs.

### Expected Behavior

All the resources should get synced when user runs the sync, and user should get actual resource count in postgres.

### CloudQuery (redacted) config

```
kind: source
spec:
  name: "aws"
  path: "cloudquery/aws"
  version: "v22.7.0"
  tables:
    # TrustAdvisor
    - aws_support_trusted_advisor_checks
    - aws_support_trusted_advisor_check_results
    - aws_support_trusted_advisor_check_summaries
    # Object Storage
    - aws_s3_buckets
    - aws_s3_bucket_cors_rules
    - aws_s3_bucket_encryption_rules
    - aws_s3_bucket_grants
    - aws_s3_bucket_lifecycles
    - aws_s3_bucket_websites
    # Storage Filesystem
    - aws_efs_access_points
    - aws_efs_filesystems
    # Compute Service
    - aws_ec2_ebs_snapshots
    - aws_ec2_ebs_volumes
    - aws_ec2_instances
    - aws_ec2_instance_types
    - aws_ec2_ebs_snapshot_attributes
    # Databases
    - aws_rds_instances
    - aws_rds_clusters
    - aws_rds_certificates
    - aws_timestream_databases
    # ElastiSearch
    - aws_elasticache_clusters
    - aws_elasticache_engine_versions
    # CloudFront
    - aws_cloudfront_cache_policies
    - aws_cloudfront_distributions
    - aws_cloudfront_functions
    - aws_cloudfront_origin_access_identities
    - aws_cloudfront_origin_request_policies
    - aws_cloudfront_response_headers_policies
    # CloudHSM
    - aws_cloudhsmv2_backups
    - aws_cloudhsmv2_clusters
    - aws_mq_brokers
    # Cloud Trail
    - aws_cloudtrail_channels
    - aws_cloudtrail_trails
    # CloudWatch
    - aws_cloudwatch_alarms
    - aws_cloudwatchlogs_log_groups
    - aws_cloudwatchlogs_metric_filters
    - aws_cloudwatchlogs_resource_policies
  destinations: ["postgresql"]
  spec:
    aws_debug: false
    regions:
      - '*'
    initialization_concurrency: 2
    concurrency: 1000
    accounts:
      - local_profile: "account-1"
        id: account-1
      - local_profile: "account-2"
        id: account-2
      - local_profile: "account-3"
        id: account-3
      - local_profile: "account-4"
        id: account-4
      - local_profile: "account-5"
        id: account-5
      - local_profile: "account-6"
        id: account-6
```

### Steps To Reproduce

Run the sync command with above cloudquery config.

### CloudQuery (redacted) logs

As the resource sync succeed so skipping logs.

### CloudQuery version

cloudquery version 3.14.1

### Pull request (optional)

- [ ] I can submit a pull request
