### ISSUE TITLE
bug: MSSQL destination truncates all records when using overwrite-delete-stale

### ISSUE THREAD

**Issue by hermanschaaf** [cloudquery/cloudquery#13457]
[Reported on Discord](https://discord.com/channels/872925471417962546/873606591335759872/1146163749800128602)

```yaml
##########AWS Pricing############

kind: source
spec:
  name: "awspricing"
  path: "cloudquery/awspricing"
  version: "v3.0.5"
  tables: ["*"]
  destinations:
    - scmdb_dev
    #- file_csv # For Debugging
  spec:
    # Optional parameters
    region_codes:
      - "us-east-1"
      #- "us-east-2"
      #- "us-west-1"
      #- "us-west-2"
    # offer_codes: []
    # concurrency: 10000
    
###########MSSQL#################

  name: "scmdb_dev"
  registry: "github"
  path: "cloudquery/mssql"
  version: "v4.3.7"
  spec:
    connection_string: "server=<SERVERNAME>;user id=<USERNAME>;password=<PASSWORD>;port=1433;database=cloudquery_dev;"
    # Optional parameters:
    auth_mode: ms
    schema: dbo
    batch_size: 1000 # 1K entries
    batch_size_bytes: 5242880 # 5 MiB
    batch_timeout: 20s

#################################
```

```sh
#Example of what I am running;
./cloudquery sync --log-level info --cq-dir ./ ./sources/aws_pricing.yml ./destinations/scmdb_dev.yml
```

```sh
[cloudquery]$ ./cloudquery --version
cloudquery version 3.14.2
```
