### ISSUE TITLE
bug: Slow load times to Neo4j destination due to lack of indexing

### ISSUE THREAD

**Issue by smokentar** [cloudquery/cloudquery#13754]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Example: `aws_cloudtrail_events`
Big table with lots of data.

Loading to Neo4j starts off really quick (couple of seconds to load thousands of events) then speed exponentially decreases.
The more events have been loaded, the more time it takes to load.

This happens because CQ uses `MERGE` which creates a node if it doesn't already exist in the DB based on primary keys defined.
In [write.go](https://github.com/cloudquery/cloudquery/blob/main/plugins/destination/neo4j/client/write.go) there isn't a functionality for creating an index on the primary keys defined.
Without indexes, Neo4j does a full scan of all nodes to determine whether the entity in question exists.
This causes the exponential decrease in performance.
This would impact any table from any source that contains a lot of data.

### Expected Behavior

Before starting the load, CQ would create indexes on the primary keys of the node.
This could be done in write.go or a separate file.
Example: 
```
CREATE INDEX IF NOT EXISTS FOR (n:aws_cloudtrail_events) ON (n.event_id);
```

### CloudQuery (redacted) config

```
kind: source
spec:
  name: "aws"
  registry: "github"
  path: "cloudquery/aws"
  version: "v22.1.0"
  tables: ["*"]
  skip_tables:
    - aws_ec2_vpc_endpoint_services
    - aws_docdb_cluster_parameter_groups
    - aws_docdb_engine_versions
    - aws_ec2_instance_types
    - aws_elasticache_engine_versions
    - aws_elasticache_parameter_groups
    - aws_elasticache_reserved_cache_nodes_offerings
    - aws_elasticache_service_updates
    - aws_elasticsearch_versions
    - aws_neptune_cluster_parameter_groups
    - aws_neptune_db_parameter_groups
    - aws_rds_cluster_parameters
    - aws_rds_cluster_parameter_groups
    - aws_rds_cluster_parameter_group_parameters
    - aws_rds_db_parameter_groups
    - aws_rds_engine_versions
    - aws_servicequotas_services
    - aws_servicequotas_quotas
    - aws_iam_role_last_accessed_details
    - aws_iam_user_last_accessed_details
    - aws_iam_policy_last_accessed_details
    - aws_directconnect_locations
    - aws_ram_resource_types
    - aws_lambda_runtimes
    - aws_docdb_event_categories
  destinations: ["neo4j"]
  spec:
    accounts:
      - id: "${ACCOUNT_ID}"
        role_arn: "${ROLE_ARN}"
        role_session_name: "Discovery"
    aws_debug: false

kind: destination
spec:
  name: "neo4j"
  registry: "github"
  path: "cloudquery/neo4j"
  version: "v4.0.1"
  # batch_size: 10000 # optional
  # batch_size_bytes: 5242880 # optional
  spec:
    connection_string: "${DB_ENDPOINT}"
    username: "${DB_USERNAME}"
    password: "${DB_PASSWORD}"
```

### CloudQuery (redacted) logs

```
N/A
```

### CloudQuery version

v3.8.0

### Additional Context

[Neo4j Indexing](https://neo4j.com/docs/cypher-manual/current/query-tuning/indexes/)

### Pull request (optional)

- [ ] I can submit a pull request
