### ISSUE TITLE
Stale data present in cloudquery for suspended AWS accounts

### ISSUE THREAD

**Issue by rajeshwarakella1994** [cloudquery/cloudquery#13869]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Cloudquery suggests to use dedicated namespaces for running cloudquery on multiple accounts. Below is the suggested configuration from cloudquery - 
```
spec:
                name: "aws_${ACCOUNT_ID}"
                path: "cloudquery/aws"
                version: "${AWS_V}"
                tables: ["*"]
                spec:
                    accounts:
                        - id: "${ACCOUNT_ID}"
                          role_arn: "arn:aws:iam::${ACCOUNT_ID}:role/sample-role"
```

The problem with above configuration is that cloudquery when run for a suspended account fails with the below error as suspended account won't allow assume role configuration 
```
{
    "level": "error",
    "module": "cli",
    "error": "failed to sync v3 source aws_<suspended_account>: rpc error: code = Internal desc = failed to init plugin: failed to initialize client: no AWS accounts were successfully configured. See warning messages in the logs for details",
    "time": "2023-09-15T09:14:54Z",
    "message": "exiting with error"
}
```

### Expected Behavior

Stale data of the suspended account should be deleted from the DB if data of that account is present inside the Cloudquery DB.

### CloudQuery (redacted) config

```
spec:
                name: "aws_${ACCOUNT_ID}"
                path: "cloudquery/aws"
                version: "${AWS_V}"
                tables: ["*"]
                spec:
                    accounts:
                        - id: "${ACCOUNT_ID}"
                          role_arn: "arn:aws:iam::${ACCOUNT_ID}:role/sample-role"
```

### Steps To Reproduce

Run cloudquery sync for a suspended account

### CloudQuery (redacted) logs

```
{
    "level": "error",
    "module": "cli",
    "error": "failed to sync v3 source aws_<suspended_account>: rpc error: code = Internal desc = failed to init plugin: failed to initialize client: no AWS accounts were successfully configured. See warning messages in the logs for details",
    "time": "2023-09-15T09:14:54Z",
    "message": "exiting with error"
}
```

### CloudQuery version

v3.12.4

### Pull request (optional)

- [ ] I can submit a pull request
