### ISSUE TITLE
bug: SQLite plugin cannot be use with the docker image

### ISSUE THREAD

**Issue by moadibfr** [cloudquery/cloudquery#14465]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hello there,
I was trying to use the docker image to run a sync with a SQLite destination and after sucessfully donwloading the plugin I got the error that the plugin was not found:
```
docker run -v $PWD:$PWD --workdir $PWD ghcr.io/cloudquery/cloudquery:latest sync aws.yml sqlite.yml
Loading spec(s) from aws.yml, sqlite.yml
Downloading https://github.com/cloudquery/cloudquery/releases/download/plugins-source-aws-v22.13.2/aws_linux_amd64.zip
Downloading 100% |████████████████████████████████| (59/59 MB, 33 MB/s)        
Downloading https://github.com/cloudquery/cloudquery/releases/download/plugins-destination-sqlite-v2.4.10/sqlite_linux_amd64.zip
Downloading 100% |██████████████████████████████| (8.0/8.0 MB, 24 MB/s)        
Error: failed to start plugin .cq/plugins/destination/cloudquery/sqlite/v2.4.10/plugin: fork/exec .cq/plugins/destination/cloudquery/sqlite/v2.4.10/plugin: no such file or directory
```

### Expected Behavior

I expect the sync to work as intended.

### CloudQuery (redacted) config

```
❯ cat aws.yml
spec:
  path: cloudquery/aws
  tables:
  - aws_cloudtrail_events
  destinations:
  - sqlite
  name: aws
  version: v22.13.2
  spec:
    custom_endpoint_url: http://127.0.0.1:32835
    custom_endpoint_hostname_immutable: "true"
    max_retries: 0
    custom_endpoint_partition_id: aws
    custom_endpoint_signing_region: us-east-1
kind: source
❯ cat sqlite.yml
spec:
  version: v2.3.0
  name: sqlite
  spec:
    connection_string: ./db.sqlite
  path: cloudquery/sqlite
kind: destination

```

### Steps To Reproduce

`docker run -v $PWD:$PWD --workdir $PWD ghcr.io/cloudquery/cloudquery:latest sync aws.yml sqlite.yml`
with the provided config files

### CloudQuery (redacted) logs

```
2023-10-09T08:00:41Z INF Loading spec(s) args=["aws.yml","sqlite.yml"] module=cli
2023-10-09T08:00:46Z INF Plugin server listening address=/tmp/cq-bFfArHahRlQygbqv.sock module=cli
2023-10-09T08:00:49Z INF waiting for source plugin to terminate module=cli
2023-10-09T08:00:49Z INF Got stop signal. Plugin server shutting down address=/tmp/cq-bFfArHahRlQygbqv.sock module=cli signal=interrupt
2023-10-09T08:00:49Z ERR exiting with error error="failed to start plugin .cq/plugins/destination/cloudquery/sqlite/v2.3.0/plugin: fork/exec .cq/plugins/destination/cloudquery/sqlite/v2.3.0/plugin: no such file or directory" module=cli
```

### CloudQuery version

cloudquery version 3.21.3

### Pull request (optional)

- [ ] I can submit a pull request

**Comment by moadibfr** [comment]
Hey @maaarcelino thanks for your answer

> * In your sqlite config you use v2.3.0 of the plugin, yet in the logs you shared I can see that v2.4.10 is being downloaded. Can you double check that your config against the screenshots here?
Sorry I did try with multiple config to make something small to share. The log is exactly the same with 2.3.0
```
❯ docker run -v $PWD:$PWD --workdir $PWD ghcr.io/cloudquery/cloudquery:latest sync aws.yml sqlite.yml
Loading spec(s) from aws.yml, sqlite.yml
Downloading https://github.com/cloudquery/cloudquery/releases/download/plugins-source-aws-v22.13.2/aws_linux_amd64.zip
Downloading 100% |████████████████████████████████| (59/59 MB, 34 MB/s)        
Downloading https://github.com/cloudquery/cloudquery/releases/download/plugins-destination-sqlite-v2.3.0/sqlite_linux_amd64.zip
Downloading 100% |██████████████████████████████| (6.9/6.9 MB, 24 MB/s)        
Error: failed to start plugin .cq/plugins/destination/cloudquery/sqlite/v2.3.0/plugin: fork/exec .cq/plugins/destination/cloudquery/sqlite/v2.3.0/plugin: no such file or directory
```

> * It also looks like the plugin cannot be found after it was downloaded. Can you try re-running that sync but without Docker dismounting?
> * Also could you check that the file `.cq/plugins/destination/cloudquery/sqlite/v2.4.10/plugin ` is accessible from within the container?
Re running does the same and the file seems to exists.
```
❯ docker run -v $PWD:$PWD --workdir $PWD --entrypoint "" -it ghcr.io/cloudquery/cloudquery:latest /bin/sh
/home/moadib/kestra/tests # /app/cloudquery sync aws.yml sqlite.yml
Loading spec(s) from aws.yml, sqlite.yml
Downloading https://github.com/cloudquery/cloudquery/releases/download/plugins-source-aws-v22.13.2/aws_linux_amd64.zip
Downloading 100% |██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| (59/59 MB, 22 MB/s)        
Downloading https://github.com/cloudquery/cloudquery/releases/download/plugins-destination-sqlite-v2.3.0/sqlite_linux_amd64.zip
Downloading 100% |████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| (6.9/6.9 MB, 27 MB/s)        
Error: failed to start plugin .cq/plugins/destination/cloudquery/sqlite/v2.3.0/plugin: fork/exec .cq/plugins/destination/cloudquery/sqlite/v2.3.0/plugin: no such file or directory
/home/moadib/kestra/tests # /app/cloudquery sync aws.yml sqlite.yml
Loading spec(s) from aws.yml, sqlite.yml
Error: failed to start plugin .cq/plugins/destination/cloudquery/sqlite/v2.3.0/plugin: fork/exec .cq/plugins/destination/cloudquery/sqlite/v2.3.0/plugin: no such file or directory
/home/moadib/kestra/tests # ls -al .cq/plugins/destination/cloudquery/sqlite/v2.3.0/plugin
-rwxr--r--    1 root     root      18958688 Oct  9 13:12 .cq/plugins/destination/cloudquery/sqlite/v2.3.0/plugin
```

**Comment by maaarcelino** [comment]
@moadibfr I have been able to replicate the issue on my side and am working on a fix. I'll provide updates here.

**Comment by moadibfr** [comment]
Hi @maaarcelino. I just wanted to let you know that we have the exact same issue with the duckdb plugin.
```
 cat test.yaml
kind: source
spec:
  name: hackernews
  path: cloudquery/hackernews
  version: v3.0.13
  tables: ["*"]
  destinations: ["duckdb"]
  spec:
    item_concurrency: 100
    start_time: "{{ now() | dateAdd(-1, 'DAYS') }}"
  # 90k rows for just 1 week of data
---
kind: destination
spec:
  name: duckdb
  path: cloudquery/duckdb
  version: "v4.2.10"
  write_mode: "overwrite-delete-stale"
  spec:
    connection_string: hn.db 
```
result in 
```
Error: failed to start plugin .cq/plugins/destination/cloudquery/duckdb/v4.2.10/plugin: fork/exec .cq/plugins/destination/cloudquery/duckdb/v4.2.10/plugin: no such file or directory
```

**Comment by maaarcelino** [comment]
@moadibfr Yes, both the SQLite and DuckDB plugins are CGO_ENABLED and as a result failed to run under Alpine Linux distributions. I have been able to fix this by changing how they are compiled (see https://github.com/cloudquery/plugin-sdk/pull/1292).

A fix will be coming out to solve this. Once I've confirmed it works I'll add a closing comment to this issue.

**Comment by maaarcelino** [comment]
We've published a new version of the SQLite plugin (v2.4.13) which fixes this issue. I was able to run a sync under the public Docker image with this command:

`docker run -v $PWD:$PWD --workdir $PWD ghcr.io/cloudquery/cloudquery:latest sync aws.yml sqlite.yml`

Please ensure your sqlite config specifies version 2.4.13 (or newer in the future).

I have opened a separate issue for the DuckDB plugin (https://github.com/cloudquery/cloudquery/issues/14701) as this fix doesn't cover that plugin.

**Comment by moadibfr** [comment]
hi @maaarcelino, I know this bug is closed but I came back to try with the new version of sqlite and I don't get anything different than. before. Event with the 2.4.15 version:
```
❯ docker run -v $PWD:$PWD --workdir $PWD ghcr.io/cloudquery/cloudquery:latest sync aws.yml sqlite.yml
Loading spec(s) from aws.yml, sqlite.yml
Downloading https://github.com/cloudquery/cloudquery/releases/download/plugins-destination-sqlite-v2.4.13/sqlite_linux_amd64.zip
Downloading 100% |████████████████████████████████| (10/10 MB, 22 MB/s)        
Error: failed to start plugin .cq/plugins/destination/cloudquery/sqlite/v2.4.13/plugin: fork/exec .cq/plugins/destination/cloudquery/sqlite/v2.4.13/plugin: no such file or directory
❯ vi sqlite.yml
❯ docker run -v $PWD:$PWD --workdir $PWD ghcr.io/cloudquery/cloudquery:latest sync aws.yml sqlite.yml
Loading spec(s) from aws.yml, sqlite.yml
Downloading https://github.com/cloudquery/cloudquery/releases/download/plugins-destination-sqlite-v2.4.15/sqlite_linux_amd64.zip
Downloading 100% |████████████████████████████████| (10/10 MB, 23 MB/s)        
Error: failed to start plugin .cq/plugins/destination/cloudquery/sqlite/v2.4.15/plugin: fork/exec .cq/plugins/destination/cloudquery/sqlite/v2.4.15/plugin: no such file or directory

```

**Comment by maaarcelino** [comment]
Can you please remove the Docker images you have stored locally and then try again?

I just ran a test on a clean EC2 instance and it worked as expected. It's possible you have a bad image cached locally. I was using this config:

```
kind: source
spec:
  name: aws
  registry: "cloudquery"
  path: cloudquery/aws
  version: "v22.18.0"
  tables: ["aws_ec2_instances"]
  destinations: ["sqlite"]
---
kind: destination
spec:
  name: sqlite
  path: cloudquery/sqlite
  registry: cloudquery
  version: "v2.4.15"
  spec:
    connection_string: ./db.sql
```
