### ISSUE TITLE
bug: DuckDB plugin doesn't support arm64 architecture

### ISSUE THREAD

**Issue by anna-geller** [cloudquery/cloudquery#14557]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The DuckDB plugin cannot be downloaded for arm64 arch, I tried both v5.0.0 and the previous one v4.2.10

https://github.com/cloudquery/cloudquery/releases?q=duckdb&expanded=true

![image](https://github.com/cloudquery/cloudquery/assets/86264395/81ff056b-d00d-4b1e-888e-5cd7113b6327)

![image](https://github.com/cloudquery/cloudquery/assets/86264395/311397b0-db27-4208-9b44-90fdf21e5bd9)

not sure if this is related to running the CloudQuery sync within the (brand new https://github.com/cloudquery/cloudquery/issues/14506) arm-based image, but I was able to verify that for linux-amd64 DuckDB plugin works while arm64 doesn't 

![image](https://github.com/cloudquery/cloudquery/assets/86264395/1a154457-06ce-43d9-a02d-131018fedf08)

### Expected Behavior

These URLs should work :)
https://github.com/cloudquery/cloudquery/releases/download/plugins-destination-duckdb-v4.2.10/duckdb_darwin_arm64.zip
https://github.com/cloudquery/cloudquery/releases/download/plugins-destination-duckdb-v5.0.0/duckdb_darwin_arm64.zip

### CloudQuery (redacted) config

```yaml
kind: source
spec:
  name: hackernews
  path: cloudquery/hackernews
  version: v3.0.13
  tables: ["*"]
  destinations: ["duckdb"]
  spec:
    item_concurrency: 100
    start_time: 2023-10-16T00:00:00Z
---
kind: destination
spec:
  name: duckdb
  path: cloudquery/duckdb
  version: v5.0.0
  write_mode: overwrite-delete-stale
  spec:
    connection_string: hn.db
```

### CloudQuery (redacted) logs

that flow works when running locally but not in a Docker image (see screenshots)

### CloudQuery version

3.23.1

### Pull request (optional)

- [ ] I can submit a pull request
