### ISSUE TITLE
bug: DuckDB plugin doesn't run under Alpine Linux Docker image

### ISSUE THREAD

**Issue by maaarcelino** [cloudquery/cloudquery#14701]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Attempting to run a sync with DuckDB as a destination under Alpine Linux fails with version 5.0.3 of the DuckDB plugin.

### Expected Behavior

`docker run -v $PWD:$PWD --workdir $PWD ghcr.io/cloudquery/cloudquery:latest sync config.yml` should result in a successful sync

### CloudQuery (redacted) config

```yaml
kind: source
spec:
  name: hackernews
  path: cloudquery/hackernews
  version: v3.0.13
  tables: ["*"]
  destinations: ["duckdb"]
---
kind: destination
spec:
  name: duckdb
  path: cloudquery/duckdb
  version: "v5.0.3"
  write_mode: "overwrite-delete-stale"
  spec:
    connection_string: hn.db
```

### Steps To Reproduce

1. Use config above and run `docker run -v $PWD:$PWD --workdir $PWD ghcr.io/cloudquery/cloudquery:latest sync config.yml`

### CloudQuery (redacted) logs

```
Loading spec(s) from config-duckdb.yml
Error: failed to start plugin .cq/plugins/destination/cloudquery/duckdb/v5.0.3/plugin: fork/exec .cq/plugins/destination/cloudquery/duckdb/v5.0.3/plugin: no such file or directory
```

### CloudQuery version

3.25.0

### Additional Context

https://github.com/cloudquery/cloudquery/issues/14465

### Pull request (optional)

- [ ] I can submit a pull request
