### ISSUE TITLE
bug: `failed to sync records: failed to sync unmanaged client: parsing time "111111-11-11 11:11:00" as "2006-01-02 15:04:05.999999999": cannot parse "11-11-11 11:11:00" as "-"`

### ISSUE THREAD

**Issue by nicosuave** [cloudquery/cloudquery#14796]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Postgres -> DuckDB sync is failing. I don't believe Postgres can store such a value as `111111-11-11 11:11:00` in a timestamp field so am a little unclear of what's happening.

### Expected Behavior

No failure

### CloudQuery (redacted) config

```yaml
kind: source
spec:
  name: ...
  registry: "github"
  path: "cloudquery/postgresql"
  version: "v3.0.6"
  destinations: ["motherduck"]
  tables: ['*']
  spec:
    rows_per_record: 10000
    pgx_log_level: debug
    connection_string: ...
  backend_options:
    table_name: "cq_..._state"
    connection: "@@plugins.motherduck.connection"
---
kind: destination
spec:
  name: motherduck
  path: cloudquery/duckdb
  version: "v5.0.3"
  write_mode: overwrite
  migrate_mode: forced
  spec:
    connection_string: ...
    batch_size: 10000
    debug: true
```

### CloudQuery (redacted) logs

In title. `debug` option also not seeming to do anything as far as surfacing more detailed logs around the failure

### CloudQuery version

cloudquery version 3.9.0

### Pull request (optional)

- [ ] I can submit a pull request
