### ISSUE TITLE
bug: Athena schema issues

### ISSUE THREAD

**Issue by patelkajal18** [cloudquery/cloudquery#14877]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am uploading CQ data to S3 and getting this error when try to run queries in Athena: “HIVE_INVALID_METADATA: Glue table aws_ec2_instances column tags has invalid data type struct<>”. The potential issue could be that the tag data is a struct made up of key & value pairs with special characters (\ : / , . ) and Athena [doesn't support](https://docs.aws.amazon.com/athena/latest/ug/tables-databases-columns-names.html) special characters other than (_) for column names. 

Examples of tags:
- "test.io/test-test/test-template/label/id": "13423"
- "test.sh/test-name": "test"
- "aws:ec2launchtemplate:id": "lt-dsew0132s3d"

### Expected Behavior

I expected the tags field to be converted into a queryable tags column. 

### CloudQuery (redacted) config

```
kind: destination
spec:
  name: "s3"
  path: "cloudquery/s3"
  version: "v4.7.1"
  spec:
    bucket: "<bucket name>"
    region: "<region name>"
    path: "path/table/ds=yr-month-date/uuid.json"
    format: "json"
    athena: true
```

### CloudQuery (redacted) logs

No logs

### CloudQuery version

v3.25.1

### Pull request (optional)

- [ ] I can submit a pull request
