### ISSUE TITLE
bug: sharepoint->snowflake silent failure

### ISSUE THREAD

**Issue by yevgenypats** [cloudquery/cloudquery#15041]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Seems sharepoint plugin is working with other destinations but failure silently with snowflake

### Expected Behavior

--

### CloudQuery (redacted) config

```
spec:
  name: "sharepoint"
  registry: "github"
  path: "koltyakov/sharepoint"
  version: "v1.8.2" # provide the latest stable version

---
kind: destination
spec:
  name: "snowflake"
  path: "cloudquery/snowflake"
  registry: "cloudquery"
  version: "v3.2.11"
```

### Steps To Reproduce

-

### CloudQuery (redacted) logs

-

### CloudQuery version

-

### Additional Context

-

### Pull request (optional)

- [ ] I can submit a pull request
