### ISSUE TITLE
bug: type mismatch: got=utf8, want=date32

### ISSUE THREAD

**Issue by thijsbrouwers** [cloudquery/cloudquery#15059]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Columns of type `date32` are created as `utf8` in postgres destination.

### Expected Behavior

Columns of type `date32` are created as `date32` in postgres destination.

### CloudQuery (redacted) config

```yaml
kind: source
spec:
  name: 'source-db'
  registry: 'cloudquery'
  path: 'cloudquery/postgresql'
  version: 'v3.0.7'
  destinations: ['destination-db']
  tables: ['*']
  spec:
    connection_string: ...
---
kind: destination
spec:
  name: 'destination-db'
  path: 'cloudquery/postgresql'
  version: 'v6.1.3'
  write_mode: 'overwrite-delete-stale'
  spec:
    connection_string: ...
```

### Steps To Reproduce

1. Create a table with a `date` datatype and populate it with a records
2. Sync

### CloudQuery (redacted) logs

```
Starting sync for: source-db (postgresql@v3.0.7) -> [destination-db (cloudquery@cloudquery/postgresql)]
| Syncing resources... (948/-, 2369 resources/s) [0s] panic: interface conversion: interface {} is nil, not pgtype.Time

goroutine 40 [running]:
github.com/cloudquery/cloudquery/plugins/source/postgresql/client.transformerForDataType.func3({0x0?, 0x0?})
	/home/runner/work/cloudquery/cloudquery/plugins/source/postgresql/client/transform.go:42 +0x78
github.com/cloudquery/cloudquery/plugins/source/postgresql/client.(*Client).syncTable(0x14000534960, {0x105dc9428, 0x14000780600}, {0x105dd4d08, 0x14000630300}, 0x14000a2c000, 0x9?)
	/home/runner/work/cloudquery/cloudquery/plugins/source/postgresql/client/sync.go:133 +0x510
github.com/cloudquery/cloudquery/plugins/source/postgresql/client.(*Client).syncTables(0x14000534960, {0x105dc9428, 0x14000780600}, {0x0, 0x0}, {0x1400052c700, 0xf, 0x0?}, 0x0?)
	/home/runner/work/cloudquery/cloudquery/plugins/source/postgresql/client/sync.go:99 +0x26c
github.com/cloudquery/cloudquery/plugins/source/postgresql/client.(*Client).Sync(0x14000534960, {0x105dc9428, 0x14000780600}, {{0x14000a01500, 0xf, 0x10}, {0x0, 0x0, 0x0}, 0x1, ...}, ...)
	/home/runner/work/cloudquery/cloudquery/plugins/source/postgresql/client/sync.go:57 +0x304
github.com/cloudquery/plugin-sdk/v4/plugin.(*Plugin).Sync(0x0?, {0x105dc9428?, 0x14000780600?}, {{0x14000a01500, 0xf, 0x10}, {0x0, 0x0, 0x0}, 0x1, ...}, ...)
	/home/runner/go/pkg/mod/github.com/cloudquery/plugin-sdk/v4@v4.16.1/plugin/plugin_source.go:93 +0x120
github.com/cloudquery/plugin-sdk/v4/internal/servers/plugin/v3.(*Server).Sync.func1()
	/home/runner/go/pkg/mod/github.com/cloudquery/plugin-sdk/v4@v4.16.1/internal/servers/plugin/v3/plugin.go:128 +0x8c
created by github.com/cloudquery/plugin-sdk/v4/internal/servers/plugin/v3.(*Server).Sync in goroutine 39
	/home/runner/go/pkg/mod/github.com/cloudquery/plugin-sdk/v4@v4.16.1/internal/servers/plugin/v3/plugin.go:126 +0x210
source plugin process failed with exit status 2
Error: failed to sync v3 source source-db: unexpected error from sync client receive: rpc error: code = Unavailable desc = error reading from server: EOF
- Syncing resources... (948/-, 1482 resources/s) [0s] %
```

### CloudQuery version

3.26.1

### Pull request (optional)

- [ ] I can submit a pull request
