### ISSUE TITLE
Plugin AWS: Need extra permissions ec2:DescribeRegions which are not required to pull Route53 Data

### ISSUE THREAD

**Issue by yvardhineni** [cloudquery/cloudquery#15169]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Created a AWS configurations to fetch Route53 DNS Data with AWS **Route53ReadonlyAccess**.

Cloudquery sync is failing with error: AWS Client Setup is failing with the following [error](https://github.com/cloudquery/cloudquery/blob/main/plugins/source/aws/client/client.go#L270)

### Expected Behavior

Sync should happen without fail, Route53 Data should sync without any additional permissions other than [Route53 Readonly Access](https://docs.aws.amazon.com/aws-managed-policy/latest/reference/AmazonRoute53ReadOnlyAccess.html)

### CloudQuery (redacted) config

```yaml
kind: source
spec:
  name: aws
  path: "cloudquery/aws"
  version: "v22.5.1"
  tables: <dns - tables>
  destinations: postgresql
  deterministic_cq_id: true
  spec:
    accounts:
      - id: aws
        role_arn: role_arn
        external_id: external_id
```

### CloudQuery (redacted) logs

```
 module=aws-src\n2023-11-06T08:45:37Z WRN Failed to find disabled regions for account when checking: us-east-1 error=\“operation error EC2: DescribeRegions, https response error StatusCode: 403, RequestID: 44c1b508-fbbb-4145-9f09-61ba93730a09, api error UnauthorizedOperation: You are not authorized to perform this operation. User: arn:aws:iam::<user> is not authorized to perform: ec2:DescribeRegions because no identity-based policy allows the ec2:DescribeRegions action\” account=\“aws\” module=aws-src\n2023-11-06T08:45:37Z WRN No enabled regions provided in config for account account=\“aws” module=aws-src\n2023-11-06T08:45:37Z ERR finished call grpc.code=Internal grpc.component=server grpc.error=\“rpc error: code = Internal desc = failed to init plugin: failed to initialize client: no AWS accounts were successfully configured. See warning messages in the logs for details\”
```

### CloudQuery version

3.27.3

### Pull request (optional)

- [ ] I can submit a pull request
