### ISSUE TITLE
bug: Github data sync process never finish

### ISSUE THREAD

**Issue by adrian-gil-miranda** [cloudquery/cloudquery#15399]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The Github data sync process process never finish, the data is pulled correctly but then just keeps going at a 0 resource/h rate forever. I have tried with an organization with just 1 repo in order to try to avoid the API rate limits, and this one resource is retrieved but then sync don't finish.

### Expected Behavior

I would expect to retrieve the data and then finish.

### CloudQuery (redacted) config

`tables: ["github_repositories"]`
`concurrency: 1`
`discovery_concurrency: 1`

### CloudQuery (redacted) logs

> 2023-11-21T08:52:16Z INF Start fetching resources destinations=["mongodb (v2.2.11)"] module=cli source="github (cloudquery@cloudquery/github)"
2023-11-21T08:52:16Z INF started call grpc.component=server grpc.method=Sync grpc.method_type=server_stream grpc.service=cloudquery.plugin.v3.Plugin grpc.start_time=2023-11-21T09:52:16+01:00 grpc.time_ms=0.044 module=cli peer.address= protocol=grpc
2023-11-21T08:52:16Z INF Discovering repositories module=github-src
2023-11-21T08:52:17Z INF top level table resolver started client="org: CloudQueryTest repo: CloudQueryTest/CloudQuery-Test" module=github-src table=github_repositories
2023-11-21T08:52:17Z INF started call grpc.component=server grpc.method=Write grpc.method_type=client_stream grpc.service=cloudquery.plugin.v3.Plugin grpc.start_time=2023-11-21T09:52:16+01:00 grpc.time_ms=720.573 module=cli peer.address= protocol=grpc
2023-11-21T08:52:17Z WRN GitHub secondary rate limit detected for API call: https://api.github.com/repos/CloudQueryTest/CloudQuery-Test/dependabot/alerts?per_page=100. Sleeping until 2023-11-21T10:52:17+01:00 module=github-src

### CloudQuery version

3.23.1

### Pull request (optional)

- [ ] I can submit a pull request

**Comment by erezrokah** [comment]
Hi @adrian-gil-miranda, can you share the full configuration specs you're using? Including the plugin version and `orgs` or `repos` config. You can put `****` instead of information you don't want to expose, e.g.

```yaml
kind: source
spec:
  # Source spec section
  name: github
  path: cloudquery/github
  registry: cloudquery
  version: "v7.5.1"
  tables: ["github_repositories"]
  destinations: ["postgresql"]
  spec:
    access_token: `******`
    orgs: ['****'] # Optional. List of organizations to sync from
    repos: [] # Optional. List of repositories to sync from
```

Also it seems you're running with `concurrency: 1` which explains the slow sync.
For better rate limits you can try authenticating with a GitHub app https://hub.cloudquery.io/plugins/source/cloudquery/github/v7.5.1/docs#app-authentication

**Comment by adrian-gil-miranda** [comment]
Hi, first of all thanks for the assistance.

I am using concurrency: 1 to try to avoid the limits but I have tried other values and end up with the same result, that said i don't  have any problems with slow sync, i am able to sync thousands of repository in less than a minute but if try to sync one of the dependent tables the sync get stuck after synchronizing just dozens of resources.

```YAML
kind: source
spec:
  # Source spec section
  name: github
  path: cloudquery/github
  registry: cloudquery
  version: "v7.5.1"
  tables: ["github_repositories"]
  skip_tables: ["github_repository_branches", "github_repository_keys", "github_repository_dependabot_alerts", "github_releases", "github_repository_dependabot_secrets"]
  destinations: ["postgresql"]
  spec:
    access_token: '******'
    orgs: ['****'] # Optional. List of organizations to sync from

    # Optional parameters
    concurrency: 1
    discovery_concurrency: 1
```

**Comment by erezrokah** [comment]
Hi @adrian-gil-miranda thanks for sharing the configuration.

I think it all depends on the number of resources (repositories and dependent tables) in your organization. If it falls under GitHub's rate limits everything should work great.
If you cross that limits by trying to sync more resources (e.g.  `github_repository_branches`) it will all become slow as CloudQuery retries when the rate limits are reached.

A possible solution would be to split the configuration to sync a single repository using the `repos` configuration property.
I would first test what happens if you try to sync a single repository with all dependent tables. A single repository with lots of dependent resources can hang the sync for other ones.

**Comment by adrian-gil-miranda** [comment]
Hi @erezrokah i have tested with a single repository as you suggested and it worked but this leaves me with more questions.

Here are some of the test i have done and the results.

**1. Sync all repositories with all dependent tables**

- Failed, the sync process never finish.
- Only 385 resources synced after more than 16 hours.

**2. Sync all repositories with no dependent tables**

- Worked.
- More than 1700 resources synced in less than a minute.

**3. Sync single repository with dependent tables**

- Worked.
- ~30 resources synced in seconds.


So I don't understand what can i do or configure in order to make the first test work.

Something to take into account is that i can execute the first test and as soon as it gets stuck execute the second test and this second test works without any issues, that doesn't makes sense to me, if the limits are reached the second test should fail too right?

**Comment by erezrokah** [comment]
> So I don't understand what can i do or configure in order to make the first test work.

I don't think you'll be able to use the first config in a single sync due to GitHub rate limits

> if the limits are reached the second test should fail too right?

GitHub has primary rate limits and secondary rate limits. The primary resets every hour, and the secondary ones are subject to GitHub's internal abuse detection mechanism, see https://docs.github.com/en/rest/overview/rate-limits-for-the-rest-api?apiVersion=2022-11-28#about-secondary-rate-limits. The secondary ones make it very hard to predict what will happen when the limits are reached.

My suggestion is to either look at the logs for configuration number 1. and see if the limits is reached on a specific repository, or try configuration number 3 for each repository separately to see what triggers the limit.
Another option is to use configuration number 3. then add more repositories to each (first try with one, then with two, then with three, etc.). That should allow better understanding on what triggers the limit.

**Comment by adrian-gil-miranda** [comment]
Hi @erezrokah I've had more time perform some test and i think i have found the issue, its related to archived repositories, if i enable the dependabot_alerts the sync process stall with this archived repositories, even when trying to sync a single repository.

**Comment by adrian-gil-miranda** [comment]
@erezrokah Yes, i paste the logs below, i was wondering if this could be fixed or atleast if there is a way to configure the module to skip the archived repositories. Many thanks.
> INF Migrating table module=pg-dest table=github_repository_dependabot_alerts
INF Table exists, auto-migrating module=pg-dest table=github_repository_dependabot_alerts
INF Migrating table module=pg-dest table=github_releases
INF Table exists, auto-migrating module=pg-dest table=github_releases
INF Migrating table module=pg-dest table=github_release_assets
INF Table exists, auto-migrating module=pg-dest table=github_release_assets
INF Migrating table module=pg-dest table=github_repository_dependabot_secrets
INF Table exists, auto-migrating module=pg-dest table=github_repository_dependabot_secrets
INF Migrating table module=pg-dest table=github_repository_branches
INF Table exists, auto-migrating module=pg-dest table=github_repository_branches
INF Migrating table module=pg-dest table=github_repository_keys
INF Table exists, auto-migrating module=pg-dest table=github_repository_keys
INF Migrating table module=pg-dest table=github_repositories
INF Table exists, auto-migrating module=pg-dest table=github_repositories
WRN GitHub secondary rate limit detected for API call:

**Comment by erezrokah** [comment]
Hi @adrian-gil-miranda, so based on https://github.com/orgs/community/discussions/19607 and https://docs.github.com/en/code-security/dependabot/dependabot-alerts/about-dependabot-alerts#detection-of-insecure-dependencies it seems once a repository is archived it should not receive new alerts (like issues or PRs) but any existing ones are still there unless dismissed/closed before archiving.

Thinking about this a bit more might be better to have an option to ignore archived repositories so users have the option to chose, and we can also release this in a non breaking change

**Comment by erezrokah** [comment]
Hi @adrian-gil-miranda, you can skip archived repositories via `skip_archived_repos: true`, e.g.

```yaml
kind: source
spec:
  # Source spec section
  name: github
  path: cloudquery/github
  registry: cloudquery
  version: "v7.6.0"
  tables: ["github_repositories"]
  destinations: ["postgresql"]
  spec:
    access_token: `******`
    orgs: ['****'] # Optional. List of organizations to sync from
    repos: [] # Optional. List of repositories to sync from
    skip_archived_repos: true
```

Starting [`v7.6.0` of the GitHub source plugin](https://hub.cloudquery.io/plugins/source/cloudquery/github/v7.6.0/docs#configuration)
