### ISSUE TITLE
bug: azure_security_contacts produces unmarshalling errors

### ISSUE THREAD

**Issue by getglad** [cloudquery/cloudquery#15504]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When syncing `azure_security_contacts`, Azure Plugin `v10.3.0` produces the below
```
ERR table resolver finished with error error="unmarshalling type *armsecurity.ContactList: unmarshalling type *armsecurity.ContactList: json: cannot unmarshal array into Go value of type map[string]json.RawMessage" client=subscriptions/*** module=azure-src table=azure_security_contacts
```

### Expected Behavior

`azure_security_contacts` syncs without error

### CloudQuery (redacted) config

```
kind: source
spec:
  destinations:
  - postgresql
  name: ***
  path: cloudquery/azure
  spec:
    retry_options: null
    skip_subscriptions: null
    subscriptions: null
  tables:
  - azure_security_contacts
  version: v10.3.0
```

### Steps To Reproduce

1. Run CloudQuery with Azure creds in environment

### CloudQuery (redacted) logs

```
ERR table resolver finished with error error="unmarshalling type *armsecurity.ContactList: unmarshalling type *armsecurity.ContactList: json: cannot unmarshal array into Go value of type map[string]json.RawMessage" client=subscriptions/*** module=azure-src table=azure_security_contacts
```

### CloudQuery version

4.1.2

### Pull request (optional)

- [ ] I can submit a pull request
