### ISSUE TITLE
feat: add `cloudquery validate` subcommand to validate a configuration directory

### ISSUE THREAD

**Issue by asaba-hashi** [cloudquery/cloudquery#15704]
### Which problem is this feature request solving?

I would like to check that my configuration is syntactically valid and internally consistent without invoking a full `sync` operation or making any actual API requests using real credentials.

For my use case, the following errors would be nice to catch in CI:

1. Syntactically correct yaml
1. Invalid plugin versions
1. Mismatched plugin versions
1. Missing required fields
1. `spec` should also be validated for syntactic correctness and internal consistency with it's plugin provider.
1. etc

Some of these can be checked with variations and combinations of other commands, but the ask is for:

1. A single subcommand.
2. No side-effects (such as plugin downloads or source/destination API calls).
3. List all problems found instead of failing at the first one.

### Describe the solution you'd like

Add a `cloudquery validate` subcommand that takes similar arguments to `sync`, that just does the minimal loading a checks of the configuration.  If necessary, the user should supply dummy variables values for testing.  Given the following file:

```yaml
kind: source
spec:
  name: aws
  path: cloudquery/aws
  registry: cloudquery
  version: "v19.09.2"
  spec:
    accounts:
       - id: 123456789012
         role: {ROLE_ARN}
         role_session_name: CloudQuerySession
  tables: ["aws_s3_buckets"]
  destinations: ["postgresql"]
```

`cloudquery validate .` should fail with a message listing all detectable errors (i.e. not stopping after the first one).

```
ROLE_ARN is not defined.

plugin version is invalid for aws
```

These checks would be similar to something like what [nomad job validate](https://developer.hashicorp.com/nomad/docs/commands/job/validate) is able to check.

The command should not make any changes or fetch new versions of plugins.

### Pull request (optional)

- [ ] I can submit a pull request
