### ISSUE TITLE
bug: AWS Lambda Function tags are not being set

### ISSUE THREAD

**Issue by jutley** [cloudquery/cloudquery#15727]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Row in the table `aws_lambda_functions` have their `tags` column set to null, despite having tags defined.

### Expected Behavior

Tags actually show up.

### CloudQuery (redacted) config

```yaml
---
kind: source
spec:
  # Source spec section
  name: aws
  path: cloudquery/aws
  version: "v23.2.0"
  skip_dependent_tables: true
  concurrency: 10000
  tables:
    - aws_acm_certificates
    - aws_athena_work_groups
    - aws_autoscaling_groups
    - aws_cloudtrail_trails
    - aws_cloudwatchlogs_log_groups
    - aws_dynamodb_tables
    - aws_dynamodb_global_tables
    - aws_ec2_instances
    - aws_elasticache_clusters
    - aws_elasticsearch_domains
    - aws_elbv2_load_balancers
    - aws_lambda_functions
    - aws_glue_databases
    - aws_glue_jobs
    - aws_guardduty_detectors
    - aws_organizations_accounts
    - aws_rds_clusters
    - aws_rds_instances
    - aws_redshift_clusters
    - aws_route53_domains
    - aws_route53_hosted_zone_resource_record_sets
    - aws_s3_buckets
    - aws_securityhub_hubs
    - aws_sqs_queues
    - aws_support_cases
    - aws_support_case_communications
    - aws_transfer_servers
  destinations:
    - postgresql
  spec:
    aws_debug: false
    org: <redacted>
```

### Steps To Reproduce

1. Have a Lambda with tags
2. Run Cloudquery with the aws_lambda_functions table enabled
3. Check the tags. They will be null.

### CloudQuery (redacted) logs

```
2023-12-18T21:12:53Z INF top level table resolver started client=<account_id>:eu-west-1 module=aws-src table=aws_lambda_functions
2023-12-18T21:12:54Z WRN location of lambda function redacted for security purposes account_id=<account_id> module=aws-src region=eu-west-1
2023-12-18T21:12:54Z WRN location of lambda function redacted for security purposes account_id=<account_id> module=aws-src region=eu-west-1
2023-12-18T21:12:54Z INF table sync finished client=<account_id>:eu-west-1 errors=0 module=aws-src resources=2 table=aws_lambda_functions
```

### CloudQuery version

4.3.4

### Additional Context

I'm pretty certain this is just a result of bad copy-pasting during the change to redact the code location. This block shows the value for `concurrency` is being used instead of `tags`.
https://github.com/cloudquery/cloudquery/blob/main/plugins/source/aws/resources/services/lambda/functions.go#L308-L310

### Pull request (optional)

- [x] I can submit a pull request
