### ISSUE TITLE
feat: Support connecting to OCI Dedicated Region in CloudQuery Oracle source plugin

### ISSUE THREAD

**Issue by gianluca-ava** [cloudquery/cloudquery#16015]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm trying to run cloudquery towards an OCI Dedicated Region passing the same variables used for OCI. The task fail with the following error: 

> dial tcp: lookup identity.<new_region>.oci.oraclecloud.com on 10.0.0.2:53: no such host.

### Expected Behavior

With terraform I had the same issue that I've solved passing a new variable:

> domain_name_override
 
as documented in the following doc: 
https://docs.oracle.com/en-us/iaas/Content/API/Concepts/sdk_adding_new_region_endpoints.htm

I need that cloudquery support the variable listed above like below:

```
{
                  "name": "TF_VAR_domain_name_override",
                  "value": "oraclecloudXX.com"
}
```

### CloudQuery (redacted) config

```
kind: source
spec:
 # Source spec section
  name: oracle
  path: "cloudquery/oracle"
  version: "v4.2.0"
  tables: ["*"]
  skip_tables:
    - "oracle_compute_images"
    - "oracle_compute_vnic_attachments"
    - "oracle_virtualnetwork_fast_connect_provider_services"
    - "oracle_blockstorage_boot_volumes"
    - "oracle_blockstorage_volumes"
  destinations: ["postgresql"] 
  spec:
    concurrency: 500
---
kind: destination
spec:
  name: "postgresql"
  path: "cloudquery/postgresql"
  version: "v6.1.0"
  spec:
    connection_string: "postgresql://${user}:${password}@${host}:${port}/${database}?sslmode=require"
```

### CloudQuery (redacted) logs

```
Error: failed to sync v3 source oracle: unexpected error from sync client receive: rpc error: code = Unknown desc = failed to sync records: failed to sync unmanaged client: failed to list compartments in tenancy: 
Get "https://identity.<new_region>.oci.oraclecloud.com/20160918/compartments?compartmentId=<compartmentID>&compartmentIdInSubtree=true&lifecycleState=ACTIVE": 
dial tcp: lookup identity.<new_region>.oci.oraclecloud.com on 10.0.0.2:53: no such host
```

### CloudQuery version

3.23.0

### Additional Context

discussed on discord: https://discord.com/channels/872925471417962546/1192132713986142248/1192153663133720698

### Pull request (optional)

- [ ] I can submit a pull request

**Comment by candiduslynx** [comment]
Hi @gianluca-ava!

Could you do some additional research so that we can implement this better?

First off, have you tried using `OCI_REGION_METADATA` as described in this [doc](https://docs.oracle.com/en-us/iaas/Content/API/Concepts/sdk_adding_new_region_endpoints.htm#SDK_Adding_Regions_Environment_Variable)?

Or using the [cfg file](https://docs.oracle.com/en-us/iaas/Content/API/Concepts/sdk_adding_new_region_endpoints.htm#SDK_Adding_Regions_Config_File)?

**Comment by gianluca-ava** [comment]
Hi @candiduslynx
I'm running cloudquery via AWS ECS using the TF environment variable as described in the Option 2 of the cloudquery doc. 
I'm not sure I can pass a non key-value pair object to the container as figure out using OCI_REGION_METADATA.
I'm trying the config file way but still no success...

**Comment by candiduslynx** [comment]
The [docs](https://docs.oracle.com/en-us/iaas/Content/API/Concepts/sdk_adding_new_region_endpoints.htm#SDK_Adding_Regions_Environment_Variable) list a way to export the variable as
```sh
export OCI_REGION_METADATA='{"realmKey":"OC1","realmDomainComponent":"oraclecloud.com","regionKey":"SYD","regionIdentifier":"ap-sydney-1"}'
```

So you could instead use this in YAML:
```yaml
env:
  OCI_REGION_METADATA: '{ "realmKey":"OC1", "realmDomainComponent":"oraclecloud.com",
    "regionKey":"SYD", "regionIdentifier":"ap-sydney-1" }'
```
or for better readability:
```yaml
env:
  OCI_REGION_METADATA: >-
    {
    "realmKey":"OC1",
    "realmDomainComponent":"oraclecloud.com",
    "regionKey":"SYD",
    "regionIdentifier":"ap-sydney-1"
    }
```
