### ISSUE TITLE
bug: When publishing plugin documentation; version is pointing to the wrong plugin

### ISSUE THREAD

**Issue by dsmith111** [cloudquery/cloudquery#16031]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When publishing the documentation for a plugin, the standard for implementing the version seems to be:
"VERSION_<TYPE>_<NAME>"

When I add this to my documentation, I get the "Azure" plugin version with "AD" appended to it:
"v11.3.0-AD"

### Expected Behavior

I'd just expect my configuration to have the Azure-AD v1.x.x placed in it.

### CloudQuery (redacted) config

```yaml copy
kind: source
spec:
  # Source spec section
  name: "azure-ad"
  path: "year-of-the-nimbus/azure-ad"
  registry: "cloudquery"
  version: "VERSION_SOURCE_AZURE-AD"
  destinations: ["DESTINATION_NAME"]
  tables: ["azure_ad_users"]
  spec:
    # Optional parameters
    # concurrency: 50000
```

### Steps To Reproduce

Create documentation using the version call with a non a-z0-9_ character
Publish plugin
View results

### CloudQuery (redacted) logs

N/A

### CloudQuery version

N/A

### Additional Context

https://github.com/cloudquery/cloudquery/blob/76479fed2d726d57ec112f8e2e568eaee0acd7c3/website/next.config.mjs#L10

I believe the RegEx here just needs to be updated to accept "-" dash characters as it already appears to accept "_" delimiters.

### Pull request (optional)

- [ ] I can submit a pull request
