### ISSUE TITLE
bug: arm64 docker images are actually built for amd64

### ISSUE THREAD

**Issue by JumaX** [cloudquery/cloudquery#16218]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Env: OSX Sonoma 14.1
Docker Desktop: 4.26.1
Hardware: M1 Max, 32GB of RAM

Building a local docker environment using the following images fails:

`ghcr.io/cloudquery/cloudquery:latest-linux-arm64`

> Error response from daemon: image with reference ghcr.io/cloudquery/cloudquery:latest-linux-arm64 was found but does not match the specified platform: wanted linux/arm64, actual: linux/amd64

`ghcr.io/cloudquery/cloudquery:4.4-linux-arm64`

> Error response from daemon: image with reference ghcr.io/cloudquery/cloudquery:4.4-linux-arm64 was found but does not match the specified platform: wanted linux/arm64, actual: linux/amd64

Docker inspect output on both confirms they are built for `amd64`:

`
        "Architecture": "amd64",
        "Os": "linux",
        "Size": 47424823,
        "VirtualSize": 47424823,
`

Using DockerDesktop you can also view the image hierarchy and can see that these images are based on a root image for Alpine 3.19 for X86.

Links to here: 
https://github.com/alpinelinux/docker-alpine/blob/97c57449282d97cfa1c0b64669aed9afbf08645a/x86_64/Dockerfile 

<img width="1218" alt="Screenshot 2024-01-20 at 12 29 01" src="https://github.com/cloudquery/cloudquery/assets/1376580/fdf2238c-71ef-4d3f-a194-b53125f2de40">

### Expected Behavior

The expected behaviour is that images tagged with `linux/arm64` would be built for the arm64 platform and not `amd64`.

### CloudQuery (redacted) config

Not Applicable.

### Steps To Reproduce

Env: OSX Sonoma 14.1
Docker Desktop: 4.26.1
Hardware: M1 Max, 32GB of RAM

1. Pull either image:

`docker pull ghcr.io/cloudquery/cloudquery:latest-linux-arm64`

`docker pull ghcr.io/cloudquery/cloudquery:4.4-linux-arm64`

2. Use a simple docker compose file like the following:

```
version: "3.8"
services:
  cloudquery_demo:
    image: ghcr.io/cloudquery/cloudquery:latest-linux-arm64
    platform: linux/arm64
    container_name: cloudquery
    pull_policy: never
    volumes:
      - ./config.yml:/cache/.cq
    ports:
      - "7777:7777"
    depends_on:
      - db_source
      - db_destination

  db_source:
    image: postgres:15.5
    container_name: postgres_db_source
    environment:
      POSTGRES_USER: <redacted>
      POSTGRES_PASSWORD: <redacted>
      POSTGRES_DB: <redacted>
    volumes:
      - ./postgres_data_source:/var/lib/postgresql/data/
      - ./init-db-source.sh:/docker-entrypoint-initdb.d/init-db.sh
    ports:
      - "5432:5432"

  db_destination:
    image: postgres:15.5
    container_name: postgres_db_destination
    environment:
      POSTGRES_USER: <redacted>
      POSTGRES_PASSWORD: <redacted>
      POSTGRES_DB: <redacted>
    volumes:
      - ./postgres_data_destination:/var/lib/postgresql/data/
      - ./init-db-destination.sh:/docker-entrypoint-initdb.d/init-db.sh
    ports:
      - "5433:5432"
```

3. Docker-compose up -d

You will then see the incompatibility with either image.

### CloudQuery (redacted) logs

Not Applicable.

### CloudQuery version

Not applicable.

### Additional Context

Looks like ARM image support was added in October 2023.

https://github.com/cloudquery/cloudquery/issues/14506

There are not many downloads, suspect most of them are me. :). My guess is the build pipeline was updated or changed and there isn't verification on these images.

https://github.com/cloudquery/cloudquery/pkgs/container/cloudquery

### Pull request (optional)

- [ ] I can submit a pull request
