### ISSUE TITLE
bug: GCP projects missing metadata

### ISSUE THREAD

**Issue by RichardoC** [cloudquery/cloudquery#16755]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Only the following fields are available for projects
``Columns
NAME	TYPE
_cq_id	uuid
_cq_parent_id	uuid
project_id	utf8
```
https://hub.cloudquery.io/plugins/source/cloudquery/gcp/latest/tables/gcp_projects

### Expected Behavior

The full data model is documented in https://cloud.google.com/compute/docs/reference/rest/v1/projects#resource:-project and I expected all fields to be available. In particular commonInstanceMetadata, creationsTimestamp and quotas as they're useful to be able to check when there are a large number of projects.

### CloudQuery (redacted) config

```yaml

kind: source
spec:
  name: "gcp"
  path: "cloudquery/gcp"
  version: "v10.0.0"
  tables: ["*"]
  destinations: ["bigquery"]
---
kind: destination
spec:
  name: bigquery
  path: cloudquery/bigquery
  version: "v3.3.8"
  write_mode: append # BigQuery plugin does not support overwrite
  migrate_mode: forced # This can be removed after successful migration
  spec:
    project_id: REDACTED
    dataset_id: REDACTED
```

### CloudQuery (redacted) logs

N/A

### CloudQuery version

4.1.2

### Additional Context

From looking at plugins/source/gcp/resources/services/compute/projects.go:16 I would expect these fields to be present since we're providing the full Project struct. 

Happy to fix this if someone can give me a pointer about what/where the issue is

### Pull request (optional)

- [ ] I can submit a pull request
