### ISSUE TITLE
bug: AWS Source plugin

### ISSUE THREAD

**Issue by mMeijden** [cloudquery/cloudquery#16818]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Recently i've upgraded the source and destination versions. During the upgrade to v24.3.2 the AWS source plugin throws the following error
> 2024-02-22T11:50:42Z ERR exiting with error error="failed to sync v3 source aws_REDACTED: write client returned error (insert): plugin returned error: failed to execute batch with pgerror: severity: ERROR, code: 42703, message: column \"limitless_database\" of relation \"aws_rds_clusters\" does not exist, detail :, hint: , position: 1256, internal_position: 0, internal_query: , where: , schema_name: , table_name: , column_name: , data_type_name: , constraint_name: , file: parse_target.c, line: 1272, routine: checkInsertTargets: ERROR: column \"limitless_database\" of relation \"aws_rds_clusters\" does not exist (SQLSTATE 42703)" module=cli

As noted in the v24 changelog, it is recommended to run `>v.7.3.1` postgres destination version. So we've upgraded to `v7.3.4` first, ran the syncs and then tried to upgrade the AWS source plugin.

Due to this error the sync stops abruptly.

**Workaround:**
Throw away the table and run the sync again.

### Expected Behavior

Expected to have the new column added properly to the new table without an error

### CloudQuery (redacted) config

```yaml
kind: source
spec:
  name: "aws_${ACCOUNT_ID}"
  registry: cloudquery
  path: "cloudquery/aws"
  version: "v24.3.2"
  tables:
    [
      #...rest omitted...
      "aws_rds_clusters",
      #...rest omitted...
    ]

  skip_tables:
    [
      #...omitted
    ]

  destinations: ["postgresql"]

  spec:
    regions:
      - eu-west-1
      - us-east-1
    accounts:
      - id: "cloudquery"
        role_arn: ${CLOUD_QUERY_ROLE_ARN}
        role_session_name: ${SESSION_NAME}
   
---
kind: destination
spec:
  name: "postgresql"
  path: "cloudquery/postgresql"
  version: "v7.3.4"
  write_mode: "overwrite-delete-stale"
  migrate_mode: "forced"
  spec:
    connection_string: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${DB_ENDPOINT}:${DB_PORT}/${POSTGRES_DBNAME}

```

### Steps To Reproduce

1. Run version v23.2.0 AWS source
2. Add an entry to rds cluster entry in the table aws_rds_clusters
3. Upgrade to v24.3.2 AWS source
4. Run sync again

### CloudQuery (redacted) logs

see above

### CloudQuery version

cloudquery version 5.5.1

### Additional Context

We've migrated from aws source `v23.2.0` -> `v24.3.2`
We've migrated postgresql destination from `v6.1.3` to `v7.3.4`

### Pull request (optional)

- [ ] I can submit a pull request
