### ISSUE TITLE
New Version Upgrade is throwing a error in cloudquery

### ISSUE THREAD

**Issue by Prabhanjali** [cloudquery/cloudquery#17128]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

**Current Version**
  postgres - v7.3.3
  aws - v23.7.0
  azure - v11.4.3
  cli - v5.5.0
  
**Previous Version**
  postgres - v7.0.0
  aws - v23.1.0
  azure - v11.0.0
  cli - v5.5.0

This change worked fine. But I can see that now when I tried changing the versions of cloudquery is taking more time than expected. The expected time is around 2 and half hours and now after upgradation, it is taking 10 hours.

Please select what am I missing?

### Expected Behavior

expected to run for 1100 accounts in 2 and half hours but taking around 10 hours to run and failing.

### CloudQuery (redacted) config
```yaml
kind: source
spec:
  name: "aws_xxxxxxxxxxxx"
  path: "cloudquery/aws"
  version: "23.1.0"
  tables: ["*"]
  spec:
      accounts:
          - id: "xxxxxxxxxxxx"
            role_arn: "arn:aws:iam::xxxxxxxxxxxx:role/fds-cloud-admin/aws-inventory-role"
    """
```

### CloudQuery (redacted) logs

.

### CloudQuery version

5.5.0

### Pull request (optional)

- [ ] I can submit a pull request

**Comment by erezrokah** [comment]
Hi @Prabhanjali it's not recommended to use `tables: ["*"]` as that syncs all tables and can be very slow. We add new tables with each release hence the change in sync time.

There's a list of tables here https://hub.cloudquery.io/plugins/source/cloudquery/aws/v23.1.0/docs#configuration-skip-tables we recommend skipping to avoid long sync times

**Comment by Prabhanjali** [comment]
@erezrokah , We always run this for all the tables at a time and there isn't any issue. Now when we upgarde to a newer version of cloudquery plugins, we are running into a issue where the syncing of tables is taking time. Also, I did skipped all the newly added tables because they are of premium ones.

**Comment by erezrokah** [comment]
> @erezrokah , We always run this for all the tables at a time and there isn't any issue. Now when we upgarde to a newer version of cloudquery plugins, we are running into a issue where the syncing of tables is taking time. Also, I did skipped all the newly added tables because they are of premium ones.

We add new tables with newer versions. When use configure `*` you implicitly gets all of the new ones, some are quite big and slow to sync.

You don't need to configure each table under `tables:` manually, you can chose to configure the skip list based on the link I shared in https://hub.cloudquery.io/plugins/source/cloudquery/aws/v23.1.0/docs#configuration-skip-tables

For example:

```yaml
kind: source
spec:
  name: "aws_xxxxxxxxxxxx"
  path: "cloudquery/aws"
  version: "23.1.0"
  tables: ["*"]
  skip_tables:
    - aws_cloudtrail_events
    - aws_docdb_cluster_parameter_groups
    - aws_docdb_engine_versions
    - aws_ec2_instance_types
    - aws_ec2_vpc_endpoint_services
    - aws_elasticache_engine_versions
    - aws_elasticache_parameter_groups
    - aws_elasticache_reserved_cache_nodes_offerings
    - aws_elasticache_service_updates
    - aws_iam_group_last_accessed_details
    - aws_iam_policy_last_accessed_details
    - aws_iam_role_last_accessed_details
    - aws_iam_user_last_accessed_details
    - aws_neptune_cluster_parameter_groups
    - aws_neptune_db_parameter_groups
    - aws_rds_cluster_parameter_groups
    - aws_rds_db_parameter_groups
    - aws_rds_engine_versions
    - aws_servicequotas_services
    - aws_stepfunctions_map_run_executions
    - aws_stepfunctions_map_runs
  spec:
      accounts:
          - id: "xxxxxxxxxxxx"
            role_arn: "arn:aws:iam::xxxxxxxxxxxx:role/fds-cloud-admin/aws-inventory-role"
```

Would you mind trying that and see if that works?

**Comment by Prabhanjali** [comment]
Checking on it and let you know soon.

**Comment by erezrokah** [comment]
Hi @Prabhanjali can share the configuration and versions for the shorter sync time?

Is it:

postgres - v7.0.0
aws - v23.1.0
azure - v11.0.0
cli - v5.5.0

```
kind: source
spec:
  name: "aws_xxxxxxxxxxxx"
  path: "cloudquery/aws"
  version: "23.1.0"
  tables: ["*"]
  spec:
      accounts:
          - id: "xxxxxxxxxxxx"
            role_arn: "arn:aws:iam::xxxxxxxxxxxx:role/fds-cloud-admin/aws-inventory-role"
```

and the configuration and versions for the longer sync time?

Is it:

postgres - v7.3.3
aws - v23.7.0
azure - v11.4.3
cli - v5.5.0

```
kind: source
spec:
  name: "aws_xxxxxxxxxxxx"
  path: "cloudquery/aws"
  version: "23.7.0"
  tables: ["*"]
  spec:
      accounts:
          - id: "xxxxxxxxxxxx"
            role_arn: "arn:aws:iam::xxxxxxxxxxxx:role/fds-cloud-admin/aws-inventory-role"
```
?

Can you share redacted logs for both syncs? Also can you try using the same postgres version for both? e.g use v7.3.3 for both
