### ISSUE TITLE
bug: Plugin installation requires "cloudquery login"

### ISSUE THREAD

**Issue by massynmantel** [cloudquery/cloudquery#17243]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Cloudquery installations in my CI/CD pipelines are now failing, because it seems that a plugin installation is now requiring "cloudquery login"

```
Error: unauthorized. Try logging in via `cloudquery login`
```

Trying to run `cloudquery login`, my system gets redirected to a browser for login, which is not available in a CI/CD pipeline.  There is also no way to pass the username and password to the command.

### Expected Behavior

Plugins should be able to be installed without having to authenticate to the Cloudquery hub

### CloudQuery (redacted) config

```yaml
kind: source
spec:
  # Source spec section
  name: okta
  path: cloudquery/okta
  registry: cloudquery
  version: "v4.1.4"
  tables: ["*"]
  destinations: ["postgresql"]
  spec:
    # required, Okta domain name, for example: https://example.okta.com, https://example.okta-emea.com,  https://example.oktapreview.com
    domain: "OKTA_DOMAIN"
    # required, Okta Token to access API
    token: "OKTA_ACCESS_TOKEN"

    # Optional. Rate limiter settings
    # rate_limit:
    #   max_backoff: 5s
    #   max_retries: 3
---
kind: destination
spec:
  name: "postgresql"
  path: "cloudquery/postgresql"
  registry: "cloudquery"
  version: "v7.6.0"

  spec:
    connection_string: "POSTGRESQL_CONNECTION_STRING" # set the environment variable in a format like postgres://postgres:pass@localhost:5432/postgres?sslmode=disable
    # you can also specify it in DSN format, which can hold special characters in the password field:
    # connection_string: "user=postgres password=pass+0-[word host=localhost port=5432 dbname=postgres"
    # Optional parameters:
    # pgx_log_level: error
    # batch_size: 10000 # 10K entries
    # batch_size_bytes: 100000000 # 100 MB
    # batch_timeout: 60s
```

### Steps To Reproduce

Try to install any plugin, and the error message will appear.

### CloudQuery (redacted) logs

```
2024-03-20T06:44:15Z INF Loading spec(s) args=["okta.yml"] module=cli
2024-03-20T06:44:15Z WRN when using the CloudQuery registry, it's recommended to log in via `cloudquery login`. Logging in allows for better rate limits and downloading of premium plugins module=cli
2024-03-20T06:44:16Z ERR exiting with error error="unauthorized. Try logging in via `cloudquery login`" module=cli
```

### CloudQuery version

cloudquery version 4.3.4

### Pull request (optional)

- [ ] I can submit a pull request
