### ISSUE TITLE
bug: Docker plugins from CloudQuery registry don't work with team API keys

### ISSUE THREAD

**Issue by erezrokah** [cloudquery/cloudquery#17579]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Using an API key with Docker plugins from CloudQuery registry fail with an error:
```
Error: team required. Hint: use `cloudquery switch` to set a team
```

### Expected Behavior

CLI should be able to work with Docker plugins from CloudQuery registry and team API keys

### CloudQuery (redacted) config

```yaml
kind: source
spec:
  name: airtable
  registry: docker
  path: docker.cloudquery.io/cloudquery/source-airtable:v2.1.2
  tables:
    - "*"
  destinations: ["postgresql"]
  spec:
    access_token: "redacted"
---
kind: destination
spec:
  name: "postgresql"
  path: "cloudquery/postgresql"
  version: "v8.0.2"
  spec:
    connection_string: "postgresql://postgres:pass@localhost:5432/postgres?sslmode=disable"
```

### Steps To Reproduce

1. Run `CLOUDQUERY_API_KEY=<your-api-key> cloudquery plugin install spec.yml` with the above spec

### CloudQuery (redacted) logs

N/A

### CloudQuery version

`cloudquery version 5.13.1`

### Pull request (optional)

- [X] I can submit a pull request
