### ISSUE TITLE
bug: Failed to save state: write failed: table cq_state_bq not found

### ISSUE THREAD

**Issue by hermanschaaf** [cloudquery/cloudquery#17570]
This is a strange error that I only encountered once. 

The error states that the state table was not found, but it was definitely already there from a previous sync. When I just re-ran the sync, without changing anything else, it worked as expected.

The error:
```
➜ cloudquery sync bigquery-source.yml
Loading spec(s) from bigquery-source.yml
Starting sync for: bigquery (cloudquery/bigquery@v1.3.1) -> [postgresql (cloudquery/postgresql@v7.3.3)]
- Syncing resources... (37/-, 7 resources/s) [11s] Error: failed to sync v3 source bigquery: unexpected error from sync client receive: rpc error: code = Internal desc = failed to sync records: failed to sync unmanaged client: failed to save state: rpc error: code = Internal desc = write failed: table cq_state_bq not found
```

Subsequent runs, without changing anything:

```
➜ cloudquery sync bigquery-source.yml
Loading spec(s) from bigquery-source.yml
Starting sync for: bigquery (cloudquery/bigquery@v1.3.1) -> [postgresql (cloudquery/postgresql@v7.3.3)]
Sync completed successfully. Resources: 1, Errors: 0, Warnings: 0, Time: 9s
➜ cloudquery sync bigquery-source.yml
Loading spec(s) from bigquery-source.yml
Starting sync for: bigquery (cloudquery/bigquery@v1.3.1) -> [postgresql (cloudquery/postgresql@v7.3.3)]
Sync completed successfully. Resources: 2, Errors: 0, Warnings: 0, Time: 11s
```

Details:
- cloudquery version 5.9.0
- config:
```
kind: source
spec:
  name: "bigquery"
  path: "cloudquery/bigquery"
  version: v1.3.1
  tables:
    - "bq_my_table"
  destinations: ["postgresql"]
  backend_options:
    table_name: "cq_state_bq"
    connection: "@@plugins.postgresql.connection"
  spec:
    project_id: cq-cloud-prod
    dataset_id: billing
    queries:
      - name: bq_my_table
        query: "SELECT * FROM my_table WHERE end_time >= @cursor"
        incremental_column: end_time
        incremental_column_type: TIMESTAMP
---
kind: destination
spec:
  name: "postgresql"
  path: "cloudquery/postgresql"
  registry: "cloudquery"
  version: "v7.3.3"
  migrate_mode: forced
  spec:
    connection_string: "postgresql://postgres:pass@localhost:5432/cloudquery?sslmode=disable"
```
