### ISSUE TITLE
bug: Snyk Rate Limiting

### ISSUE THREAD

**Issue by komodo472** [cloudquery/cloudquery#17671]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Snyk rate limit (429) ends sync early causing not all resources to be synced.

### Expected Behavior

Sync of Snyk collects all resources

### CloudQuery (redacted) config

```yaml
kind: source
spec:
  name: "snyk"
  path: "cloudquery/snyk"
  version: "v5.3.5"
  tables:
    - "snyk_container_images"
    - "snyk_custom_base_images"
    - "snyk_issues"
    - "snyk_organizations"
    - "snyk_projects"
    - "snyk_sbom"
  destinations: ["postgresql"]
  spec:
    api_key: "${SNYK_API_KEY}"
    organizations:
      - "<redacted>"
```

### Steps To Reproduce

Use Synk organization with many targets that contain many projects

### CloudQuery (redacted) logs

```
2024-04-16T20:08:49Z ERR table resolver finished with error error="[GET /orgs/{org_id}/projects/{project_id}/sbom] getSbom (status 429): {}" client=c96482b5-b83e-43e6-9462-60fd98a8dd8d-f2e04307-7c37-4d63-8422-76dc345c0aa2 invocation-id=a7ebdee4-ba01-4c9d-962a-5bb6bfef7abc module=snyk-source table=snyk_sbom
2024-04-16T20:08:49Z INF table sync finished client=c96482b5-b83e-43e6-9462-60fd98a8dd8d-f2e04307-7c37-4d63-8422-76dc345c0aa2 errors=1 invocation-id=a7ebdee4-ba01-4c9d-962a-5bb6bfef7abc module=snyk-source resources=0 table=snyk_sbom
```

### CloudQuery version

5.11.0

### Additional Context

Snyk Docs
> There is a limit of 1620 requests per minute, per API key. All requests above the limit will get a response with status code 429 - Too many requests until requests stop for the duration of the rate-limiting interval (currently one minute).

https://apidocs.snyk.io/?&version=2024-04-11#rate-limiting

### Pull request (optional)

- [ ] I can submit a pull request
