### ISSUE TITLE
bug: Running Sequential Syncs with MySQL results in error

### ISSUE THREAD

**Issue by bbernays** [cloudquery/cloudquery#17684]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Running Sequential Syncs with MySQL results in errors with migration

### Expected Behavior

No Errors

### CloudQuery (redacted) config

```
kind: source
spec:
  name: shopify
  path: cloudquery/shopify
  version: "v5.1.11"
  tables: ["*"]
  destinations: ["mysql"]
  spec:
    access_token: "XX"
    api_version: "2024-01"
    page_size: 250
---
kind: destination
spec:
  name: "mysql"
  registry: "cloudquery"
  path: "cloudquery/mysql"
  version: "v5.0.4"
  write_mode: "overwrite-delete-stale"
  spec:
    connection_string: "root:test@/cloudquery"
```

### Steps To Reproduce

1. `cloudquery migrate config.yml` -- This will work successfully
2. `cloudquery migrate config.yml` -- This will fail

### CloudQuery (redacted) logs

```
Error: failed to migrate v3 source shopify: rpc error: code = Internal desc = write failed: failed to flush: tables shopify_customers,shopify_orders,shopify_products,shopify_product_variants,shopify_product_images,shopify_price_rules,shopify_price_rule_discount_codes,shopify_abandoned_checkouts with changes [[column: _cq_id, previous: _cq_id:uuid:NotNull:Unique] [column: _cq_id, previous: _cq_id:uuid:NotNull:Unique] [column: _cq_id, previous: _cq_id:uuid:NotNull:Unique] [column: _cq_id, previous: _cq_id:uuid:NotNull:Unique] [column: _cq_id, previous: _cq_id:uuid:NotNull:Unique] [column: _cq_id, previous: _cq_id:uuid:NotNull:Unique] [column: _cq_id, previous: _cq_id:uuid:NotNull:Unique] [column: _cq_id, previous: _cq_id:uuid:NotNull:Unique]] require migration. Migrate manually or consider using 'migrate_mode: forced'
```

### CloudQuery version

cloudquery version 5.11.0

### Pull request (optional)

- [ ] I can submit a pull request
