### ISSUE TITLE
Feedback for Official Stripe Plugin.

### ISSUE THREAD

**Issue by aitoehigie** [cloudquery/cloudquery#17698]
Your official Stripe plugin returns this error: 
`Loading spec(s) from stripe.yml, sqlite.yml
Starting sync for: stripe (cloudquery@cloudquery/stripe) -> [sqlite (cloudquery@cloudquery/sqlite)]
Error: failed to sync v3 source stripe: unexpected error from sync client receive: rpc error: code = Internal desc = failed to sync records: failed to sync unmanaged client: failed to create state client: rpc error: code = Internal desc = write failed: failed to flush: failed to create table with 'CREATE TABLE IF NOT EXISTS "cq_state_stripe" ("key" text,"value" text, CONSTRAINT "cq_state_stripe_cqpk" PRIMARY KEY ("key"))': Binary was compiled with 'CGO_ENABLED=0', go-sqlite3 requires cgo to work. This is a stub
`
It was built with 'CGO_ENABLED=0

**Comment by bbernays** [comment]
@aitoehigie What version of the sqlite plugin are you using?

**Comment by aitoehigie** [comment]
@bbernays v2.8.2 (The latest version)

**Comment by bbernays** [comment]
Can you share some more information about the OS and or container you are running this in so we can troubleshoot the issue?

**Comment by aitoehigie** [comment]
Linux Mint 21.1 
Kernel 6.5.7-060507-generic  x86_64 x86_64 x86_64 GNU/Linux
go version go1.21.5 linux/amd64

Running directly on host and not in a container.

**Comment by aitoehigie** [comment]
Stripe:
`kind: source
# Common source-plugin configuration
spec:
  name: stripe
  path: cloudquery/stripe
  registry: cloudquery
  version: "v3.2.12"
  tables: ["*"]
  destinations: ["sqlite"]
  skip_tables:
    - stripe_issuing*  # Needs sign-up at https://stripe.com/issuing
    - stripe_treasury* # Needs sign-up at https://stripe.com/treasury
    - stripe_sigma_scheduled_query_runs # Live keys only
  backend_options:
    table_name: "cq_state_stripe"
    connection: "@@plugins.sqlite.connection"
  # Stripe specific configuration
  spec:
    # required
    api_key: "${STRIPE_API_KEY}"`
    
    
Sqlite:
`kind: destination
spec:
  name: sqlite
  path: cloudquery/sqlite
  registry: cloudquery
  version: "v2.8.0"
  spec:
    connection_string: ./db.sql
`

**Comment by bbernays** [comment]
@aitoehigie - We had an issue earlier today where `v2.8.0` of the sqlite plugin was being compiled without `cgo` enabled. Which is the error you were seeing. If you upgrade to `v2.8.2` you should have no issues

**Comment by aitoehigie** [comment]
I had the understanding that installing the latest cloudquery installed the latest plugins?
If this assumption is incorrect, how do I upgrade the sqlite plugin to the latest version?

**Comment by aitoehigie** [comment]
@bbernays 
cloudquery -v
cloudquery version 5.15.2
which comes with cloudquery/sqlite@v2.8.0 not v2.8.2

Excuse my many questions, I just started using Cloudquery today.

**Comment by bbernays** [comment]
Welcome to CloudQuery sorry you had issues on your first day, but I am glad we can get them sorted out! In your spec files there is a version of each plugin you are using.
For stripe:
```
version: "v3.2.12"
```

For sqlite:
```
version: "v2.8.0"
```


The CLI is versioned separately from all of the other plugins to enable better interoperability


Here is a config using the newest sqlite version:

```
kind: source
# Common source-plugin configuration
spec:
  name: stripe
  path: cloudquery/stripe
  registry: cloudquery
  version: "v3.2.12"
  tables: ["*"]
  destinations: ["sqlite"]
  skip_tables:
    - stripe_issuing*  # Needs sign-up at https://stripe.com/issuing
    - stripe_treasury* # Needs sign-up at https://stripe.com/treasury
    - stripe_sigma_scheduled_query_runs # Live keys only
  backend_options:
    table_name: "cq_state_stripe"
    connection: "@@plugins.sqlite.connection"
  # Stripe specific configuration
  spec:
    # required
    api_key: "${STRIPE_API_KEY}"
---
kind: destination
spec:
  name: sqlite
  path: cloudquery/sqlite
  registry: cloudquery
  version: "v2.8.2"
  spec:
    connection_string: ./db.sql
```
