### ISSUE TITLE
AWS Org Role

### ISSUE THREAD

**Issue by bbernays** [cloudquery/cloudquery#1771]
Currently the AWS Org Integration requires that member accounts have a trust relationship with role that you use in order list member accounts or you have to specify a different role for CloudQuery to assume.

Users should be able to use the base execution role that was used to assume the role in the admin account to assume a role in each member account.

**Comment by yevgenypats** [comment]
Can you please elaborate on this a bit more? Do we want to this before v2? as it might be a breaking change to config ?

**Comment by bbernays** [comment]
This work is not 100% necessary. If a user specifies **just** the `id` field in `member_trusted_principle` then it will force the SDK to grab all of the information from the environment:

```
org:
  member_role_name: OrganizationAccountAccessRole
  admin_account:
    local_profile: <Named-Profile-Admin>
  member_trusted_principal:
    id: 'default-env-creds'
```
