### ISSUE TITLE
feat(github-source): Make issues table incremental based on `updated` field

### ISSUE THREAD

**Issue by erezrokah** [cloudquery/cloudquery#17780]
Looks like we can sort issues by updated date ascending and filter by time:
https://github.com/google/go-github/blob/8d4be0b2cf2b8242a0b7e3777232cd0058ae535f/github/issues.go#L188

This should allow making the issues table incremental.

Went over other tables, didn't find another candidate

**Comment by duncanmapes** [comment]
This would be great. Assuming `github_action_runs` are already incremental?

**Comment by erezrokah** [comment]
> Assuming `github_action_runs` are already incremental?

We tried to make it incremental but since we can't sort the results it's not possible to make it incremental (we can't use a value to filter + sort, e.g. `create_at` then get all runs from a specific date).
However you can filter runs using a table option:

```yaml
spec:
    access_token: "${GITHUB_PERSONAL_ACCESS_TOKEN}"
    table_options:
      github_workflow_runs:
        created_since: '3 days ago'
```
