### ISSUE TITLE
bug: Oracle: missing defined_tags on oracle_compute_instances resource

### ISSUE THREAD

**Issue by gianluca-ava** [cloudquery/cloudquery#17831]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

cloudquery return {} on defined_tags attribute for oracle_compute_instances resource even the defined_tags are defined at source.

- [ ] 

### Expected Behavior

defined_tags returned as defined in Oracle

### CloudQuery (redacted) config

```yaml
kind: source
spec:
  # Source spec section
  name: drcc
  path: "cloudquery/oracle"
  version: "v4.3.5"
  tables: ["*"]
  skip_tables:
    - "oracle_compute_images"
    - "oracle_compute_vnic_attachments"
    - "oracle_virtualnetwork_fast_connect_provider_services"
    - "oracle_networkfirewall_network_firewall_policies"
    - "oracle_networkfirewall_network_firewalls"
    - "oracle_networkfirewall_work_requests"
    - "oracle_networkloadbalancer_work_requests"
    - "oracle_virtualnetwork_vlans"
  destinations: ["postgresql"] 
  spec:
    concurrency: 500
---
kind: destination
spec:
  name: "postgresql"
  path: "cloudquery/postgresql"
  version: "v7.1.5"
  spec:
    write_mode: "overwrite-delete-stale"
    connection_string: "postgresql://gamadm:${password}@${host}:${port}/${database}?sslmode=require"
```

### CloudQuery (redacted) logs

unuseful

### CloudQuery version

4.4.0

### Pull request (optional)

- [ ] I can submit a pull request
