### ISSUE TITLE
bug: Jira, not showing issue parentage

### ISSUE THREAD

**Issue by duncanmapes** [cloudquery/cloudquery#17908]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

  "customfield_10018": {
    "showField": false,
    "nonEditableReason": {
      "reason": "PLUGIN_LICENSE_ERROR",
      "message": "The Parent Link is only available to Jira Premium users."
    },
    "hasEpicLinkFieldDependency": false
  },

### Expected Behavior

show the parent of the issue

### CloudQuery (redacted) config

```yaml

kind: source
spec:
  name: "jira"
  path: "cloudquery/jira"
  registry: "cloudquery"
  version: "v1.4.1"
  destinations:
    - "postgresql"
  tables: ["*"]
  spec:
    base_url: "{{JIRA.BASE_URL}}"
    username: "{{JIRA.USERNAME}}"
    token: "{{JIRA.TOKEN}}"

```

### CloudQuery (redacted) logs

n/a

### CloudQuery version

v5.18.1

### Pull request (optional)

- [ ] I can submit a pull request
