### ISSUE TITLE
Unable to use incremental sync in local - failed to sync unmanaged client: failed to create state client: rpc error

### ISSUE THREAD

**Issue by Prabhanjali** [cloudquery/cloudquery#18039]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am using AWS Plugin 24.1.0, Postgresql version 7.0.0, AWS CLI is 5.20.1.
While trying to use a incremental sync for aws_inspector2_findings table, I am running into the below issues.

**Error:**
```
 unexpected error from sync client receive: rpc error: code = Unavailable desc = failed to sync records: failed to sync unmanaged client: failed to create state client: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp: address: too many colons in address"
```

### Expected Behavior

Incremental sync to work without error

### CloudQuery (redacted) config

source.yml
```
kind: source
spec:
  # Source spec section
  name: aws_xxxxxx
  path: cloudquery/aws
  version: "v24.1.0"
  tables: ["aws_inspector2_findings"]
  destinations: ["postgresql"]
  backend_options:
    table_name: "cq_state_aws"
    connection: "@@plugins.postgresql.connection"

```

postgresql.yml

```
kind: destination
spec:
  name: postgresql
  path: "cloudquery/postgresql"
  version: "v7.0.0"
  write_mode: "overwrite-delete-stale"
  migrate_mode: "forced"
  spec:
    connection_string: "xxxxxxxxxx"
```

### CloudQuery (redacted) logs

```
..
```

### CloudQuery version

5.20.1

### Pull request (optional)

- [ ] I can submit a pull request
