### ISSUE TITLE
bug: Unclear error message(s) when using the CLI without selecting a team

### ISSUE THREAD

**Issue by erezrokah** [cloudquery/cloudquery#18224]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When a user is a part of multiple teams, but runs `cloudquery login` without `cloudquery switch <team>` after to set the team, following commands error out with an unclear message:

```
Error: failed to get team name: failed to get team from config: failed to read config file: open /Users/<user>/Library/Application Support/cloudquery/config.json: no such file or directory
```

### Expected Behavior

The CLI should simply tell users the team is not set and they should run `cloudquery switch`

### CloudQuery (redacted) config

```yaml
kind: source
spec:
  name: "gcp"
  path: "cloudquery/gcp"
  version: "v14.0.0"
  destinations: ["postgresql"]
  tables: ["gcp_storage_buckets"]
  spec:
    project_ids: ["cq-playground"]
    concurency: 1
---
kind: destination
spec:
  name: "postgresql"
  path: "cloudquery/postgresql"
  version: "v8.0.4"
  migrate_mode: "forced"
  spec:
    connection_string: "postgresql://postgres:pass@localhost:5432/postgres?sslmode=disable"
```

### Steps To Reproduce

1. Onboard to https://cloud.cloudquery.io/teams/cloudquery and ensure you're a part of more than one team (create additional teams if needed)
2. Run `cloudquery login`, see the following console output:
```
Your current team is not set.

Teams available to you: <team-1>, <team-2>, ...

To set your current team, run `cloudquery switch <team>`

CLI successfully authenticated.
```

3. Run `cloudquery plugin install spec.yml`, and see error:
```
Loading spec(s) from examples/gcp-postgres.yml
Error: failed to get team name: failed to get team from config: failed to read config file: open /Users/<user>/Library/Application Support/cloudquery/config.json: no such file or directory
```

### CloudQuery (redacted) logs

NA

### CloudQuery version

5.21.3

### Pull request (optional)

- [X] I can submit a pull request
