### ISSUE TITLE
aws_costexplorer_cost_custom runs endless with a high number of results

### ISSUE THREAD

**Issue by birnemeier** [cloudquery/cloudquery#18539]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

running aws_costexplorer_cost_custom using a short time_period (2 month) with the config below works fine:

```
Loading spec(s) from .
Starting sync for: aws (cloudquery/aws@v27.7.0) -> [postgresql (cloudquery/postgresql@v8.2.3)]
Sync completed successfully. Resources: 63, Errors: 0, Warnings: 0, Time: 9s
```

doubling the time_period to 4 month it seems to never end and debug output always shows the same AWS API calls again and again (canceled after 4m24s).

```
Loading spec(s) from .
Starting sync for: aws (cloudquery/aws@v27.7.0) -> [postgresql (cloudquery/postgresql@v8.2.3)]
| Syncing resources... (2336/-, 8 resources/s) [4m24s] source plugin process failed with signal: killed
source plugin process failed with signal: killed
Error: failed to sync v3 source aws: unexpected error from sync client receive: rpc error: code = Canceled desc = context canceled
```

It looks to me that pagination ("NextPageToken") is not implemented or broken.

### Expected Behavior

Doubling the time_period should double the execution time (approximately of cause)

### CloudQuery (redacted) config

```
kind: source
spec:
  name: "aws"
  path: "cloudquery/aws"
  registry: "cloudquery"
  version: "v27.7.0"
  tables: [ "aws_organizations","aws_organizations_accounts","aws_costexplorer_cost_custom" ]
  destinations: [ "postgresql" ]
  spec:
    use_paid_apis: true
    enable_api_level_tracing: true
    aws_debug: true
    regions:
      - us-east-1
    table_options:
      aws_costexplorer_cost_custom:
        get_cost_and_usage:
          - time_period:
              start: "2024-06-01"
              end: "2024-07-01"
            filter:
              not:
                dimensions:
                  key: SERVICE
                  values:
                    - Tax
            granularity: MONTHLY
            group_by:
              - type: DIMENSION
                key: LINKED_ACCOUNT
              - type: DIMENSION
                key: SERVICE
            metrics:
              - NetUnblendedCost
              - UnblendedCost
              - NetAmortizedCost
              - AmortizedCost
```

### CloudQuery (redacted) logs

can be sent if needed, contains sensitive information

### CloudQuery version

cloudquery version 5.24.0

### Pull request (optional)

- [ ] I can submit a pull request
