### ISSUE TITLE
bug: aws_asset_inventory transform setting all regions as 'unavailable' in view 

### ISSUE THREAD

**Issue by mpatel-aops** [cloudquery/cloudquery#18710]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When running the aws_asset_inventory dbt transformation, the macro for postgres (haven't tested this with other destinations) always sets the region in the view to 'unavailable' even when there is a region column in the source table

### Expected Behavior

The view should only show 'unavailable' in the case where the source table does not have a region column.

### CloudQuery (redacted) config

dbt_profile.yml file:
```
version: 2.2.6
config-version: 2
profile: aws_asset_inventory
flags:
    send_anonymous_usage_stats: False
    use_colors: False
model-paths:
  - models
analysis-paths:
  - analyses
test-paths:
  - tests
seed-paths:
  - seeds
macro-paths:
  - macros
snapshot-paths:
  - snapshots
clean-targets:
  - target
  - dbt_packages
```

### Steps To Reproduce

1. Setup and run cloudquery with postgres destination and any table from the aws source plugin
2. Download and run the aws asset inventory transformation from the cloudquery site (https://hub.cloudquery.io/addons/transformation/cloudquery/aws-asset-inventory/latest/docs). As of this report, the latest version is v2.2.6
3. Check the corresponding view in postgres.   

### CloudQuery (redacted) logs

Result from dbt logs:
```
SELECT
_cq_id, _cq_source_name, _cq_sync_time,

SPLIT_PART(arn, ':', 5)
 AS account_id,

SPLIT_PART(arn, ':', 5)
 AS request_account_id,
CASE
WHEN SPLIT_PART(SPLIT_PART(arn, ':', 6), '/', 2) = '' AND SPLIT_PART(arn, ':', 7) = '' THEN NULL
ELSE SPLIT_PART(SPLIT_PART(arn, ':', 6), '/', 1)
END AS TYPE,
arn,

'unavailable'
 AS region,

'{}'::jsonb
 AS tags,
SPLIT_PART(arn, ':', 2) AS PARTITION,
SPLIT_PART(arn, ':', 3) AS service,
'aws_ec2_instances' AS _cq_table
FROM aws_ec2_instances

```

### CloudQuery version

cloudquery version 6.0.1

### Pull request (optional)

- [X] I can submit a pull request
