### ISSUE TITLE
bug: Stripe to S3 integration writing same row every run

### ISSUE THREAD

**Issue by MertAkyol7** [cloudquery/cloudquery#18916]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Stripe to S3 integration project by using Sqlite to save the state keeps writing the same 1 row of stripe charge everyday to S3 and doesn't update the state. In the initial run of the glue batch job, it wrote all of the data but after that the following days it writes only 1 same row of stripe charge every day instead of the charges data which hasn't been synced yet.

### Expected Behavior

I expect to get the charge data from Stripe since the last sync. In each run, it should append the new data since the last sync.

### CloudQuery (redacted) config

s3.yaml:

```
kind: destination
spec:
  name: "s3"
  path: "cloudquery/s3"
  version: "v4.10.0"
  write_mode: "append" 
  spec:
    bucket: "xxx"
    region: "eu-west-2"
    path: "raw_data/stripe_raw_data/{{TABLE}}/dt={{YEAR}}-{{MONTH}}-{{DAY}}/{{UUID}}.parquet"
    format: "parquet"
    athena: true

```
stripe.yaml:

```
kind: source
spec:
  name: "stripe"
  path: "cloudquery/stripe"
  version: "v2.1.11"
  registry: github
  tables: 
    - stripe_charges
  destinations: 
    - s3
  spec:
    api_key: ${STRIPE_TOKEN}
    rate_limit: 20
    incremental_sync: true
  backend_options:
    table_name: "cq_state_stripe"
    connection: "@@plugins.sqlite.connection"
```

sqlite.yaml:

```
kind: destination
spec:
  name: "sqlite"
  path: "cloudquery/sqlite"
  version: "v2.4.13"
  spec:
    connection_string: /cloudquery/state.sqlite
```

Dockerfile:

```
FROM ghcr.io/cloudquery/cloudquery:4.1

# Add AWS CLI without caching package index
RUN apk add --no-cache aws-cli

# Copy the cloudquery directory
COPY cloudquery /cloudquery

# Set the entry point to the run.sh script
ENTRYPOINT [ "" ]
```

run.sh:

```
#!/bin/sh
set -ex

aws --version
/app/cloudquery --version

aws s3 cp s3://xxx/state/cloudquery-stripe-extraction-state.sqlite /cloudquery/state.sqlite || { 
    echo "No state found. Assuming first execution to extract everything" 
}

# Sync CloudQuery plugins
/app/cloudquery sync /cloudquery/stripe.yaml /cloudquery/s3.yaml /cloudquery/sqlite.yaml 



aws s3 cp /cloudquery/state.sqlite s3://xxx/state/cloudquery-stripe-extraction-state.sqlite
```

### CloudQuery (redacted) logs

<html>
<body>

+ aws --version
--
aws-cli/2.15.14 Python/3.11.8 Linux/4.14.348-265.565.amzn2.x86_64 exec-env/AWS_ECS_EC2 source/x86_64.alpine.3 prompt/off
+ /app/cloudquery --version
cloudquery version 4.1.2
+ aws s3 cp s3://xxx/state/cloudquery-stripe-extraction-state.sqlite /cloudquery/state.sqlite
Completed 12.0 KiB/12.0 KiB (208.3 KiB/s) with 1 file(s) remainingdownload: s3://xxx/state/cloudquery-stripe-extraction-state.sqlite to ../cloudquery/state.sqlite
+ /app/cloudquery sync /cloudquery/stripe.yaml /cloudquery/s3.yaml /cloudquery/sqlite.yaml
Loading spec(s) from /cloudquery/stripe.yaml, /cloudquery/s3.yaml, /cloudquery/sqlite.yaml
Downloading https://github.com/cloudquery/cloudquery/releases/download/plugins-source-stripe-v2.1.11/stripe_linux_amd64.zip
Downloading   0% \|                                      \| ( 0 B/8.0 MB) [0s:0s]                                                                               Downloading 100% \|█████████████████████████████\| (8.0/8.0 MB, 370 MB/s)
Downloading https://assets.cloudquery.io/cq-cloud-releases/cloudquery/destination/s3/v4.10.0/linux_amd64
Downloading   0% \|                                       \| ( 0 B/14 MB) [0s:0s]                                                                               Downloading  49% \|███████████████                \| (7.1/14 MB, 94 MB/s) [0s:0s]                                                                               Downloading  94% \|██████████████████████████████  \| (14/14 MB, 95 MB/s) [0s:0s]                                                                               Downloading 100% \|████████████████████████████████\| (14/14 MB, 96 MB/s)
Downloading https://assets.cloudquery.io/cq-cloud-releases/cloudquery/destination/sqlite/v2.4.13/linux_amd64
Downloading   0% \|                                       \| ( 0 B/11 MB) [0s:0s]                                                                               Downloading  50% \|███████████████                \| (5.5/11 MB, 83 MB/s) [0s:0s]                                                                               Downloading 100% \|████████████████████████████████\| (11/11 MB, 86 MB/s)
Starting sync for: stripe (v2.1.11) -> [s3 (cloudquery@cloudquery/s3)]
/ Syncing resources... (0/-, 0 resources/hr) [0s]                                                   - Syncing resources... (0/-, 0 resources/hr) [0s]                                                   \ Syncing resources... (1/-, 3 resources/s) [0s]                                                   Sync completed successfully. Resources: 1, Errors: 0, Warnings: 0, Time: 0s
+ aws s3 cp /cloudquery/state.sqlite s3://xxx/state/cloudquery-stripe-extraction-state.sqlite
Completed 12.0 KiB/12.0 KiB (199.0 KiB/s) with 1 file(s) remainingupload: ../cloudquery/state.sqlite to s3://xxx/state/cloudquery-stripe-extraction-state.sqlite

</body>
</html>

### CloudQuery version

4.1.2

### Pull request (optional)

- [ ] I can submit a pull request
