### ISSUE TITLE
bug: AWS -> S3 and then S3 -> PostgreSQL doesnt work

### ISSUE THREAD

**Issue by gala-neosec** [cloudquery/cloudquery#19024]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm trying to export AWS EC2 instances to S3 and then from S3 to PostgreSQL and it doesn't work

### Expected Behavior

I expect it to work seamlessly as it works in AWS -> PostgreSQL.

### CloudQuery (redacted) config

aws source
```
kind: source
spec:
  name: aws-test
  path: cloudquery/aws
  registry: cloudquery
  version: "v27.16.0"
  tables: ['aws_ec2_instances']
  destinations: ["s3"]
  spec:
    aws_debug: false
    accounts:
      - account_name: "****"
    regions:
      - 'us-east-1'
```
s3 destination
```
kind: destination
spec:
  name: "s3"
  path: "cloudquery/s3"
  registry: "cloudquery"
  version: "v7.4.3"
  write_mode: "append"
  spec:
    bucket: "test"
    region: "us-east-1" # Example: us-east-1
    path: "{{TABLE}}/{{UUID}}.{{FORMAT}}"
    format: "parquet" # options: parquet, json, csv
```

s3 source
```
kind: source
spec:
  name: s3

  path: cloudquery/s3
  registry: cloudquery
  version: "v1.3.11"
  tables: ["*"]
  destinations: ["postgresql"]

  spec:
    # TODO: Update it with the actual spec
    bucket: "test"
    region: "us-east-1"
```

PostgreSQL destination
```
kind: destination
spec:
  name: "postgresql"
  path: "cloudquery/postgresql"
  registry: "cloudquery"
  version: "v8.5.3"
  write_mode: "overwrite-delete-stale"
  spec:
    connection_string: "${POSTGRESQL_CONNECTION_STRING}" 
```

### Steps To Reproduce

1. run `cloudquery sync aws_config_s3.yaml s3_destination.yaml`
2. run `cloudquery sync s3_source.yaml postgres.yaml`

### CloudQuery (redacted) logs

```
Loading spec(s) from s3_source.yaml, postgres.yaml
Starting sync for: s3 (cloudquery/s3@v1.3.11) -> [postgresql (cloudquery/postgresql@v8.5.3)]
| Syncing resources... (120/-, 0 resources/hr) [2s] Error: failed to sync v3 source s3: rpc error: code = Internal desc = write failed: table name not found in metadata
\ Syncing resources... (120/-, 27 resources/s) [2s] %
```

### CloudQuery version

cloudquery version 6.4.1

### Pull request (optional)

- [ ] I can submit a pull request

**Comment by liadt-neosec** [comment]
In addition to that, I found the same error reproduce with file plugin, so I assume its related to parquet file.
I created file_source.yaml file:
```
kind: source
spec:
  name: file
  path: cloudquery/file
  registry: cloudquery
  version: "v1.4.6"
  tables: ["*"]
  destinations: ["postgresql"]

  spec:
    files_dir: "lambda_test/path/to/files/aws_ec2_vpcs/"
    # Optional parameters
    # rows_per_record: 500
    # concurrency: 50
```

postgres_destination.yaml configuration file:
```
kind: destination
spec:
  name: "postgresql"
  path: "cloudquery/postgresql"
  registry: "cloudquery"
  version: "v8.5.3"
  write_mode: "overwrite-delete-stale"
  spec:
    connection_string: "${POSTGRESQL_CONNECTION_STRING}"
```


then ran a sync between file source into postgres:
`cloudquery sync file_source.yaml postgres_destination.yaml --cq-dir /tmp/`


and I seem to get simillar error:
```
$ cloudquery sync file_source.yaml postgres_destination.yaml --cq-dir /tmp/
Loading spec(s) from file_source.yaml, postgres_destination.yaml
Starting sync for: file (cloudquery/file@v1.4.6) -> [postgresql (cloudquery/postgresql@v8.5.3)]
| Syncing resources... (4/-, 10 resources/s) [0s] Error: failed to sync v3 source file: rpc error: code = Internal desc = write failed: table name not found in metadata
| Syncing resources... (4/-, 3 resources/s) [1s] %     
```
