### ISSUE TITLE
bug: OCI db_systems are missing

### ISSUE THREAD

**Issue by MohamedMSaeed** [cloudquery/cloudquery#19028]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I enabled oracle_database_* tables but I can't find the DBs from OCI listed in any table. All are empty.

### Expected Behavior

Get all of DBs scraped from OCI.

When I run the following command I can get the list.
```
oci mysql db-system list --compartment-id ${COMPARTMENT_ID} --region ${REGION} --all
```

### CloudQuery (redacted) config

```
kind: source
spec:
  name: "oracle"
  path: cloudquery/oracle
  registry: cloudquery
  version: "v7.2.4"
  destinations: ["postgres-devops-port-forward"]
  tables:
    - "oracle_database_*"
  # Learn more about the configuration options at https://cql.ink/oracle_source
  spec:
    # Optional parameters
    # concurrency: 10000
```

### CloudQuery (redacted) logs

will be provided separately

### CloudQuery version

cloudquery version 6.2.0

### Pull request (optional)

- [ ] I can submit a pull request
