### ISSUE TITLE
Change gen command

### ISSUE THREAD

**Issue by yevgenypats** [cloudquery/cloudquery#1945]
While working on our documentation I found a few inefficiencies in the `gen` command and plugin documentation:

gen command is doing few things:
1) finding latest version
2) downloading the latest version
3) generating main source or dest spec with name plugin and the latest pinned version
4) dumping huge block of documentation into spec from the specific soruce or dest plugin

I think we should remove  step number 4 and just link to the documentation. This should ensure number of things.

Empty spec still should work in most cases where we have good defaults, so the dev workflow of `gen` && `sync` should work.

We wont need to maintain both documentation and example and make sure it's up to date + support protocol changes + have various issues with yaml in case the source plugin implemented that incorrectly.

Right now step number 4 is backward because we have very little documentation but we've put the documentation that we have into a file inside a plugin which very hard to find rather then starting with basic documentation.

So basically my suggestion is the following:
keep the `gen` command and just output the main config like this:

```
kind: "source"
spec:
  # Name of the plugin.
  name: "aws"

  # Version of the plugin to use.
  version: "v1.1.4"

  # Registry to use (one of "github", "local" or "grpc").
  registry: "github"

  # Path to plugin. Required format depends on the registry.
  path: "cloudquery/aws"

  # List of tables to sync.
  tables: ["*"]

  ## Tables to skip during sync. Optional.
  # skip_tables: []

  # Names of destination plugins to sync to.
  destinations: ["postgresql"]

  ## Approximate cap on number of requests to perform concurrently. Optional.
  # concurrency: 5

  # Plugin-specific configuration.
  spec:
      # Check documentation here: https://github.com/cloudquery/cloudquery/tree/main/plugins/source/aws
```

we can also discuss this tmrw live
