### ISSUE TITLE
feat(transformer-basic): Ability to filter and/or obfuscate data in JSON columns

### ISSUE THREAD

**Issue by erezrokah** [cloudquery/cloudquery#19496]
### Which problem is this feature request solving?

Extracted from https://github.com/cloudquery/cloudquery/issues/6388#issuecomment-2435224444

Our [basic](https://github.com/cloudquery/cloudquery/tree/main/plugins/transformer/basic) transformer can only remove columns, or obfuscate string columns. It would be good to support JSON columns fields too.

### Describe the solution you'd like

The config could look like this maybe:

```yaml
kind: transformer
spec:
  name: "basic"
  path: "cloudquery/basic"
  version: v1.1.5
  spec:
    transformations:
      - kind: obfuscate_columns
        tables: ["table_with_json_column_named_properties"]
        columns: ["properties.id"]
      - kind: remove_columns
        tables: ["table_with_json_column_named_properties"]
        columns: ["properties.name"]
 ```

### Pull request (optional)

- [ ] I can submit a pull request
