### ISSUE TITLE
bug: line_items missing from shopify_orders table in Shopify Plugin

### ISSUE THREAD

**Issue by konung** [cloudquery/cloudquery#19639]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

line_items jsonb field is no longer present in shopify_orders. But it was present in previous versions of the plugins. I'm migrating from  Shopify 3.21 to cloudquery/shopify@v8.3.2. 

A bunch of my reports are failing ,because line_items is no longer part of the shopify_orders table 

### Expected Behavior

line_items should be present. It's part of Shopify GraphQL spec , and it arguably one of the most important pieces of information about order - what was actually sold and how much per line.  Other items are present like shipping_lines and tax_lines and discount_lines, but not line_items. 

https://shopify.dev/docs/api/admin-graphql/2024-10/objects/LineItem

### CloudQuery (redacted) config

```yaml

kind: destination
spec:
  name: "postgresql-shopify"
  path: "cloudquery/postgresql"
  version: "v8.6.7"
  write_mode: "overwrite-delete-stale" # overwrite-delete-stale, overwrite, append
  spec:
    connection_string: "${POSTGRES_CONNECTION_STRING}&search_path=cq_shopify"


```

```yaml
kind: source
spec:
  name: shopify
  path: cloudquery/shopify
  version: "v8.3.2"
  tables: [ "*"]
  destinations: ["postgresql-shopify"]
  backend_options:
    table_name: "shopify_postgres_state"
    connection: "@@plugins.postgresql-shopify.connection"
  spec:
    shop_url: "https://${SHOPIFY_STORE_NAME}.myshopify.com"
    access_token: "${SHOPIFY_ACCESS_TOKEN}"
    concurrency: 1000

```

### CloudQuery (redacted) logs

no logs

### CloudQuery version

 6.11.2

### Pull request (optional)

- [ ] I can submit a pull request
