### ISSUE TITLE
feat: Add WHERE clause support for MySQL source plugin

### ISSUE THREAD

**Issue by KadyrbekAnalyst** [cloudquery/cloudquery#19874]
### Which problem is this feature request solving?

I would like to implement incremental data loading from MySQL tables without creating additional views or external scripts. Currently, the MySQL source plugin doesn't support filtering data using WHERE conditions in the configuration, which leads to full table scans every time. This causes unnecessary load on the source database and increases network traffic, especially when dealing with large tables where we only need to sync new or updated records.

### Describe the solution you'd like

This could be resolved by adding support for WHERE clause in the MySQL source plugin configuration, similar to how custom queries work in other plugins. 

Proposed configuration syntax:

```yaml
kind: source
spec:
  name: mysql
  path: cloudquery/mysql
  registry: cloudquery
  version: "v4.5.1"
  destinations: ["postgresql"]
  tables: ["my_table"]
  spec:
    connection_string: "..."
    table_options:
      - table: "my_table"
        where: "id > 1000000"  # New feature
```

Benefits:
1. Efficient incremental loading based on ID or timestamp
2. Reduced load on source databases
3. Lower network traffic
4. No need for temporary views or external scripts
5. Better performance for large table synchronization

This feature would significantly improve the efficiency of data synchronization processes, especially for large-scale incremental data loading scenarios.

### Pull request (optional)

- [ ] I can submit a pull request
