### ISSUE TITLE
bug: transformer plugin - add_column produces nullable field

### ISSUE THREAD

**Issue by jeromewir** [cloudquery/cloudquery#20026]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When using the [basic transformer](https://hub.cloudquery.io/plugins/transformer/cloudquery/basic/latest/docs) with `add_column` feature, the added field is a nullable string

### Expected Behavior

Since the spec [requires a value](https://github.com/cloudquery/cloudquery/blob/1b2b19be4053acc65d1c97652612c755866f544e/plugins/transformer/basic/client/spec/spec.go#L51), I would expect the added field to be non-nullable

I believe ~~(I have not tested)~~ that flipping [this boolean](https://github.com/cloudquery/cloudquery/blob/1b2b19be4053acc65d1c97652612c755866f544e/plugins/transformer/basic/client/recordupdater/record_updater.go#L99) to false would produce the expected behavior.

Edit: I tested a modified version of the basic transformer and this does produce a non-nullable field

### CloudQuery (redacted) config

```
kind: source
spec:
  name: sentinelone
  path: cloudquery/sentinelone
  registry: cloudquery
  version: "v1.11.0"
  tables: ["*"]
  destinations: ["postgres"]
  skip_dependent_tables: true
  spec:
    # required
    api_token: "${SENTINELONE_API_TOKEN}"
    # required
    management_url: "https://${SENTINELONE_MANAGEMENT_HOST}/"

---

kind: destination
spec:
  name: postgres
  path: cloudquery/postgresql
  registry: cloudquery
  version: "v8.7.5"
  spec:
    connection_string: ${PG_CONNECTION_STRING}
  transformers:
    - "basic"

---

kind: transformer
spec:
  name: "basic"
  registry: "cloudquery"
  path: "cloudquery/basic"
  version: v1.3.4
  spec:
    transformations:
      - kind: add_column
        tables: ["*"]
        name: "my_custom_field"
        value: "a_custom_string"
```

### Steps To Reproduce

- Run a sync with any source and the basic plugin

### CloudQuery (redacted) logs

No related logs

### CloudQuery version

6.12.9

### Additional Context

I might be missing some context about why this is like this.
If it's expected, is there any way to add a non-nullable field?

Thanks!

### Pull request (optional)

- [X] I can submit a pull request
