### ISSUE TITLE
bug: JSONFlattener incorrectly handles casing for `Tls`

### ISSUE THREAD

**Issue by bbernays** [cloudquery/cloudquery#20192]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

Currently because we normalize between cases snake and pascal, we turn `minimumTlsVersion` --> `minimum_tls_version` --> `minimumTLSVersion`

This means that when we are updating records the value for that column is always nil because the name doesn't match

### Expected Behavior

We should never drop values

### CloudQuery (redacted) config

```yaml
kind: source
spec:
  name: "azure-tls"
  path: "cloudquery/azure"
  registry: "cloudquery"
  version: "v17.1.2"
  destinations: ["postgresql"]
  tables: [
    # "azure_appservice_web_app_configurations",
    # "azure_cosmos_database_accounts",
    # "azure_eventhub_namespaces",
    # "azure_hdinsight_clusters",
    # "azure_mariadb_servers",
    # "azure_mysql_servers",
    # "azure_postgresql_servers",
    # "azure_redis_caches",
    # "azure_sql_managed_instances",
    # "azure_sql_servers",
    "azure_storage_accounts"
]
  spec:
    concurrency: 500

---
kind: transformer
spec:
  name: "jsonflattener"
  path: "cloudquery/jsonflattener"
  # registry: "grpc"
  # path: "localhost:7777"
  version: v2.0.2
  spec:
    tables: ["*"]

---
kind: destination
spec:
  name: "postgresql"
  path: "cloudquery/postgresql"
  registry: "cloudquery"
  version: "v8.7.8"
  migrate_mode: "forced"
  spec:
    connection_string: "postgresql://postgres:pass@localhost:5432/postgres?sslmode=disable"
  transformers:
    - "jsonflattener"

```

### CloudQuery (redacted) logs

NA

### CloudQuery version

all

### Pull request (optional)

- [x] I can submit a pull request
