### ISSUE TITLE
bug: Azure plugin documentation provides invalid options for cloud_name

### ISSUE THREAD

**Issue by ukbe** [cloudquery/cloudquery#20445]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

THe Azure plugin documentations provides options below for `cloud_name` spec setting.
- AzureCloud
- AzureChinaCloud
- AzureGovernment

However we get error below if we use `AzureCloud` option.
```
error: code = Internal desc = failed to init plugin: failed to initialize client: unknown Azure cloud name 'AzureCloud'. Supported values are ['AzurePublic', 'AzureGovernment', 'AzureChina']." 
```

### Expected Behavior

The documentation should provide the correct options for `cloud_name``

- AzurePublic
- AzureGovernment'
- AzureChina

### CloudQuery (redacted) config

```yaml
kind: source
spec:
  name: ABC..

  path: cloudquery/azure
  registry: cloudquery
  version: "v15.4.0"

  # Required. all destinations you want to sync data to.
  destinations: ["postgres"]

  # https://hub.cloudquery.io/plugins/source/cloudquery/azure/latest/docs#configuration
  spec:
    subscriptions:
      - "${SUBSCRIPTION_ID}"
    cloud_name: ${AZURE_CLOUD_NAME}
```

### CloudQuery (redacted) logs

```
error: code = Internal desc = failed to init plugin: failed to initialize client: unknown Azure cloud name 'AzureCloud'. Supported values are ['AzurePublic', 'AzureGovernment', 'AzureChina']." 
```

### CloudQuery version

6.17.0

### Pull request (optional)

- [ ] I can submit a pull request
