### ISSUE TITLE
GCP Policy: missing view in CIS 1.2.0 Section 5 

### ISSUE THREAD

**Issue by SCKelemen** [cloudquery/cloudquery#2524]
GCP CIS 1.2.0 Policy broken
Missing view `gcp_storage_bucket_policies`

```sql
CREATE OR REPLACE VIEW gcp_public_buckets_accesses AS
WITH project_policy_roles AS (SELECT p.project_id,
                                     p.name,
                                     CASE WHEN p.name like '%.appspot.com' THEN 'https://'||p.name ELSE 'https://' || p.name || '.storage.googleapis.com' END AS self_link,
                                     jsonb_array_elements(pp.bindings) AS binding
                              FROM gcp_storage_buckets p LEFT JOIN gcp_storage_bucket_policies pp ON pp.project_id=p.project_id AND pp.bucket_name=p.name
     ),
     role_members AS (SELECT project_id,
                             name,
                             self_link,
                             binding ->> 'role'                              AS "role",
                             jsonb_array_elements_text(binding -> 'members') AS MEMBER
                      FROM project_policy_roles)
SELECT project_id, name, self_link, "role", MEMBER
FROM role_members;
```

CloudQuery version 1.0.5
GCP Source Version 1.0.0
PSQL Destination Version 0.3.0

```
cloudquery sync gcp.yaml psql.yaml
psql -U postgres -h localhost -f plugins/source/gcp/policies_v1/create_gcp_policy_results.sql
psql -U postgres -h localhost -f plugins/source/gcp/policies_v1/cis_v1.2.0/policy.sql
```

`gcp.yaml`:
```yaml
kind: source
spec:
  name: gcp
  version: "v1.0.0"
  destinations: ["postgresql"]
```

`psql.yaml`:
```yaml
kind: destination
spec:
  name: "postgresql"
  version: "v0.3.0"
  write_mode: "overwrite" # overwrite, append
  spec:
    connection_string: "postgresql://postgres:pass@localhost:5432/postgres?sslmode=disable"```
```
