### ISSUE TITLE
Investigation request:  Usage of `AWS_WEB_IDENTITY_TOKEN_FILE` with the AWS plugin 

### ISSUE THREAD

**Issue by erezrokah** [cloudquery/cloudquery#3009]
[Reported on Discord](https://discord.com/channels/872925471417962546/873606591335759872/1032068002587361360).

We should investigate if the `AWS_WEB_IDENTITY_TOKEN_FILE` should work, and fix it if it doesn't or document that it shouldn't 🙃

**Comment by bbernays** [comment]
I have confirmed that in our EKS cluster `cloudquery/aws v3.2.1` is able to utilize `AWS_WEB_IDENTITY_TOKEN_FILE` for sourcing the credentials:

we use the following configuration for the test:
```
kind: source
spec:
  name: aws-0
  registry: github
  path: cloudquery/aws
  version: v3.4.1
  tables: 
    - "*"
  destinations: ["postgresql"]
  spec:
    accounts:
      - id: "cloudquery-account-1"
        role_arn: "arn:aws:iam::[ACCOUNT-1]:role/CloudQueryFetchRole"
        role_session_name: "cloudquery-irsa"
      - id: "cloudquery-account-2"
        role_arn: "arn:aws:iam::[ACCOUNT-2]:role/CloudQueryFetchRole"
```

In the shell it has the following AWS environment variables set:
```
AWS_ROLE_ARN=arn:aws:iam::[REDACTED]:role/cloudquery-complete-example-eksa-irsa
AWS_WEB_IDENTITY_TOKEN_FILE=/var/run/secrets/eks.amazonaws.com/serviceaccount/token
AWS_DEFAULT_REGION=us-east-1
AWS_STS_REGIONAL_ENDPOINTS=regional
AWS_REGION=us-east-1
 ```

 `AWS_DEFAULT_REGION`,`AWS_STS_REGIONAL_ENDPOINTS` and `AWS_REGION` are optional variables
 
I can also confirm that when the role associated with the pod (in our case `arn:aws:iam::[REDACTED]:role/cloudquery-complete-example-eksa-irsa`) doesn't have the IAM permissions to assume the target roles (`arn:aws:iam::[ACCOUNT-1]:role/CloudQueryFetchRole and arn:aws:iam::[ACCOUNT-2]:role/CloudQueryFetchRole`) there are log messages that indicate this:
```
failed to refresh cached credentials, operation error STS: AssumeRole, https response error StatusCode: 403, RequestID: <UUID>, api error AccessDenied: User: arn:aws:sts::[ACCOUNT-0]:assumed-role/cloudquery-complete-example-eksa-irsa/cloudquery-irsa is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::[ACCOUNT-1]:role/CloudQueryFetchRole
```

and

```
failed to refresh cached credentials, operation error STS: AssumeRole, https response error StatusCode: 403, RequestID: <UUID>, api error AccessDenied: User: arn:aws:sts::[ACCOUNT-0]:assumed-role/cloudquery-complete-example-eksa-irsa/1666204988554762814 is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::[ACCOUNT-2]:role/CloudQueryFetchRole
```
