### ISSUE TITLE
digitalocean plugin is broken

### ISSUE THREAD

**Issue by shimonp21** [cloudquery/cloudquery#3428]
### Describe the Bug
Panics, and empty database after `cloudquery sync`.

```
export DIGITALOCEAN_ACCESS_TOKEN="<...>"
~/projects/cqdo % cloudquery sync .
Loading spec(s) from .
Starting migration for: digitalocean -> [postgresql]
Migration completed successfully.
Starting sync for: digitalocean -> [postgresql]
Sync completed successfully.
Summary: resources: 493, errors: 2, panic: 2, failed_writes: 0, time: 8s
```

### CloudQuery Version
`cloudquery: v1.4.0`
`digitalocean: v2.1.0`
`postgresql: v1.3.11`

### Steps to Reproduce
`digitalocean.yml`:

```yml
kind: source
spec:
  name: digitalocean
  path: cloudquery/digitalocean
  version: "v2.1.0" # latest version of digitalocean plugin
  tables: ["*"]
  destinations: ["postgresql"]

  spec:
```
