### ISSUE TITLE
feat(plugin-csv): Use `append` `write-mode` as CSV plugin default

### ISSUE THREAD

**Issue by erezrokah** [cloudquery/cloudquery#3484]
Could be considered a bug, but logging this as a feature instead.

The only `write-mode` that works for the CSV plugin is `append`, but our default is `overwrite-delete-stale`.

This means the following configuration fails:

```yml
kind: source
spec:
  name: aws
  path: cloudquery/aws
  version: "v4.1.0" # latest version of aws plugin
  tables: ["*"]
  destinations: ["csv"]
---
kind: destination
spec:
  name: csv
  path: cloudquery/csv
  version: "v1.0.0" # latest version of csv plugin
```

And users need to add `write_mode: "append"` to make it work (making it a required field).

We could either support different defaults for different plugins, or put the `write-mode` under plugin `spec` as it seems to be destination specific.
