### ISSUE TITLE
Support Syncing Multiple Azure Tenants in a single config

### ISSUE THREAD

**Issue by bbernays** [cloudquery/cloudquery#3551]
### Is your feature request related to a problem? Please describe.

Currently Azure source plugin grabs the credentials from the environment variables. This means that single config can only ever grab from a single tenant. 

### Describe the solution you'd like

Rather than grabbing the `Tenant_id`, `Client_id` and `Client_secret` from a single place enable users to hard code in the config file or use environment variable substituion

**Comment by alanjoseuk** [comment]
It would be great if the source config file for azure could accept the tenant_id, client_id and client_secret rather than passing them as environment variables. For example:

```
---
kind: source
spec:
  name: "azure"
  path: "cloudquery/azure"
  version: "v1.3.0"
  destinations:
    - postgresql

  spec:
     - tenant_id: <tenant-id>
       client_id: <client-id>
       client_secret: <client-secret>
       subscriptions: []
```
