### ISSUE TITLE
skip tables does not work

### ISSUE THREAD

**Issue by jimr6007** [cloudquery/cloudquery#3610]
### Describe the Bug
setup your stuffs like this
```
data:
  aws-src.yml: |
    kind: source
    spec:
      name: aws
      version: "v4.5.0"
      destinations: ["postgresql"]
      tables: ["*"]
      skip_tables: ["aws_ecs_task_defintions"]
```
kick of a run and note that aws_ecs_task_defintions is not being skipped

watch the logs

do a 
```select count(_cq_id) from aws_ecs_task_definitions;```

periodically, and note that the number of rows in the table is growing

I had suspected this for a while now but decided to absolutely confirm today

### Expected Behavior
the table is skipped

### CloudQuery Version
cli 1.5.3
pg dest 1.6.1
aws src 4.5.0

### Debug Output

N/A

### Steps to Reproduce

config CQ as mentioned ^^^
run your sync
watch the aws_ecs_task_defintions table while sync is in progress and note that the number of records in the table is increasing
