### ISSUE TITLE
feat(CLI): The CLI should verify all plugins use the same gRPC protocol version

### ISSUE THREAD

**Issue by erezrokah** [cloudquery/cloudquery#3628]
## Problem

Given the following configuration:

```yml
kind: source
spec:
  name: aws
  version: v3.8.0
  destinations: [postgresql]
  path: cloudquery/aws
---
kind: destination
spec:
  name: postgresql
  version: v1.6.0
  spec:
    connection_string: postgresql://postgres:pass@localhost:5432/postgres
```

The CLI fails with a confusing error:

```bash
Starting migration for: aws -> [postgresql]
Migration completed successfully.
Starting sync for: aws -> [postgresql]
Error: failed to write for aws->postgresql: failed to call Write.Send: EOF
exit status 1
```

The reason is that the AWS plugin in the config uses protocol version 1, while the PostgreSQL plugin uses version 2.

## Proposed solution

The CLI should verify all plugins use the same protocol version and if not prompt users to update the relevant ones
