### ISSUE TITLE
panic: table not found errors

### ISSUE THREAD

**Issue by asvinours** [cloudquery/cloudquery#4489]
### Describe the Bug
<!-- try to elaborate as much as you can on the bug and the behaviour -->

I am trying to do a PoC with CloudQuery, but I am facing an issue with the postgres destination plugin.
Whenever I run "cloudquery sync" command, it throws an error about tables not found.

It's not always the same table, it changes, and every time I checked, that table actually exists in the DB.
The migration log output also shows the table exists.

Example:
```shell
$ cloudquery sync configs/ --log-level debug
Loading spec(s) from configs/
Starting migration for: aws -> [postgresql]
Migration completed successfully.
Starting sync for:  aws -> [postgresql]
\ Syncing resources... (243/-, 105 resources/s) [1s] panic: table aws_cloudformation_stack_resources not found
                                                      
goroutine 1322 [running]:
0xc000379fd0?)                                        x2?}, com/cloudquery/cloudquery/plugins/destination/postgresql/client.(*Client).Write(0xc0000b8200, 
\ Syncing resources... (246/-, 105 resources/s) [1s] :30 +0x5a5tion/postgresql/client/write.go
github.com/cloudquery/plugin-sdk/plugins.(*DestinationPlugin).Write.func1()
                                                      plugin-sdk@v1.5.0/plugins/destination.go:145 +0x42
golang.org/x/sync/errgroup.(*Group).Go.func1()
\ Syncing resources... (247/-, 105 resources/s) [1s] /home/runner/go/pkg/mod/golang.org/x/sync@v0.1.0/errgroup/errgroup.go:75 +0x64
created by golang.org/x/sync/errgroup.(*Group).Go
        /home/runner/go/pkg/mod/golang.org/x/sync@v0.1.0/errgroup/errgroup.go:72 +0xa5
failed to terminate destination client:  destination plugin process exited with status exit status 2
Error: failed to write for aws->postgresql: failed to call Write2.Send: EOF
```

<details><summary>More error examples</summary>

```text
panic: table aws_lambda_function_versions not found                                                                                                                               
                                                                                                                                                                                  
goroutine 1318 [running]:                                                                                                                                                         
github.com/cloudquery/cloudquery/plugins/destination/postgresql/client.(*Client).Write(0xc0001c8200, {0xcc9208, 0xc00027b280}, {0xc0001d5500, 0x129, 0x3?}, 0xc0002847d0?)        
        /home/runner/work/cloudquery/cloudquery/plugins/destination/postgresql/client/write.go:30 +0x5a5                                                                          
github.com/cloudquery/plugin-sdk/plugins.(*DestinationPlugin).Write.func1()                                                                                                       
        /home/runner/go/pkg/mod/github.com/cloudquery/plugin-sdk@v1.5.0/plugins/destination.go:145 +0x42                                                                          
golang.org/x/sync/errgroup.(*Group).Go.func1()                                                                                                                                    
        /home/runner/go/pkg/mod/golang.org/x/sync@v0.1.0/errgroup/errgroup.go:75 +0x64                                                                                            
created by golang.org/x/sync/errgroup.(*Group).Go                                                                                                                                 
        /home/runner/go/pkg/mod/golang.org/x/sync@v0.1.0/errgroup/errgroup.go:72 +0xa5                                                                                            
2022-11-13T16:05:02Z ERR Failed to terminate destination client error="destination plugin process exited with status exit status 2" module=cli
```

```text
panic: table aws_docdb_cluster_parameters not found

goroutine 1309 [running]:
github.com/cloudquery/cloudquery/plugins/destination/postgresql/client.(*Client).Write(0xc0001d0200, {0xcc9208, 0xc000215280}, {0xc000166000, 0x129, 0x6f6974707972636e?}, 0xc0001487d0?)
        /home/runner/work/cloudquery/cloudquery/plugins/destination/postgresql/client/write.go:30 +0x5a5
github.com/cloudquery/plugin-sdk/plugins.(*DestinationPlugin).Write.func1()
        /home/runner/go/pkg/mod/github.com/cloudquery/plugin-sdk@v1.5.0/plugins/destination.go:145 +0x42
golang.org/x/sync/errgroup.(*Group).Go.func1()
        /home/runner/go/pkg/mod/golang.org/x/sync@v0.1.0/errgroup/errgroup.go:75 +0x64
created by golang.org/x/sync/errgroup.(*Group).Go
        /home/runner/go/pkg/mod/golang.org/x/sync@v0.1.0/errgroup/errgroup.go:72 +0xa5
2022-11-13T16:11:37Z ERR Failed to terminate destination client error="destination plugin process exited with status exit status 2" module=cli
2022-11-13T16:11:37Z ERR table resolver finished with error error="operation error WAFV2: ListIPSets, https response error StatusCode: 0, RequestID: , canceled, context canceled" client=595861543079:us-east-1::REGIONAL module=aws-src table=aws_wafv2_ipsets
Error: failed to write for aws->postgresql: failed to call Write2.Send: EOF
2022-11-13T16:11:37Z ERR exiting with error error="failed to write for aws->postgresql: failed to call Write2.Send: EOF" module=cli
```

</details>

### Expected Behavior
<!--
What should have happened?
-->

Sync command should complete successfully if the table exists and not throw a table not found error


### CloudQuery Version

```shell
$ cloudquery --version
cloudquery version 2.0.13
```

Source plugin: AWS, version `4.15.1`
Destination plugin: postgresql, version `1.7.8`

### Debug Output
<!--
Full debug output can be obtained by running `cloudquery --log-console --log-level debug`

Debug logs may contain sensitive information. Please review and censor it before posting publicly.
-->

[cloudquery.log](https://github.com/cloudquery/cloudquery/files/9997758/cloudquery.log)


### Steps to Reproduce

<details>
<summary>Source configuration</summary>

```yaml
---
kind: source
spec:
  name: "aws"
  path: "cloudquery/aws"

  version: "v4.15.1"
  tables: ["*"]
  destinations: ["postgresql"]

  spec:
    aws_debug: false
    regions:
      - us-east-1
    accounts:
      - id: "identity"
        local_profile: "main-identity"
```

</details>

<details>
<summary>Destination configuration</summary>

```yaml
---
kind: destination
spec:
  name: "postgresql"
  path: "cloudquery/postgresql"

  version: "v1.7.8"
  write_mode: "overwrite-delete-stale"

  spec:
    # pgx_log_level: debug
    connection_string: postgresql://postgres:mysecretpassword@postgres:5432/cloudquery?sslmode=disable
```

</details>

<details>
<summary>Docker compose configuration</summary>

```yaml
---
services:
  cloudquery:
    image: fab/cloudquery
    build:
      context: docker
      dockerfile: Dockerfile.cloudquery
      args:
        TARGETVERSION: "2.0.13"
    volumes:
      - ./config/aws/config:/home/cloudquery/.aws/config:ro
      - $HOME/.aws/credentials:/home/cloudquery/.aws/credentials:ro
      - ./config/cq:/home/cloudquery/configs:ro
      - cloudquery_cache:/home/cloudquery/.cq:rw
  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=cloudquery
    ports:
      - '5432:5432'
    volumes:
      - postgres_db:/var/lib/postgresql/data

volumes:
  cloudquery_cache:
  postgres_db:

```

</details>

<details>
<summary>Dockerfile.cloudquery</summary>

```dockerfile
FROM ubuntu:22.04

ARG TARGETVERSION
ARG TARGETOS="linux"
ARG TARGETARCH="amd64"

RUN adduser \
    --system --disabled-login \
    --ingroup 0 --gecos "cloudquery user" --shell /bin/false \
    cloudquery \
  && mkdir -p /home/cloudquery/.aws \
  && mkdir -p /home/cloudquery/.cq \
  && mkdir -p /home/cloudquery/configs \
  && chown -R cloudquery:0 /home/cloudquery \
  && apt-get update -y \
  && apt-get upgrade -y \
  && apt-get install -y \
    curl \
    git \
    less \
    unzip \
  # cloudquery
  && curl -fSL -o "/tmp/cloudquery.zip" \
    "https://github.com/cloudquery/cloudquery/releases/download/cli-v${TARGETVERSION}/cloudquery_${TARGETOS}_${TARGETARCH}.zip" \
  && unzip /tmp/cloudquery.zip -d /tmp \
  && mv /tmp/cloudquery /usr/local/bin/ \
  && chmod +x /usr/local/bin/cloudquery \
  && rm -rf /tmp/cloudquery.zip \
  # aws-cli
  && mkdir -p /awscli/ \
  && curl -fSL -o /awscli.zip "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" \
  && unzip /awscli.zip -d /awscli/ \
  && /awscli/aws/install --bin-dir /usr/bin --install-dir /usr/local/aws-cli \
  && rm -rvf /awscli.zip \
  # tests
  && aws --version \
  && cloudquery --version \
  && git --version

USER cloudquery:0
WORKDIR /home/cloudquery

ENV CQ_TELEMETRY_LEVEL="none"
ENTRYPOINT ["cloudquery"]
```

</details>

```shell
$ cloudquery migrate configs/
$ cloudquery sync configs/
```

### Additional Context
<!--
Add any other context or examples about the feature request here.
-->

### References
<!--
Link any other relevant PRs or Issues
-->

**Comment by erezrokah** [comment]
Hi @asvinours, thank you for opening the issue and sorry you're experiencing this.
This seems like a bug with our latest version of the PostgreSQL plugin `v1.7.8`. Do you mind trying with `v1.7.7`?
That is, use the following config for the destination:
```yml
kind: destination
spec:
  name: "postgresql"
  path: "cloudquery/postgresql"

  version: "v1.7.8"
  write_mode: "overwrite-delete-stale"

  spec:
    # pgx_log_level: debug
    connection_string: postgresql://postgres:mysecretpassword@postgres:5432/cloudquery?sslmode=disable
```
