### ISSUE TITLE
Sync command exits with error on big AWS org

### ISSUE THREAD

**Issue by asvinours** [cloudquery/cloudquery#4585]
### Describe the Bug

We have an AWS organization with ~250 accounts, and the sync command is unable to complete successfully. I thought about the IAM roles expiring, but the role is valid for ~1h and the sync command exits after couple of minutes.

If the sync command is used in `accounts` mode with one account, it completes properly.
If we use it in `org` mode, even with one single region, it fails to complete. 
We tried adjusting the `batch_size` config spec of the destination plugin but it does not seem to help.

```shell
cloudquery sync configs/ --log-level debug
Loading spec(s) from configs/
Starting migration for: aws -> [postgresql]
Migration completed successfully.
Starting sync for:  aws -> [postgresql]
failed to terminate source client:  source plugin process exited with status signal: killed
Error: failed to sync source aws: failed to fetch resources from stream: rpc error: code = Unavailable desc = error reading from server: EOF
```

### Expected Behavior

Sync command to complete successfully on big organizations

### CloudQuery Version

```shell
$ cloudquery --version
cloudquery version 2.0.13
```

Source plugin: AWS, version `4.15.1`
Destination plugin: postgresql, version `1.7.9`

### Debug Output

[cloudquery.log](https://github.com/cloudquery/cloudquery/files/10005689/cloudquery.log)

### Steps to Reproduce

<details>
<summary>Source configuration</summary>

```yaml
---
kind: source
spec:
  name: "aws"
  path: "cloudquery/aws"

  version: "v4.15.1"
  tables: ["*"]
  destinations: ["postgresql"]

  spec:
    aws_debug: false
    regions: []
    org:
      admin_account:
        id: "root"
        local_profile: "root"
      member_trusted_principal:
        id: "main-identity"
        local_profile: "main-identity"
      member_role_name: "ReadOnly"
      member_role_session_name: "CloudQuery"
      member_regions: ['us-east-1']
```

</details>

<details>
<summary>Destination configuration</summary>

```yaml
---
kind: destination
spec:
  name: "postgresql"
  path: "cloudquery/postgresql"

  version: "v1.7.9"
  write_mode: "overwrite-delete-stale"

  spec:
    connection_string: postgresql://postgres:mysecretpassword@postgres:5432/cloudquery?sslmode=disable
```

</details>

<details>
<summary>Docker compose configuration</summary>

```yaml
---
services:
  cloudquery:
    image: fab/cloudquery
    build:
      context: docker
      dockerfile: Dockerfile.cloudquery
      args:
        TARGETVERSION: "2.0.13"
    volumes:
      - ./config/aws/config:/home/cloudquery/.aws/config:ro
      - $HOME/.aws/credentials:/home/cloudquery/.aws/credentials:ro
      - ./config/cq:/home/cloudquery/configs:ro
      - cloudquery_cache:/home/cloudquery/.cq:rw

  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=cloudquery
    ports:
      - '5432:5432'
    volumes:
      - ./config/postgres:/etc/postgres-queries:ro
      - postgres_db:/var/lib/postgresql/data

  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    volumes:
      - ./config/grafana/provisioning:/etc/grafana/provisioning:ro
      - ./config/grafana/dashboards:/etc/grafana-dashboards:ro
      - grafana_data:/var/lib/grafana

volumes:
  cloudquery_cache:
  postgres_db:
  grafana_data:
```

</details>

<details>
<summary>Dockerfile.cloudquery</summary>

```dockerfile
FROM ubuntu:22.04

ARG TARGETVERSION
ARG TARGETOS="linux"
ARG TARGETARCH="amd64"

RUN adduser \
    --system --disabled-login \
    --ingroup 0 --gecos "cloudquery user" --shell /bin/false \
    cloudquery \
  && mkdir -p /home/cloudquery/.aws \
  && mkdir -p /home/cloudquery/.cq \
  && mkdir -p /home/cloudquery/configs \
  && chown -R cloudquery:0 /home/cloudquery \
  && apt-get update -y \
  && apt-get upgrade -y \
  && apt-get install -y \
    curl \
    git \
    less \
    unzip \
  # cloudquery
  && curl -fSL -o "/tmp/cloudquery.zip" \
    "https://github.com/cloudquery/cloudquery/releases/download/cli-v${TARGETVERSION}/cloudquery_${TARGETOS}_${TARGETARCH}.zip" \
  && unzip /tmp/cloudquery.zip -d /tmp \
  && mv /tmp/cloudquery /usr/local/bin/ \
  && chmod +x /usr/local/bin/cloudquery \
  && rm -rf /tmp/cloudquery.zip \
  # aws-cli
  && mkdir -p /awscli/ \
  && curl -fSL -o /awscli.zip "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" \
  && unzip /awscli.zip -d /awscli/ \
  && /awscli/aws/install --bin-dir /usr/bin --install-dir /usr/local/aws-cli \
  && rm -rvf /awscli.zip \
  # tests
  && aws --version \
  && cloudquery --version \
  && git --version

USER cloudquery:0
WORKDIR /home/cloudquery

ENV CQ_TELEMETRY_LEVEL="none"
ENTRYPOINT ["cloudquery"]
```

</details>

```shell
$ cloudquery migrate configs/ --log-level debug
$ cloudquery sync configs/ --log-level debug
```
