### ISSUE TITLE
cloudquery init digitalocean is not working for me

### ISSUE THREAD

**Issue by Niba-nazar** [cloudquery/cloudquery#4616]
Hi, 

Months ago I installed cloudquery and tried to generate `config.hcl` file for Digital ocean by using `cloudquery init digitalocean`.  It worked fine and the generated file was `cloudquery.yml` actually. Now I tried configuring SQLite as a destination and was having difficulty doing so. Hence I removed the installed cloudquery and tried to do it fresh. 

I have installed it under root and am now getting the following:  now 'init' is not working for me. I tried many ways still getting the same.

```

root@niba:~# curl -L https://versions.cloudquery.io/latest/v2/cloudquery_linux_amd64 -o cloudquery
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   115    0   115    0     0    189      0 --:--:-- --:--:-- --:--:--   189
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
100 12.3M  100 12.3M    0     0   551k      0  0:00:22  0:00:22 --:--:--  827k
root@niba:~# chmod a+x cloudquery
root@niba:~# /root/cloudquery init digitalocean
Error: unknown command "init" for "cloudquery"
Run 'cloudquery --help' for usage.
root@niba:~# cloudquery init digitalocean
cloudquery: command not found
```

Also, I tried before, by creating a digitalocean.yml file as below, and tried to sync it by using `cloudquery sync ./digitalocean.yml` and `/root/cloudquery sync ./digitalocean.yml`  
```
kind: source
spec:
  name: digitalocean
  version: v2.2.21
  destinations: [sqlite]
  path: ./digitalocean
  registry: local
---
kind: destination
spec:
  name: sqlite
  path: cloudquery/sqlite
  version: "v1.0.6" # latest version of sqlite plugin
  spec:
    connection_string: ${CQ_DSN}

```

was getting no such file or directory named digitalocean

### Expected Behavior
Expected to work fine for me but it didn't

### CloudQuery Version
cloudquery version 2.0.16

### Debug Output
cloudquery --log-console --log-level debug, not working for me

### Steps to Reproduce

Also please share any other necessary configuration files
am only having a cloudquery file and cloudquery.log file

### References
referred links are: 
https://www.cloudquery.io/blog/introducing-the-digital-ocean-cloudquery-provider
https://www.cloudquery.io/docs/reference/cli/cloudquery_sync
https://www.cloudquery.io/docs/quickstart
