### ISSUE TITLE
aws resource synchronization problem

### ISSUE THREAD

**Issue by songant** [cloudquery/cloudquery#4627]
Error synchronizing aws resources using cloudquery, the configuration is as follows:

**aws.yml**

```yml
kind: source
spec:

  name: "aws"
  path: "cloudquery/aws"

  version: "v5.1.1" # latest version of aws plugin

  destinations: ["postgresql"]

  spec:
    regions:
      - us-east-1
    accounts:
      - local_profile: "/Users/shareit/.aws/credentials"
        id: "XXX"
    aws_debug: true
```

 **/Users/shareit/.aws/credentials**

```ini
[default]
aws_access_key_id = xxxxx
aws_secret_access_key = xxxxx
```

**Execution error**
```
Loading spec(s) from aws.yml, postgresql.yml
Starting migration for: aws -> [postgresql]
Migration completed successfully.
Starting sync for:  aws -> [postgresql]
Error: failed to sync source aws: failed to fetch resources from stream: rpc error: code = DeadlineExceeded desc = failed to sync resources: failed to create execution client for source plugin aws: error retrieving credentials: failed to refresh cached credentials, no EC2 IMDS role found, operation error ec2imds: GetMetadata, canceled, context deadline exceeded
```
thanks

**Comment by songant** [comment]
error

**Comment by erezrokah** [comment]
Hi @songant and thank you for opening the issue.

Can you trying removing `local_profile` from your configuration file, that is try the following:
```yml
kind: source
spec:

  name: "aws"
  path: "cloudquery/aws"

  version: "v5.1.1" # latest version of aws plugin

  destinations: ["postgresql"]

  spec:
    regions:
      - us-east-1
    accounts:
      - id: "XXX"
    aws_debug: true
```

I believe that should work. In general `local_profile` should point to the name of a profile inside the AWS credentials file (and not to the file itself). For example, with the following file

```ini
[default]
aws_access_key_id=xxxx
aws_secret_access_key=xxxx

[user1]
aws_access_key_id=xxxx
aws_secret_access_key=xxxx
```

`local_profile` should be either `default` or `user1`.

More about this in https://github.com/cloudquery/cloudquery/blob/58112854fb686653d33a0db9eed504a1feb13dee/plugins/source/aws/docs/configuration.md#accounts.

I'll also look into improving that error message/our docs
