### ISSUE TITLE
feat(aws): Improve error message when wrong `local_profile` is used

### ISSUE THREAD

**Issue by erezrokah** [cloudquery/cloudquery#4656]
Related to https://github.com/cloudquery/cloudquery/issues/4627.

If someone uses the wrong `local_profile`, e.g.
```yml
kind: source
spec:
  name: "aws"
  path: "cloudquery/aws"
  version: "v5.1.1" # latest version of aws plugin
  destinations: ["postgresql"]

  spec:
    accounts:
      - local_profile: "<does-not-exists>"
        id: "XXX"
```

They'll get the following error:

```
Loading spec(s) from aws.yml, postgresql.yml
Starting migration for: aws -> [postgresql]
Migration completed successfully.
Starting sync for:  aws -> [postgresql]
Error: failed to sync source aws: failed to fetch resources from stream: rpc error: code = DeadlineExceeded desc = failed to sync resources: failed to create execution client for source plugin aws: error retrieving credentials: failed to refresh cached credentials, no EC2 IMDS role found, operation error ec2imds: GetMetadata, canceled, context deadline exceeded
```

We should either improve the docs or the error message
