### ISSUE TITLE
Cloudquery deletes data from other tables if provided list of tables in source config

### ISSUE THREAD

**Issue by rajeshwarakella1994** [cloudquery/cloudquery#4770]
By default CQ runs for all tables but when a configuration as mentioned below is provided, data is getting deleted from other tables as well.

This is the case with overwrite-delete-stale mode in postgres destination.
Sharing the config files below - 

**aws.yml**
```yml
kind: source
spec:
  name: "aws_667292283479"
  path: "cloudquery/aws"
  version: "v5.1.2"
  destinations: ["postgresql"]
  tables: 
  - aws_rds_engine_versions
  - aws_rds_cluster_parameters
```

**rds.yml**
```yml
kind: destination
spec:
  name: "postgresql"
  path: "cloudquery/postgresql"
  version: "v1.7.10" 
  write_mode: "overwrite-delete-stale" # overwrite, overwrite-delete-stale, append
```

**Comment by rajeshwarakella1994** [comment]
Discord thread here - https://discord.com/channels/872925471417962546/1042796460342775909

**Comment by cloudmatt** [comment]
I _believe_ i'm seeing the same issue as well but with the GCP plugin. I have two 'instances' of the gcp plugin run (see config snippet below) but I only seem to be capturing a subset of the tables. I know it's not a permissions issue because this worked fine before I split out the two sources.

```yaml
---
kind: source
spec:
  name: gcp-all
  path: cloudquery/gcp
  version: "v3.0.5"
  tables: ["*"]
  skip_tables:
    - "gcp_compute_disk_types"
  destinations: ["postgresql"]
  spec:
    folder_ids:
     - "folders/123456789"
    project_ids:
      - projectA
      - projectB
---
kind: source
spec:
  name: gcp-bq-exception
  path: cloudquery/gcp
  version: "v3.0.5"
  tables: ["*"]
  skip_tables:
    - "gcp_compute_disk_types"
    - "gcp_bigquery_datasets"
    - "gcp_bigquery_tables"
  destinations: ["postgresql"]
  spec:
    project_ids:
      - projectC
      - projectD
---
kind: destination
spec:
  name: postgresql
  path: cloudquery/postgresql
  version: "v1.7.14"
  write_mode: overwrite-delete-stale
  spec:
    connection_string: ${CQ_DSN}
```

and the query
```sql
select count(_cq_table), _cq_table from gcp_resources group by _cq_table;
```

only returns
<img width="254" alt="image" src="https://user-images.githubusercontent.com/95309754/204419031-811f3c4d-e02b-4506-98f6-c61d416e95b3.png">
