### ISSUE TITLE
bug(aws): Sync should still complete for other accounts if one fails to authenticate

### ISSUE THREAD

**Issue by hermanschaaf** [cloudquery/cloudquery#5028]
Currently, when a list of accounts is specified for the AWS source plugin, the sync fails completely if any one of the accounts fail to retrieve credentials. This can be a problem for setups where accounts (and the associated roles) frequently get nuked. In this case we would expect the sync to still complete for all working accounts, but report errors for the failed account(s). 

Minimal source config that reproduces the issue:

```
kind: source
spec:
  name: "aws"
  version: "v7.2.0"
  registry: "github"
  path: "cloudquery/aws"
  tables: 
    - aws_ec2_instances
  destinations: 
    - "postgresql"
  spec:
    regions:
      - us-east-1
  spec:
    accounts:
    - local_profile: profile1 # profile1 exists
      regions: ["us-east-1"]
    - local_profile: profile2 # profile2 does not exist
      regions: ["us-east-2"]
```

Output: 
```
cloudquery sync aws.yml
Loading spec(s) from aws.yml
Starting migration for: aws -> [postgresql]
Migration completed successfully.
Starting sync for:  aws -> [postgresql]
Error: failed to sync source aws: failed to fetch resources from stream: rpc error: code = Unknown desc = failed to sync resources: failed to create execution client for source plugin aws: error retrieving AWS credentials (see logs for details). Please verify your credentials and try again
```

## Notes

In `overwrite-delete-stale` mode, I think the old rows should still be deleted for accounts that cannot be authenticated against. This is because auth issues are unlikely to arise randomly; once you have the correct credentials set up, they should continue working. And if the credentials do stop working, the next time you run a sync the rows for the account will be repopulated in any case.

This issue was initially reported by @altho1 on Discord.
