### ISSUE TITLE
plugin: New API destination

### ISSUE THREAD

**Issue by erezrokah** [cloudquery/cloudquery#5107]
### Why do you need this resource or plugin? Please describe.

Logging a thought (not a priority). We could have a simple ~~proxy~~ API destination that sends synced data to an HTTP(s) endpoint.
Some use cases:

1. Use an ~~proxy server~~ API endpoint to route different data to different databases
3. Write custom logic for consuming data using other languages than Go
4. Not needing to modify a binary, release it and distribute it. Instead one could re-deploy the API

### Describe the solution you'd like

An example spec could look like:

```yml
kind: "destination"
spec:
 ...
 spec:
   api_url: "https://cq-api.my-domain.com/v1"
   # optional, used for authentication
   request_headers: ""
```

### Additional context

N/A
