### ISSUE TITLE
feat: Provide better error when someone runs `sync --no-migrate` and there are no tables

### ISSUE THREAD

**Issue by erezrokah** [cloudquery/cloudquery#5152]
Extracted from https://github.com/cloudquery/cloudquery/discussions/5150

When someones runs CloudQuery for the first time (without an initialized database) and uses the `--no-migrate` flag they get the following error:
```bash
Error: failed to write for aws->local-sqlite: failed to call Write2.Send: EOF
```

Config to reproduce:
```yml
kind: source
spec:
  name: aws
  path: "cloudquery/aws"
  version: "v7.2.2"
  destinations: ["local-sqlite"]
---
kind: destination
spec:
  name: "local-sqlite"
  path: "cloudquery/sqlite"
  version: "v1.0.9"
  spec:
    connection_string: "local.sql"
```

We should provide a better error message in this case to let the user know that migration is required to bootstrap the database
