### ISSUE TITLE
bug(website): Version replacement doesn't work when copy pasting code blocks

### ISSUE THREAD

**Issue by erezrokah** [cloudquery/cloudquery#5483]
To reproduce, copy paste https://www.cloudquery.io/docs/plugins/sources/aws/configuration#simple-example.

The result is:

```yml
kind: source
spec:
 # Source spec section
 name: aws
 path: cloudquery/aws
 version: "VERSION_SOURCE_AWS"
 tables: ["*"]
 destinations: ["postgresql"]
 spec: 
 # AWS Spec section described below
 regions: 
 - us-east-1
 accounts:
 - id: "account1"
 local_profile: "account1"
 aws_debug: false

```
