### ISSUE TITLE
Cloudquery sync command failing with cq source aws not found

### ISSUE THREAD

**Issue by bhaskarbalusani** [cloudquery/cloudquery#5576]
Im using latest version of cloud query. 
cloudquery version 2.0.24

Here is the content of AWS config file.
```yml
kind: source
spec:
  name: "aws"
  path: "config/aws"
  version: "v7.3.0"
  tables: ["*"]
  destinations: ["csv"]
  spec:
    # AWS Spec section described below
    regions: 
      - us-east-1
```

When I run the cloudquery sync command with the above file.
PS C:\dev\drift> **.\cloudquery sync ./config**
Loading spec(s) from ./config
Failed downloading https://github.com/config/cq-source-aws/releases/download/v7.3.0/cq-source-aws_windows_amd64.zip with status code 404. Retrying
Failed downloading https://github.com/config/cq-source-aws/releases/download/v7.3.0/cq-source-aws_windows_amd64.zip with status code 404. Retrying
Failed downloading https://github.com/config/cq-source-aws/releases/download/v7.3.0/cq-source-aws_windows_amd64.zip with status code 404. Retrying
Failed downloading https://github.com/config/cq-source-aws/releases/download/v7.3.0/cq-source-aws_windows_amd64.zip with status code 404. Retrying
Failed downloading https://github.com/config/cq-source-aws/releases/download/v7.3.0/cq-source-aws_windows_amd64.zip with status code 404. Retrying
Error: failed to get source plugin client for aws: failed to download plugin: failed downloading: https://github.com/config/cq-source-aws/releases/download/v7.3.0/cq-source-aws_windows_amd64.zip

Is that a bug with this version?

**Comment by erezrokah** [comment]
Hi @bhaskarbalusani and thank you for reporting this issue. Can you try with the following config:

```yml
kind: source
spec:
  name: "aws"
  path: "cloudquery/aws"
  version: "v7.3.0"
  tables: ["*"]
  destinations: ["csv"]
  spec:
    # AWS Spec section described below
    regions: 
      - us-east-1
```

The path property should be `cloudquery/aws`
