### ISSUE TITLE
error="log line too long, discarding"

### ISSUE THREAD

**Issue by MichaelTay0** [cloudquery/cloudquery#5665]
### Describe the Bug

 ERR skipping too long log line error="log line too long, discarding" 

### Expected Behavior

Cq should insert data into bigquery table

### CloudQuery Version

https://versions.cloudquery.io/latest/v2/cloudquery_linux_amd64

### Steps to Reproduce

```kind: source
spec:
  name: "gcp"
  path: "cloudquery/gcp"
  registry: "github"
  version: "v4.0.0"
  concurrency: 5
  skip_tables: ["gcp_bigquery_tables", "gcp_compute_disk_types"]
  tables: ["gcp_compute*", "gcp_sql*", "gcp_storage*", "gcp_bigquery_datasets"]
  destinations: ["postgresql","bigquery"]
  spec:
    service_account_key_json: '${file:./<KEY>}'
```
```
kind: destination
spec:
  name: "bigquery"
  version: "v1.1.2"
  registry: "github"
  path: "cloudquery/bigquery"
  write_mode: "append"
  spec:
    project_id: "<project_id>"
    dataset_id: "<dataset>"
    service_account_key_json: '${file:./<KEY>.json}'
    time_partitioning: "day"
```
### Additional Context

this is running in a gke environment.  this is trying to populate data into a bigquery dataset.

this fetch its
