### ISSUE TITLE
bug(aws-resource-ses): `aws_ses_active_receipt_rule_sets` generates write errors

### ISSUE THREAD

**Issue by erezrokah** [cloudquery/cloudquery#5991]
Run a sync with the following config:

```yaml
kind: source
spec:
  name: aws
  version: v8.1.0
  destinations: [postgresql]
  path: cloudquery/aws
  tables: ["aws_ses_active_receipt_rule_sets"]
---
kind: destination
spec:
  name: "postgresql"
  path: "cloudquery/postgresql"
  version: "v1.10.0"
  write_mode: "overwrite-delete-stale"
  spec:
    connection_string: postgresql://postgres:pass@localhost:5432/postgres
```

See the following error in the log:
```
failed to execute batch with pgerror on table aws_ses_active_receipt_rule_sets: ERROR: null value in column \"name\" violates not-null constraint (SQLSTATE 23502)
```
