### ISSUE TITLE
bug(aws-ses): `aws_ses_active_receipt_rule_sets` generates a lot of resolver errors

### ISSUE THREAD

**Issue by erezrokah** [cloudquery/cloudquery#5995]
Run a sync with the following config:

```yaml
kind: source
spec:
  name: aws
  version: v8.1.0
  destinations: [postgresql]
  path: cloudquery/aws
  tables: ["aws_ses_active_receipt_rule_sets"]
---
kind: destination
spec:
  name: "postgresql"
  path: "cloudquery/postgresql"
  version: "v1.10.0"
  write_mode: "overwrite-delete-stale"
  spec:
    connection_string: postgresql://postgres:pass@localhost:5432/postgres
```

See multiple errors in the following format:
```
ERR table resolver finished with error error="operation error SES: DescribeActiveReceiptRuleSet, https response error StatusCode: 400, RequestID: ********, api error InvalidAction: Unavailable Operation" client=******:eu-west-3
```

Apparently only a few regions support that API call https://docs.aws.amazon.com/ses/latest/dg/regions.html#region-receive-email
