### ISSUE TITLE
feat: filter out columns

### ISSUE THREAD

**Issue by yevgenypats** [cloudquery/cloudquery#6388]
Some use-cases require to make sure columns are never synced to a destination.

This will require a way for a user to specify table and columns to filter out.

```
spec:
  filter:
    - name: table_name
      columns: ["column_name"]
```

EDIT: additional use-case:
 filtering inside `JSON`. This goes a bit into transformations so we need to see what is the right approach here that can generalize well.
