### ISSUE TITLE
Error aws->postgresql unexpected EOF

### ISSUE THREAD

**Issue by castaples** [cloudquery/cloudquery#6431]
After upgrading to the latest version CQ and AWS/Postgres plugins I get the following output in the logs after the sync exits after only 7 mins running (usual runs for close to 3 hours) having gathered credentials and started syncing tables.

```
Error: failed to write for aws->postgresql: failed to CloseAndRecv client: rpc error: code = Internal desc = Context done: context canceled and failed to wait for plugin: failed to execute batch: unexpected EOF
```

We've gone from CQ `1.3.7` to `2.0.31`, AWS from `v3.5.0` to `v9.1.1` and Postgres from `v1.3.9` to `v2.0.1`

We're running CQ in a docker container on AWS ECS with Aurora Serverless v1 Postgres (pre-scaled to 16 ACU before sync called), this has worked fairly well for some time on a daily schedule. We have 350+ AWS accounts with only a few tables in the CQ config ignore list, mainly 'aws_inspector2_findings' and all the lightsail tables.

Please let me know what else you'd need to diagnose this.

**Comment by hermanschaaf** [comment]
Hi @castaples, thanks for reaching out! Other than the output of the CLI, could you tell us if there are any other error-level messages in the `cloudquery.log` file?

**Comment by castaples** [comment]
Yes so there are a lot, if I filter out the 403 errors (we probably need to update the role CQ is using to give it a few more permissions) which we had previously and it was working, I can see a lot relating to CodePipeline, for example:
```json
{
    "level": "error",
    "module": "aws-src",
    "client": "************:eu-west-1",
    "error": "operation error CodePipeline: ListWebhooks, https response error StatusCode: 0, RequestID: , canceled, context canceled",
    "message": "table resolver finished with error",
    "table": "aws_codepipeline_webhooks",
    "time": "2023-01-06T09:22:43Z"
}
```

**Comment by yevgenypats** [comment]
Hi @castaples , thx for the report! Can you please try postgresql `v2.0.3` - https://github.com/cloudquery/cloudquery/releases/tag/plugins-destination-postgresql-v2.0.3 and let us know if that worked or still the same behaviour ?

**Comment by castaples** [comment]
I've tried again with CQ `2.0.31`, AWS `v9.1.1` and Postgres `v2.0.3`, unfortunately I get the same problem, unexpected EOF error.

```json
{
    "level": "error",
    "module": "cli",
    "error": "failed to write for aws->postgresql: failed to CloseAndRecv client: rpc error: code = Internal desc = Context done: context canceled and failed to wait for plugin: failed to execute batch: unexpected EOF",
    "time": "2023-01-09T08:48:51Z",
    "message": "exiting with error"
}
```

I've been though the logs and tried to filter out the noise to find anything that might be useful, these stood out to me as they had some detail in the error messages.

```json
{
    "level": "error",
    "module": "aws-src",
    "client": "************:ap-southeast-3",
    "error": "operation error ApiGatewayV2: GetApis, https response error StatusCode: 400, RequestID: 32284d50-cad3-4b5a-84f5-3f94ff856287, deserialization failed, failed to decode response body, invalid character '\\'' in string escape code",
    "message": "table resolver finished with error",
    "table": "aws_apigatewayv2_apis",
    "time": "2023-01-09T08:44:10Z"
}
```

```json
{
    "level": "error",
    "module": "aws-src",
    "client": "************:ca-central-1",
    "error": "operation error ApiGatewayV2: GetDomainNames, https response error StatusCode: 200, RequestID: cbb34ac1-9660-42bf-9aae-21563cd470cb, deserialization failed, failed to decode response body with invalid JSON, expected json.Number to be of type string, got string instead",
    "message": "table resolver finished with error",
    "table": "aws_apigatewayv2_domain_names",
    "time": "2023-01-09T08:44:14Z"
}
```

```json
{
    "level": "error",
    "module": "aws-src",
    "client": "************:us-east-1",
    "error": "operation error Backup: GetBackupVaultNotifications, https response error StatusCode: 400, RequestID: 9bbd25a9-dfc7-4806-92a8-b12b20f8eae0, api error ERROR_2106: Failed reading notifications from database for Backup vault Default",
    "message": "column resolver finished with error",
    "table": "aws_backup_vaults",
    "time": "2023-01-09T08:45:42Z"
}
```

This final entry occurs just before the Postgres unexpected EOF error

```json
{
    "level": "info",
    "module": "cli",
    "address": "/tmp/cq-VgkcXiwkhVWaTpsA.sock",
    "message": "Got interrupt. Source plugin server shutting down",
    "time": "2023-01-09T08:48:51Z"
}
```

Please let me know if you want me to try anything else or look through the logs for something specific, I'll endeavour to get the CQ role permissions updated to rule out lack of permissions causing this issue.

**Comment by erezrokah** [comment]
Hi @castaples, thanks for digging through the logs and providing these extra errors, super valuable.
The error you're seeing is coming from either https://github.com/cloudquery/cloudquery/blob/d766e56fb8519c378b0ba10cef734032796f9d4d/plugins/destination/postgresql/client/write.go#L78 or https://github.com/cloudquery/cloudquery/blob/d766e56fb8519c378b0ba10cef734032796f9d4d/plugins/destination/postgresql/client/write.go#L93

The errors you've discovered (except the last one) are related to the source plugin. However we're looking for the destination plugin detailed error (if present).
The last error is expected as we stop the sync if there's an error write a batch to Postgres. Looks like that in this case we are unable to extract useful information from the received error.

A possible way to get more about the failure is to use another destination and see if that works or we get more information (for the sake of debugging).
For example see the SQLite destination docs [here](https://www.cloudquery.io/docs/plugins/destinations/sqlite/overview)

**Comment by castaples** [comment]
I've tried several times to get SQLite v1.1.5 (CQ 2.1 & AWS v10.1.0) working but keep getting the following error:

```json
{
    "level": "error",
    "module": "cli",
    "error": "failed to create destination plugin client for sqlite: failed to start destination plugin .cq/plugins/destination/cloudquery/sqlite/v1.1.5/plugin: fork/exec .cq/plugins/destination/cloudquery/sqlite/v1.1.5/plugin: no such file or directory",
    "time": "2023-01-11T14:42:59Z",
    "message": "exiting with error"
}
```
Config
```yml
kind: source
spec:
  ## Required. name of the plugin to use.
  ## This should be unique if you have number of aws plugins.
  name: 'aws'
  ## Optional. Where to search for the plugin. Default: "github". Options: "github", "local", "grpc"
  # registry: "github"

  ## Path for the plugin.
  ## If registry is "github" path should be "repo/name"
  ## If registry is "local", path is path to binary. If "grpc" then it should be address of the plugin (usually useful in debug).
  path: 'cloudquery/aws'

  ## Required. Must be a specific version starting with v, e.g. v1.2.3
  ## checkout latest versions here https://github.com/cloudquery/cloudquery/releases?q=plugins-source-aws&expanded=true
  version: ${CQ_VAR_CLOUD_QUERY_AWS_PLUGIN_VERSION}

  ## Optional. Default: ["*"] - all tables. We recommend to specify specific tables that you need to sync as this
  ## will reduce the amount of data synced and improve performance.
  ## See all tables: https://github.com/cloudquery/cloudquery/blob/main/plugins/source/aws/docs/tables/README.md
  # tables: ["*"]

  skip_tables:
    [
      'aws_inspector2_findings',
      'aws_lightsail_alarms',
      'aws_lightsail_buckets',
      'aws_lightsail_bucket_access_keys',
      'aws_lightsail_certificates',
      'aws_lightsail_container_services',
      'aws_lightsail_container_service_deployments',
      'aws_lightsail_container_service_images',
      'aws_lightsail_databases',
      'aws_lightsail_database_parameters',
      'aws_lightsail_database_events',
      'aws_lightsail_database_log_events',
      'aws_lightsail_database_snapshots',
      'aws_lightsail_disks',
      'aws_lightsail_disk_snapshot',
      'aws_lightsail_distributions',
      'aws_lightsail_instances',
      'aws_lightsail_instance_port_states',
      'aws_lightsail_instance_snapshots',
      'aws_lightsail_load_balancers',
      'aws_lightsail_load_balancer_tls_certificates',
      'aws_lightsail_static_ips',
    ]

  ## Required. all destinations you want to sync data to.
  destinations: ['sqlite']

  # resource_concurrency: 100000

  spec:
    ## Optional. plugin specific configuration
    ## By default will use the current aws credentials available (just like AWS CLI)
    ## See all available options here: https://github.com/cloudquery/cloudquery/blob/main/plugins/source/aws/docs/configuration.md
    org:
      member_role_name: ${CQ_VAR_AWS_CLOUD_QUERY_MEMBER_ROLE_NAME}
      admin_account:
        id: 'UK_Consolidated'
        role_arn: ${CQ_VAR_AWS_CLOUD_QUERY_ADMIN_ROLE_ARN}
      member_trusted_principal:
        id: 'CloudQueryTaskRole'
        role_arn: ${CQ_VAR_AWS_CLOUD_QUERY_ROLE_ARN}
---
kind: destination
spec:
  name: sqlite
  path: cloudquery/sqlite
  version: 'v1.1.5'
  spec:
    connection_string: /app/db.sql
```

As the versions of CQ and AWS plugin have changed since I last tried Postgres, I will try again with the latest versions.
