### ISSUE TITLE
bug: gcp_aiplatform_models giving error

### ISSUE THREAD

**Issue by cloudmatt** [cloudquery/cloudquery#6494]
### Describe the Bug

Updated to the gcp source plugin version 5.5.0 and was combing through the job logs after my last couple cloudquery runs and noticed the following error being spammed for all my projects:

```shell copy
2023-01-08T18:05:18Z ERR column resolver finished with panic error={} client=$PROJECT_NAME column=metadata duration=0.121954 module=gcp-src stack="failed to set column metadata: json: error calling MarshalJSON for type *structpb.Value: proto:\u00a0google.protobuf.Value: none of the oneof fields is set\ngoroutine 27441 [running]:\nruntime/debug.Stack()\n\t/opt/hostedtoolcache/go/1.19.4/x64/src/runtime/debug/stack.go:24 +0x65\ngithub.com/cloudquery/plugin-sdk/plugins/source.(*Plugin).resolveColumn.func1()\n\t/home/runner/go/pkg/mod/github.com/cloudquery/plugin-sdk@v1.20.0/plugins/source/scheduler.go:73 +0x86\npanic({0x146a340, 0xc01300c900})\n\t/opt/hostedtoolcache/go/1.19.4/x64/src/runtime/panic.go:884 +0x212\ngithub.com/cloudquery/plugin-sdk/schema.(*Resource).Set(0xc01303f480?, {0x186de6f, 0x8}, {0x17c4ea0?, 0xc012e764c0?})\n\t/home/runner/go/pkg/mod/github.com/cloudquery/plugin-sdk@v1.20.0/schema/resource.go:74 +0x155\ngithub.com/cloudquery/plugin-sdk/schema.PathResolver.func1({0x18?, 0x15834e0?}, {0x1a820c0?, 0xc0001abef0?}, 0xc01303f480, {{0x186de6f, 0x8}, 0xa, {0x0, 0x0}, ...})\n\t/home/runner/go/pkg/mod/github.com/cloudquery/plugin-sdk@v1.20.0/schema/resolvers.go:17 +0x73\ngithub.com/cloudquery/plugin-sdk/plugins/source.(*Plugin).resolveColumn(0xc0002808c0, {0x1a8f480, 0xc010193b60}, {{0x1a8b860, 0xc000595950}, 0x3, {0x0, 0x0}, {0xc01304a400, 0x54, ...}, ...}, ...)\n\t/home/runner/go/pkg/mod/github.com/cloudquery/plugin-sdk@v1.20.0/plugins/source/scheduler.go:80 +0x1cd\ngithub.com/cloudquery/plugin-sdk/plugins/source.(*Plugin).resolveResource(0xc0002808c0, {0x1a8f4b8?, 0xc0002e4a50?}, 0xc00096efc0, {0x1a820c0, 0xc0001abef0}, 0x0?, {0x183b8e0, 0xc012e73dc0})\n\t/home/runner/go/pkg/mod/github.com/cloudquery/plugin-sdk@v1.20.0/plugins/source/scheduler.go:56 +0x805\ngithub.com/cloudquery/plugin-sdk/plugins/source.(*Plugin).resolveResourcesDfs.func1.1()\n\t/home/runner/go/pkg/mod/github.com/cloudquery/plugin-sdk@v1.20.0/plugins/source/scheduler_dfs.go:149 +0x131\ncreated by github.com/cloudquery/plugin-sdk/plugins/source.(*Plugin).resolveResourcesDfs.func1\n\t/home/runner/go/pkg/mod/github.com/cloudquery/plugin-sdk@v1.20.0/plugins/source/scheduler_dfs.go:145 +0xf6\n" table=gcp_aiplatform_models

```

My config file looks like this:

```yaml
---
kind: source
spec:
  name: gcp-bq-exception
  path: cloudquery/gcp
  version: "v5.5.0"
  tables: ["*"]
  skip_tables:
    - "gcp_compute_disk_types"
    - "gcp_bigquery_datasets"
    - "gcp_bigquery_tables"
  destinations: ["postgresql", "bigquery"]
  spec:
    enabled_services_only: true
    project_ids:
      - "my_cool_project"
      - "my_less_cool_project"
```
### Expected Behavior

Not get an error? 😬 

### CloudQuery Version

Running the cloudquery docker image tagged `2.0.31` in a kubernetes cronjob.

### Steps to Reproduce

1. Run cloudquery
2. Wait
3. ????
4. Error
