### ISSUE TITLE
AWS multi-account configuration not working

### ISSUE THREAD

**Issue by johnkeates** [cloudquery/cloudquery#69]
When configuring multiple roles it doesn't seem like cq is even trying to assume the roles:

```
providers:
  - name: aws
    log_level: debug
    accounts:
      - role_arn: arn:aws:iam::123452641799:role/Administrator
      - role_arn: arn:aws:iam::123455796699:role/Administrator
    regions:
      - eu-west-1
    version: latest
    resources:
      - name: iam.policies
      - name: iam.roles
      - name: iam.users
```

I'm only getting data using `fetch` from the current account my access keys are valid for. Manually assume a role on the CLI works fine.
