### ISSUE TITLE
Commented Out Environment Variable Substitution 

### ISSUE THREAD

**Issue by bbernays** [cloudquery/cloudquery#6979]
### Describe the Bug

Commented out environment variables try to get substituted by spec reader

This files:
```
kind: source
spec:
  # Source spec section
  name: "aws"
  registry: "github"
  path: "cloudquery/aws"
  version: "v10.0.0"
  destinations: ["firehose"]
  spec:
    regions: 
      - "us-east-2"    
    max_retries: 0
    # service_account_key_json: '${CSCQ-BQ-SA}'
```
This succeeds:
```
kind: source
spec:
  # Source spec section
  name: "aws"
  registry: "github"
  path: "cloudquery/aws"
  version: "v10.0.0"
  destinations: ["firehose"]
  spec:
    regions: 
      - "us-east-2"    
    max_retries: 0
```
### Expected Behavior

commented lines should be ignored

### CloudQuery Version

cloudquery v2.2.0
