### ISSUE TITLE
Feat: Secret integration 

### ISSUE THREAD

**Issue by yevgenypats** [cloudquery/cloudquery#713]
### Is your feature request related to a problem? Please describe.
Multiple users asked for native integration with HCP Vault, AWS Secret manager, GCP Secret manager and Azure secret manager (without going through external k8s and publishing it to environments variables). This will also simplify deployments significantly. 

### Describe the solution you'd like

This needs an RFC but tldr config will look something like that:

```
vault:
    auth: ....
    secrets:
        - key: secret
          export_as: MY_SECRET

cloudquery:
   conneciton:
      dsn: ${CQ_VAR_MY_SECRET}
```
