### ISSUE TITLE
Mongo Destination Sync Stuck at the end

### ISSUE THREAD

**Issue by JayakrishnaThota** [cloudquery/cloudquery#7153]
### Describe the Bug
We are running cloudquery sync on one of our aws accounts to sync data to MongoDB destination. When running cq sync, we managed to import the data, but at the end the sync stuck(Attached Screenshot). We've tried multiple times & by multiple devs. I'm attaching logs (the last few lines are because we force closed the terminal process as it was idle for a while). We've tried postgres destination previously and it ended successfully unlike Mongo.

<img width="696" alt="image" src="https://user-images.githubusercontent.com/26243489/214426920-9d20073c-25f6-4b33-a2fa-d1e7f38eb52a.png">
<img width="1452" alt="Screenshot 2023-01-24 at 1 42 39 PM" src="https://user-images.githubusercontent.com/26243489/214427569-537ec7d2-03e2-413d-9dbd-219a45a2ef99.png">

### Expected Behavior
Finish sync succesfully

### CloudQuery Version
2.0.21
Pulled latest changes on 1/24
aws v8.1.0
Mongo v1.0.0

### Steps to Reproduce
cloudquery sync ${Path to config files}

My config files:
aws.yml

```
kind: source
spec:
  name: aws
  path: cloudquery/aws
  version: "v8.1.0"
  tables: ["*"]
  destinations: ["mongodb"]
  spec:
    regions: 
      - us-east-1
    accounts:
      - id: "xxxxxx"
```

mongodb.yml

```
kind: destination
spec:
  name: "mongodb"
  registry: "github"
  path: "cloudquery/mongodb"
  version: "v1.0.0"
  spec:
    connection_string: "mongodb://localhost:27017"
    database: "db-name"
```

Also please share any other necessary configuration files
-->
