### ISSUE TITLE
bug(sync): When syncing multiple sources and destinations the sync order is unpredictable

### ISSUE THREAD

**Issue by erezrokah** [cloudquery/cloudquery#7165]
Given the following configuration:

```yaml
kind: source
spec:
  name: aws
  path: cloudquery/aws
  version: v12.1.0
  destinations: [postgresql]
---
kind: source
spec:
  name: gcp
  path: cloudquery/gcp
  version: v7.2.1
  destinations: [postgresql]
---
kind: source
spec:
  name: azure
  path: cloudquery/azure
  version: v3.5.0
  destinations: [postgresql]
---
kind: destination
spec:
  name: postgresql
  path: cloudquery/postgresql
  version: v2.0.7
  spec:
    connection_string: postgresql://postgres:pass@localhost:5432/postgres
```

and running `cloudquery sync` multiple times, each time a different source will start first.
However destinations are always written to in the order defined in the source spec
