### ISSUE TITLE
S3 Destination: support YEAR, Month, Day variables in path

### ISSUE THREAD

**Issue by yevgenypats** [cloudquery/cloudquery#7213]
Users requested something like this to be supported for easy partitioning on top of S3 and Athena:

```
  spec:
    bucket: "cloudquery-dump"
    path: "records/{{YEAR}}/{{Month}}/{{DAY}}"
    format: "csv"
    athena: true
```
