### ISSUE TITLE
How to extract Office 365 (SharePoint or Streams) data?

### ISSUE THREAD

**Issue by rajaseg** [cloudquery/cloudquery#7650]
Hello Team,
Thank you very much for the project. While I was searching for tools to extract the data from Office 365 environment, I found this project.

Is it possible to extract the data from Office 365 Services like SharePoint or Streams Classic? I wanted to pass the extracted data to Elasticsearch output.

**Comment by yevgenypats** [comment]
Hey @rajaseg Thanks! Can you please point to the exact api reference on the Microsoft website? Also, are you aware of any official or community SDKs available for those APIs?

**Comment by rajaseg** [comment]
>

**Comment by rajaseg** [comment]
> Hey @rajaseg Thanks! Can you please point to the exact api reference on the Microsoft website? Also, are you aware of any official or community SDKs available for those APIs?

Hi @yevgenypats, Please find the API reference for the Office 365 services below.

https://learn.microsoft.com/en-us/graph/overview-major-services

**Comment by rajaseg** [comment]
> Hey @rajaseg Thanks! Can you please point to the exact api reference on the Microsoft website? Also, are you aware of any official or community SDKs available for those APIs?

Hi @yevgenypats, Please find links below MS Graph API links.

https://developer.microsoft.com/en-us/graph

https://developer.microsoft.com/en-us/graph/rest-api

**Comment by rajaseg** [comment]
Accidentally closed it. Re-opened.

**Comment by yevgenypats** [comment]
Thanks @rajaseg I've opened an [issue](https://github.com/microsoftgraph/msgraph-sdk-go/issues/386) request on the official  `msgraph-sdk-go` as usually we differ to the official vendor to maintain CloudQuery source plugins as we focus on developing the underlying framework. Please upvote and feel free to add comments to that [issue](https://github.com/microsoftgraph/msgraph-sdk-go/issues/386).

**Comment by yevgenypats** [comment]
@rajaseg Take a look at a new community sharepoint plugin - https://github.com/koltyakov/cq-source-sharepoint

**Comment by rajaseg** [comment]
> @rajaseg Take a look at a new community sharepoint plugin - https://github.com/koltyakov/cq-source-sharepoint

@yevgenypats Thank you very much. I will take a look and let you know the outcome.

**Comment by rajaseg** [comment]
@yevgenypats I have tried to sync SharePoint Online data to Elasticsearch. It synched Users list successfully. But Shared Documents not synched.

Please find the ```yml``` files below.

#### SharePoint (Source)
```
kind: source
spec:
  name: "sharepoint"
  registry: "github"
  path: "koltyakov/sharepoint"
  version: "v1.1.0" # https://github.com/koltyakov/cq-source-sharepoint/releases
  destinations: ["elasticsearch"]
  spec:
    auth:
      strategy: "addin"
      creds:
        siteUrl: https://tenant.sharepoint.com
        clientId: clientid
        clientSecret: clientsecret
        realm: tenantid
    lists:
      _catalogs/users:
        select:
          - Title
          - FirstName
          - LastName
          - JobTitle
          - Department
          - EMail
          - Deleted
        filter: "UserName ne null"
        alias: "user"
      Shared Documents:
        select:
          - FileLeafRef
          - FileRef
          - FileDirRef
          - Author/Title
          - File/Length
        expand:
          - Author
          - File
        alias: "document"
```
#### Elasticsearch (Destination)

```
kind: destination
spec:
  name: elasticsearch
  path: cloudquery/elasticsearch
  version: "v1.1.0"
  write_mode: "overwrite-delete-stale"
  # batch_size: 10000 # optional
  # batch_size_bytes: 5242880 # optional
  spec:
    # elasticsearch plugin spec
    addresses: ["https://elasticsearch.example.com"]
    username: elastic
    password: password
```
Please find the screen shots below for reference.

#### Cloudquery Sync Command

![image](https://user-images.githubusercontent.com/633479/221838688-41b67e59-c1ff-485c-b8d0-72b2ff755574.png)

#### SharePoint Shared Documents Library
![image](https://user-images.githubusercontent.com/633479/221839296-3d5f9f85-d4a4-4d76-8653-45e4adbc066f.png)

Am I doing anything wrong?
