### ISSUE TITLE
Custom table prefixes

### ISSUE THREAD

**Issue by michalz-rely** [cloudquery/cloudquery#8439]
### Is your feature request related to a problem? Please describe.
In some circumstances having an option to define a custom prefix for a tables created by the CQ could bring benefits in terms of access control and isolation.

### Describe the solution you'd like
Ability to define a custom prefix for all the tables created by the CQ in postgre destination plugin

### Describe alternatives you've considered
separate schema is a great alternative, but it might not be the preferred solution when integrating with legacy systems that share one schema

**Comment by pchaganti** [comment]
This would also be really useful when pulling in data from a large number of aws accounts and separating them by the account prefix for the table.

**Comment by uname223** [comment]
> This would also be really useful when pulling in data from a large number of aws accounts and separating them by the account prefix for the table.

I believe, each table has an account column, you can filter on that column

**Comment by harshithmullapudi** [comment]
Any update on this? We have a usecase where we want to have the same source in different tables.

Any suggestions on how to approach this?

**Comment by bbernays** [comment]
@harshithmullapudi - I don't think I fully understand what you are trying to do... Are you just trying to duplicate the data to multiple tables? Is there a reason why the data has to be in unique tables? If that is the case you could create a view on top of a table or use triggers on the original table to duplicate the data to other tables.

**Comment by harshithmullapudi** [comment]
Let me explain in detail. 

We are moving data of our clients from multiple sources to postgres. Here we have a unique identifier for every connection they create with the source (and the same source can be connected multiple times too) and we want that identifier to be part of the table name.

**Comment by bbernays** [comment]
Thank you for that clarification! While we don't have a timeline for when we will be able to release this feature there are a couple of ways that you could implement this same functionality today:
1. Each client gets their own schema in your PG database and you can specify the schema to use in the connection string of the destination config.
```
kind: destination
spec:
  name: "postgresql"
  registry: "github"
  path: "cloudquery/postgresql"
  version: "v4.1.1"
  spec:
    connection_string: "postgresql://postgres:pass@localhost:5432/postgres?search_path=${SCHEMA_IDENTIFIER}"
```

You can inject the schema name/identifier using the environment variable substitution functionality [detailed here](https://www.cloudquery.io/docs/advanced-topics/environment-variable-substitution)


2. Create a view for each client and table pair where the view only returns data for that specific client. Each record has a `_cq_source_name` that is the value in the `name` attribute of the source spec. So if you insert the identifier into the `name` attribute via variable substitution functionality [detailed here](https://www.cloudquery.io/docs/advanced-topics/environment-variable-substitution) you can create views that only contain the client data. For example:

```yml
kind: source
spec:
  # Source spec section
  name: aws-${CLIENT_IDENTIFIER}
  path: cloudquery/aws
  version: "v18.0.0"
  tables: ["aws_s3_buckets"]
  destinations: ["postgresql"]
```

and then in your PG database you can create a view like this:


```sql
CREATE OR REPLACE VIEW CLIENT_X_AWS_S3_BUCKETS AS
SELECT *
FROM AWS_S3_BUCKETS
WHERE "_cq_source_name" = 'aws-<CLIENT_IDENTIFIER>'
```
