### ISSUE TITLE
Support for ClickHouse ReplicatedMergeTree Table Engine

### ISSUE THREAD

**Issue by ethankelly99** [cloudquery/cloudquery#8667]
### Is your feature request related to a problem? Please describe.

CloudQuery uses the ClickHouse `MergeTree` table engine. We're running ClickHouse with multiple replicas and `MergeTree` tables don't handle replication. But ClickHouse supports replication with the `ReplicatedMergeTree` table engine.
### Describe the solution you'd like

It would be great if additional support could be added for using the `ReplicatedMergeTree` table engine for table creation.

This could possibly be done by adding a `replicated` option to the spec. If the option is true, the `ReplicatedMergeTree` engine is used, and if false (or omitted), the `MergeTree` engine is used.

The `ReplicatedMergeTree` table engine has mandatory configuration parameters that would also need to be exposed in the spec if using that table engine. I'll add details to the additional context that go into more detail.

There are also other table engines in the `*MergeTree` family (also with `Replicated*MergeTree` counterparts), so this could be a more generic feature if you'd like, but as you already support the `MergeTree` table engine, having it's Replicated counterpart seems like a good place to start (I also don't personally have a use-case for the other engines at the moment).

### Describe alternatives you've considered

It's possible to manually convert a MergeTree table to a ReplicatedMergeTree table as documented [here](https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/replication#converting-from-mergetree-to-replicatedmergetree). But would require manually managing the tables and moving data on the filesystem level which I'd like to avoid on a production setup.
### Additional context

As mentioned above, the `ReplicatedMergeTree` table engine has mandatory configuration parameters. It requires that the ZooKeeper path and replica name are specified. These can be provided as parameters to the Engine in the `CREATE TABLE` statement, or default values can be set in the ClickHouse configuration (so they wouldn't need to be provided to CloudQuery). The ClickHouse documentation explains that [here](https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/replication#replicatedmergetree-parameters).

**Some Other Useful Links**
- [Overview of the *MergeTree family of table engines](https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/mergetree)
- [Overview of replication with *MergeTree tables](https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/replication)

**Comment by candiduslynx** [comment]
Hi @ethankelly99!
I think this might be a more complex one.
In the broader scenario we'd like to use the `engine` spec option, that will have the following:

1. Engine name
2. Parameters to be passed to the engine itself (including some stubs to add table name, schema, etc)

This will definitely require some more thought, but I'd like to see what spec you might have in mind taking the previous into account.

**Comment by ethankelly99** [comment]
Hey @candiduslynx!
Yep, I fully agree, this is a more complex one.

I'll put a bit more thought into this one as well but based on what you wrote 3 initial ideas came to mind for the engine spec. I've used ReplicatingMergeTree in my examples but I think they should apply for all engines.

**Idea 1**
Having the parameters which should be passed to the table engine as an array of strings which are passed as positional parameters. Where an empty or omitted array would mean no parameters are passed. e.g.:
```yaml
engine:
  name: ReplicatingMergeTree
  parameters:
    - "/clickhouse/tables/{shard}/{database}/{table}"
    - "{replica}"
```

**Idea 2**
A really simplistic approach would be to have the parameters option as a simple string. e.g.:
```yaml
engine:
  name: ReplicatingMergeTree
  parameters: "/clickhouse/tables/{shard}/{database}/{table}, {replica}"
```

**Idea 3**
The most thorough would be to have a dictionary of supported parameter values for each supported engine type. Not sure if this is worth the extra maintenance effort though, especially with ClickHouse version changes. But this might make some kind of validation easier (if that's something you'd want). e.g.:
```yaml
engine:
  name: ReplicatingMergeTree
  parameters:
    zoo_path: "/clickhouse/tables/{shard}/{database}/{table}"
    replica_name: {replica}"
```

ClickHouse has built-in substitutions for `{database}` and `{table}` and when using replicas and shards also `{shard}` and `{replica}` (defined in the macros section of the ClickHouse config) so I don't think stubs will be needed for these. But I could be missing something.

At the moment I'd lean towards the first approach but I'll put more thought into it this evening and also try out a few things locally to see if anything else comes to mind.

Thanks for being so open to brainstorm this :)

**Comment by candiduslynx** [comment]
Thanks for the ideas @ethankelly99!
I like the 1st approach, too.
One thing to consider there is that sometimes parameters passed to the engine are not strings but numbers (see `ver` option [here](https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/replication/#replicatedmergetree-parameters)).

So, if we follow the 1st approach then the parameter list would allow specifying not only the string values, but numbers and booleans, too:

```yaml
engine:
  name: ReplicatedMergeTree
  parameters:
    - "/clickhouse/tables/{shard}/{database}/{table}"
    - "{replica}"
    - 123
```

Alternatively, we could treat all parameters as strings, but require users to specify additional single quotes in the param list (it will definitely make it easier for us, but I'm not sure it'll be preferred by the users):

```yaml
engine:
  name: ReplicatedMergeTree
  parameters:
    - "'/clickhouse/tables/{shard}/{database}/{table}'"
    - "'{replica}'"
    - "123"
```

**Comment by ethankelly99** [comment]
Ah yeah nice catch @candiduslynx! I had overlooked that completely. Apologies I'm only finding time to reply now.

I feel like you're right, that requiring users to wrap parameters in single quotes might lead to confusion. So I think your first approach is best.

But depending on the implementation effort required, treating all parameters as strings would also be acceptable (in my opinion) as long as this is clearly documented in the plugin spec.

I did some more reading on the different ClickHouse table engines yesterday. Do you already have an idea of which table engines should be supported by CloudQuery? I'm asking because I think it would make sense to limit support to a subset of the table engines ClickHouse offers.

**Some examples of why:**
The ["Special" category](https://clickhouse.com/docs/en/engines/table-engines/special/) of table engines has engines designed for specific use-cases which I don't think fit to CloudQuery data. For example, the `Distributed` table engine isn't designed to store data itself. It's designed to offer distributed query processing across multiple servers. It also doesn't support the `ORDER BY` clause.

The ["Integrations" family](https://clickhouse.com/docs/en/engines/table-engines/integrations/) has some engines engines that don't take any DDL parameters e.g. `Iceberg`:
```sql
CREATE TABLE iceberg_table
    ENGINE = Iceberg(url, [aws_access_key_id, aws_secret_access_key,])
```

My initial thought is that it makes sense to focus on the [`*MergeTree` family](https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/), which also includes the `Replicated*MergeTree` engines.

I think [this page](https://clickhouse.com/docs/en/engines/table-engines/special/) summarises the different families well.

I'd be very interested in hearing your thoughts.

**Comment by candiduslynx** [comment]
@ethankelly99 I think that [`*MergeTree` family](https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/) would be the best choice, too.

Like, if no engine was specified, we go for `MergeTree` engine, otherwise we check that the engine provided has `MergeTree` suffix (along with some SQL injections checks, naturally).

**Comment by candiduslynx** [comment]
Hi @ethankelly99!

I've implemented the `engine` option in #8844.
Would you be able to give it a go?

Format: 1st from https://github.com/cloudquery/cloudquery/issues/8667#issuecomment-1451410330

**Comment by ethankelly99** [comment]
Hi @candiduslynx!
Thanks for the heads up. Definitely, I'll give it a go today and let you know :)

**Comment by ethankelly99** [comment]
@candiduslynx I tested locally with the following configurations and everything worked as expected 🎉 

**ReplicatedMergeTree Engine:**
```yaml
spec:
    connection_string: "clickhouse://default:@localhost:9000/cloudquery?debug=true"
    cluster: default
    engine:
      name: ReplicatedMergeTree
      parameters:
        - "/clickhouse/tables/resources/{database}/{table}"
        - "{replica}-{shard}"
```

**ReplacingMergeTree Engine:**
```yaml
spec:
    connection_string: "clickhouse://default:@localhost:9000/cloudquery?debug=true"
    cluster: default
    engine:
        name: ReplacingMergeTree
```

**Default MergeTree Engine:**
```yaml
spec:
    connection_string: "clickhouse://default:@localhost:9000/cloudquery?debug=true"
    cluster: default
```

So this looks good to go to me!
