### ISSUE TITLE
New Destination Plugin: Meilisearch

### ISSUE THREAD

**Issue by rajaseg** [cloudquery/cloudquery#8857]
Hello Team,
Thank you very much for the project. It would be good to have a destination plugin for [Meilisearch](https://www.meilisearch.com/), an open-source standalone search engine written in [Rust](https://www.rust-lang.org/)

I tried Airbyte. But it requires a lot of resources to run and it only runs using docker.

**Comment by candiduslynx** [comment]
SDK: https://github.com/meilisearch/meilisearch-go

**Comment by rajaseg** [comment]
> Hi @rajaseg!
> 
> We've just released the [v1.0.0 of Meilisearch destination plugin](https://github.com/cloudquery/cloudquery/releases/tag/plugins-destination-meilisearch-v1.0.0). Feel free to poke around and kindly tell us if there're any issues you find.

Hi @candiduslynx, Thank you very much. I have tested it with [SharePoint Source Plugin](https://github.com/koltyakov/cq-source-sharepoint) and everything works as expected.

![image](https://user-images.githubusercontent.com/633479/228538937-b7e21f1d-edf3-4b36-8103-9c0c67a23e82.png)

**Comment by rajaseg** [comment]
Hi @candiduslynx, I am trying to test the Meilisearch Destination with SharePoint Online Source using GitHub Actions. I got below error even though I have the environment variables setup.

### CloudQuery.yml
```
kind: source
spec:
  name: "sharepoint"
  registry: "github"
  path: "koltyakov/sharepoint"
  version: "v1.6.2" # https://github.com/koltyakov/cq-source-sharepoint/releases
  destinations: ["meilisearch"]
  spec:
    auth:
      strategy: "${SP_AUTH_STRATEGY}"
      creds:
        siteUrl: ${SP_SITE_URL}
        clientId: ${SP_CLIENT_ID}
        clientSecret: ${SP_CLIENT_SECRET}
        realm: ${REALM}
    lists:
      _catalogs/users:
        select:
          - Title
          - FirstName
          - LastName
          - JobTitle
          - Department
          - EMail
          - Deleted
        filter: "UserName ne null"
        alias: "user"
      Shared Documents:
        select:
          - FileLeafRef -> file_name
          - FileRef -> file_path
          - FileDirRef -> file_dir
          - Author/Title -> author
          - File/Length -> file_size(mb)
          - EncodedAbsUrl -> file_url
          - EditorId -> editor
        expand:
          - File
          - Author
        alias: "shareddocs"
      Team Docs:
        select:
          - FileLeafRef -> file_name
          - FileRef -> file_path
          - FileDirRef -> file_dir
          - Author/Title -> author
          - File/Length -> file_size(mb)
          - EncodedAbsUrl -> file_url
          - EditorId -> editor
        expand:
          - File
          - Author
        alias: "teamdocs"
---
kind: destination
spec:
  name: "meilisearch"
  registry: "github"
  path: "cloudquery/meilisearch"
  version: "v1.1.0"
  write_mode: "overwrite"
  spec:
    api_key: ${MEILI_API_KEY}
    host: ${MEILI_HOST}
```
### GitHub Action Output
![image](https://user-images.githubusercontent.com/633479/231655170-11a01216-cb22-4d1c-9e34-e03d89988323.png)

### Secrets
![image](https://user-images.githubusercontent.com/633479/231655355-767de1b1-0678-444e-983b-48d63885ee5f.png)

Am I doing anything wrong? I tried with actual values instead of secrets, it works. Please have a look into the issue.

**Comment by candiduslynx** [comment]
Hi @rajaseg !
Could you share the workflow code with me?
If it's public, just a link to the file would be fine.
It might be that you forgot to add the env variable in the workflow or some typo, so I'd need that.

**Comment by rajaseg** [comment]
> Hi @rajaseg ! Could you share the workflow code with me? If it's public, just a link to the file would be fine. It might be that you forgot to add the env variable in the workflow or some typo, so I'd need that.

Hi @candiduslynx, Please find the link below for the repo.

https://github.com/rajaseg/etl

**Comment by rajaseg** [comment]
Hi @candiduslynx, It's my mistake. I forgot to add the environment variable in ```main.yml``` file. I have added them and it works as expected.

Sorry for it.
Here is the corrected workflow file (main.yml)
```
name: CloudQuery
on: [workflow_dispatch]

jobs:
  cloudquery:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cloudquery/setup-cloudquery@v3
        name: Setup CloudQuery
        with:
          version: "v2.4.1"
      - name: Sync with CloudQuery
        run: cloudquery sync cloudquery.yml --telemetry-level=none
        env:
          SP_AUTH_STRATEGY: ${{ secrets.SP_AUTH_STRATEGY }}
          SP_SITE_URL: ${{ secrets.SP_SITE_URL }}
          SP_CLIENT_ID: ${{ secrets.SP_CLIENT_ID }}
          SP_CLIENT_SECRET: ${{ secrets.SP_CLIENT_SECRET }}
          CQ_ELASTIC_PASSWORD: ${{ secrets.CQ_ELASTIC_PASSWORD }}
          REALM: ${{ secrets.REALM }}
          MEILI_HOST: ${{ secrets.MEILI_HOST }}
          MEILI_API_KEY: ${{ secrets.MEILI_API_KEY }}
```
