### ISSUE TITLE
bug: File Substitution For JSON

### ISSUE THREAD

**Issue by bbernays** [cloudquery/cloudquery#9094]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Documentation in [file substitution docs](https://www.cloudquery.io/docs/advanced-topics/environment-variable-substitution#json-files) doesn't match current behavior.

- Also if you use a single quote around `'${file:./jsongcp.json}'` --> you get the following error message:
```
Error: failed to load spec(s) from config.yml. Error: failed to unmarshal file config.yml: failed to convert yaml to json: yaml: line 11: did not find expected key
```

- In order for unmarshalling in source spec to work the json file needs to be a string rather than an object
- 

### Expected Behavior

Should all work

### CloudQuery (redacted) config

```
kind: source
spec:
  # Source spec section
  name: "gcp"
  # path: "cloudquery/gcp"
  # version: "v8.4.0"
  path: localhost:7777
  registry: grpc
  destinations: ["postgresql"]
  spec:
    project_ids: ["lab-account"]
    service_account_key_json: ${file:./jsongcp.json}
---
kind: destination
spec:
  # Destination spec section
  name: "postgresql"
  path: "cloudquery/postgresql"
  version: "v2.1.0"
  spec:
    connection_string: "postgresql://postgres:pass@localhost:5432/postgres?sslmode=disable"

```

### CloudQuery (redacted) logs

none

### CloudQuery version

cloudquery version 2.3.8

### Pull request (optional)

- [ ] I can submit a pull request
