### ISSUE TITLE
bug: postgresql unknown type character varying

### ISSUE THREAD

**Issue by reedlxm** [cloudquery/cloudquery#9141]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

as i want to sync from a postgresql to another postgresql,
take an error seams not support character varying type.

### Expected Behavior

i guess this is a bug or something goes wrong. that character varying is a very common type 

### CloudQuery (redacted) config

```
kind: source
spec:
  name: postgresql
  path: cloudquery/postgresql
  version: "v1.0.5"
  destinations: ["backup"]
  spec:
    connection_string: "postgres://"
---
kind: destination
spec:
  name: backup
  path: cloudquery/postgresql
  version: "v3.0.0"
  spec:
    connection_string: "postgres://"
```

### CloudQuery (redacted) logs

Starting migration with tables for: postgresql (v1.0.5) -> [backup (postgresql@v3.0.0)],
Error: failed to sync v1 source postgresql: failed to migrate source postgresql (v1.0.5) on destination backup (postgresql@v3.0.0) : failed to call Migrate: rpc error: code = Unknown desc = failed listing postgres tables: got unknown PostgreSQL type "character varying(150)" for column "" of table "" while trying to convert it to CloudQuery internal schema type. Supported PostgreSQL types are ["real" "macaddr[]" "inet" "macaddr" "inet[]" "float" "double precision" "text" "bytea" "uuid[]" "boolean" "bigint" "jsonb" "cidr[]" "bigint[]" "integer" "uuid" "text[]" "cidr" "timestamp"]

### CloudQuery version

docker leatest

### Pull request (optional)

- [ ] I can submit a pull request
