### ISSUE TITLE
bug: skip_dependent_tables behaviour

### ISSUE THREAD

**Issue by michalz-rely** [cloudquery/cloudquery#9160]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Source configuration, switch [skip_dependent_tables](https://www.cloudquery.io/docs/reference/source-spec#skip_dependent_tables) works only for the downstream dependency:

- When adding a top level table like **aws_accessanalyzer_analyzers** you get the following table in the DB
   - aws_accessanalyzer_analyzers

- When adding 2nd level table like **aws_accessanalyzer_analyzer_findings** you get the following tables in the DB
   - aws_accessanalyzer_analyzers
   - aws_accessanalyzer_analyzer_findings

### Expected Behavior

Instead of writing to the db tables that are not listed in the configuration file, consider writing to the log/stderr that you need to add an upstream table as well as you are going to sync dependent table. This way we can maintain the cohesion between configuration file and DB tables.

### CloudQuery (redacted) config

```yaml
kind: source
spec:
  name: aws 
  path: cloudquery/aws
  version: "v15.4.0"
  tables:
    - aws_accessanalyzer_analyzer_findings
  skip_dependent_tables: true
  concurrency: 500000
  destinations: ["postgresql"]
---
kind: destination
spec:
  name: postgresql
  path: cloudquery/postgresql
  version: "v2.1.5"
  write_mode: append
  spec:
    connection_string: ${PG_CONNECTION_STRING}
```

### CloudQuery (redacted) logs

sync successfull

### CloudQuery version

2.5.1

### Pull request (optional)

- [ ] I can submit a pull request
