### ISSUE TITLE
Investigation request: Investigate Azure plugin high memory usage

### ISSUE THREAD

**Issue by erezrokah** [cloudquery/cloudquery#9269]
We got reports of syncing on the `azure_compute_skus` compute table failing even with 8GB of memory, with reduced concurrency of `1000`.

We should investigate to see if this can be improved. One thing to note is the Azure client pre-initializes some data that is needed for multiplexing like `SubscriptionsObjects`, `ResourceGroups` and `registeredNamespaces`.
Example config:

```yaml
kind: source
spec:
  name: "azure"
  path: "cloudquery/azure"
  version: "v6.0.0"
  destinations: ["postgres"]
  tables: ["azure_compute_skus"]
```
