### ISSUE TITLE
Azure error with plugin ERR table resolver finished with error error="AzureCLICredential: signal: killed"

### ISSUE THREAD

**Issue by amirnasimzadabytedance** [cloudquery/cloudquery#9337]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hello, 

After following guides from the website I keep getting this error with my azure plugin, I verified my permissions are valid and was able to login using the az cli (az login) when I export the findings to my az blob destination the file comes out blank and I got a bunch of errors in my cloudquery.log file in particular this one:

ERR table resolver finished with error error="AzureCLICredential: signal: killed"

Any idea of what I should do? Tried upgrading go by doing some research but that didn't help.

### Expected Behavior

Expected a csv file with all of my different cloud resources in Azure.

### CloudQuery (redacted) config

```yaml
kind: source
spec:
  # Source spec section
  name: "azure"
  path: "cloudquery/azure"
  version: "v5.2.0"
  destinations: ["azblob"]

  spec:
    # Azure Spec section
    subscriptions: [""]
```

### CloudQuery (redacted) logs

ERR table resolver finished with error error="AzureCLICredential: signal: killed"

### CloudQuery version

cloudquery version 2.5.1

### Pull request (optional)

- [ ] I can submit a pull request

**Comment by erezrokah** [comment]
Hi @amirnasimzadabytedance, thank you for opening the issue and sorry you're running into it when setting up CloudQuery.
That error usually means that the CloudQuery is trying to use up all the available memory on the machine its running on.

Can you trying setting a lower concurrency setting that the default, see https://www.cloudquery.io/docs/advanced-topics/performance-tuning#tune-concurrency

An example config would look like:
```yaml
kind: source
spec:
  name: "azure"
  path: "cloudquery/azure"
  version: "v5.2.0"
  concurrency: 1000
  destinations: ["postgres"]
```
