### ISSUE TITLE
bug: Azure `azure_subscription_subscription_locations` always fails with an error

### ISSUE THREAD

**Issue by erezrokah** [cloudquery/cloudquery#9366]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Trying to sync `azure_subscription_subscription_locations` always fails with an error:

```
GET https://management.azure.com/subscriptions//subscriptions/<id>/locations
--------------------------------------------------------------------------------
RESPONSE 400: 400 Bad Request
ERROR CODE: InvalidSubscriptionId
--------------------------------------------------------------------------------
{
  \"error\": {
    \"code\": \"InvalidSubscriptionId\",
    \"message\": \"The provided subscription identifier 'subscriptions' is malformed or invalid.\"
  }
}
--------------------------------------------------------------------------------

```

### Expected Behavior

Syncing the table should not fail

### CloudQuery (redacted) config

```yaml
kind: source
spec:
  name: azure
  version: "v6.0.0"
  destinations: [postgresql]
  path: cloudquery/azure
  tables: [azure_subscription_subscription_locations]
---
kind: destination
spec:
  name: postgresql
  path: cloudquery/postgresql
  version: v3.0.2
  spec:
    connection_string: postgresql://postgres:pass@localhost:5432/postgres
```

### Steps To Reproduce

1. Run a sync with the supplied configuration
2. See error

### CloudQuery (redacted) logs

Provider above

### CloudQuery version

cloudquery version 2.5.2

### Pull request (optional)

- [X] I can submit a pull request
