### ISSUE TITLE
bug: cloudquery forced migration mode is failing with SQL State 2BP01

### ISSUE THREAD

**Issue by hariiwill** [cloudquery/cloudquery#9657]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Migration is failing with mode=forced

### Expected Behavior

migration should be done 

### CloudQuery (redacted) config

```
kind: destination
spec:
  migrate_mode: forced
  name: postgresql
  path: cloudquery/postgresql
  spec:
    connection_string: ${PG_CONNECTION_STRING}
  version: v2.1.4
  write_mode: overwrite-delete-stale
```

```
kind: source
spec:
  destinations:
  - postgresql
  name: aws
  path: cloudquery/aws
  version: v15.3.0
```

### CloudQuery (redacted) logs

Starting migration for: aws -> [postgresql] with 542 tables
Error: failed to migrate source aws: failed to migrate source aws on destination postgresql : failed to call Migrate: rpc error: code = Unknown desc = failed to drop table aws_apigateway_rest_api_stages: ERROR: cannot drop table aws_apigateway_rest_api_stages because other objects depend on it (SQLSTATE 2BP01)

### CloudQuery version

2.4.1

### Pull request (optional)

- [X] I can submit a pull request
