### ISSUE TITLE
creating-new-plugin.md typo

### ISSUE THREAD

**Issue by kaihuhw** [cloudquery/cloudquery#9767]
registry is set to "path" instead of local in creating-new-plugin.md at Line 238 
https://github.com/cloudquery/cloudquery/blob/main/website/pages/docs/developers/creating-new-plugin.md?plain=1#L238

This will create a binary with the name of the plugin directory (so, `cq-source-<plugin-name>`). We can then refer to this binary by setting the registry to `local` and `path` as the path to the binary. Example:

```yaml copy filename=config.yaml
kind: source
spec:
  name: "xkcd"
  registry: "path"
  path: "/path/to/cq-source-xkcd"
  version: "v1.0.0"
  tables: 
    ["*"]
  destinations:
    - "sqlite"
---
kind: destination
spec:
  name: sqlite
  path: cloudquery/sqlite
  version: "v1.2.1"
  spec:
    connection_string: ./db.sql
```
