### ISSUE TITLE
bug: `_cq_id` is deterministic when it should be random

### ISSUE THREAD

**Issue by bbernays** [cloudquery/cloudquery#9845]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When a user is using `deterministic_cq_id` and syncing a table that has no PKs defined, then the `_cq_id` will be deterministic. This means only a single record will only ever show up for that table no matter what

### Expected Behavior

when `_cq_id` is the only PK, then it should always be random

### CloudQuery (redacted) config

```yml
ind: source
spec:
  # Source spec section
  name: aws
  registry: grpc
  path: localhost:7777
  tables: 
    - "aws_iam_users"  
  skip_tables: ["aws_iam*_last_accessed_details", "aws_cloudtrail_events"] 
  deterministic_cq_id: true
  destinations: [ "postgresql"]
---
kind: destination
spec:
  pk_mode: cq-id-only
  name: "postgresql"
  # registry: "github"
  # path: "cloudquery/postgresql"
  # version: "v3.0.3"
  registry: grpc
  path: localhost:7778

  migrate_mode: forced
  spec:
    connection_string: "postgresql://postgres:pass@localhost:5432/postgres?sslmode=disable"
```

### Steps To Reproduce

run sync

### CloudQuery (redacted) logs

no relevant logs

### CloudQuery version

all

### Pull request (optional)

- [X] I can submit a pull request
